### ISSUE TITLE
Running on Home Assistant 0.118.5 with Python 3.8.6

### ISSUE THREAD

**Issue by mvimercati** [ollo69/ha-smartthinq-sensors#111]
Recently updated to Home Assistant 0.118.5 with Python 3.8.6 (pyenv on Raspian/RPI).
The plugin doesn't start, the following log messages are traced:

```
Logger: aiohttp.server
Source: deps/lib/python3.8/site-packages/pycountry/__init__.py:12
First occurred: 22:44:11 (1 occurrences)
Last logged: 22:44:11
Error handling request

Traceback (most recent call last):
  File "/home/homeassistant/.pyenv/versions/3.8.6/lib/python3.8/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request
    resp = await self._request_handler(request)
  File "/home/homeassistant/.pyenv/versions/3.8.6/lib/python3.8/site-packages/aiohttp/web_app.py", line 499, in _handle
    resp = await handler(request)
  File "/home/homeassistant/.pyenv/versions/3.8.6/lib/python3.8/site-packages/aiohttp/web_middlewares.py", line 118, in impl
    return await handler(request)
  File "/home/homeassistant/.pyenv/versions/3.8.6/lib/python3.8/site-packages/homeassistant/components/http/request_context.py", line 18, in request_context_middleware
    return await handler(request)
  File "/home/homeassistant/.pyenv/versions/3.8.6/lib/python3.8/site-packages/homeassistant/components/http/ban.py", line 72, in ban_middleware
    return await handler(request)
  File "/home/homeassistant/.pyenv/versions/3.8.6/lib/python3.8/site-packages/homeassistant/components/http/auth.py", line 127, in auth_middleware
    return await handler(request)
  File "/home/homeassistant/.pyenv/versions/3.8.6/lib/python3.8/site-packages/homeassistant/components/http/view.py", line 129, in handle
    result = await result
  File "/home/homeassistant/.pyenv/versions/3.8.6/lib/python3.8/site-packages/homeassistant/components/config/config_entries.py", line 136, in post
    return await super().post(request)
  File "/home/homeassistant/.pyenv/versions/3.8.6/lib/python3.8/site-packages/homeassistant/components/http/data_validator.py", line 60, in wrapper
    result = await method(view, request, *args, **kwargs)
  File "/home/homeassistant/.pyenv/versions/3.8.6/lib/python3.8/site-packages/homeassistant/helpers/data_entry_flow.py", line 69, in post
    result = await self._flow_mgr.async_init(
  File "/home/homeassistant/.pyenv/versions/3.8.6/lib/python3.8/site-packages/homeassistant/data_entry_flow.py", line 119, in async_init
    flow = await self.async_create_flow(handler, context=context, data=data)
  File "/home/homeassistant/.pyenv/versions/3.8.6/lib/python3.8/site-packages/homeassistant/config_entries.py", line 535, in async_create_flow
    integration.get_platform("config_flow")
  File "/home/homeassistant/.pyenv/versions/3.8.6/lib/python3.8/site-packages/homeassistant/loader.py", line 424, in get_platform
    cache[full_name] = self._import_platform(platform_name)
  File "/home/homeassistant/.pyenv/versions/3.8.6/lib/python3.8/site-packages/homeassistant/loader.py", line 429, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
  File "/home/homeassistant/.pyenv/versions/3.8.6/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/homeassistant/.homeassistant/custom_components/smartthinq_sensors/config_flow.py", line 3, in <module>
    import pycountry
  File "/home/homeassistant/.homeassistant/deps/lib/python3.8/site-packages/pycountry/__init__.py", line 12, in <module>
    __version__ = pkg_resources.get_distribution("pycountry").version
  File "/home/homeassistant/.pyenv/versions/3.8.6/lib/python3.8/site-packages/pkg_resources/__init__.py", line 480, in get_distribution
    dist = get_provider(dist)
  File "/home/homeassistant/.pyenv/versions/3.8.6/lib/python3.8/site-packages/pkg_resources/__init__.py", line 356, in get_provider
    return working_set.find(moduleOrReq) or require(str(moduleOrReq))[0]
  File "/home/homeassistant/.pyenv/versions/3.8.6/lib/python3.8/site-packages/pkg_resources/__init__.py", line 899, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/home/homeassistant/.pyenv/versions/3.8.6/lib/python3.8/site-packages/pkg_resources/__init__.py", line 785, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'pycountry' distribution was not found and is required by the application
```

even if pycountry seems installed.
Thanks for your support

**Comment by KTibow** [comment]
Could you use 3 backticks for code blocks? Also try beta HA and see if the 3.9 helps.

**Comment by mvimercati** [comment]
Anyone using with Python 3.8? A friend of mine does not have problems, so it may be just a problem with my installation.

**Comment by biagioDO** [comment]
> Just discovered that my hass installation has some problems with pip, maybe too updated (20.3.1). Probably the pycountry package could not be installed correctly. Fixed the dependency error I got back my dryer sensors :)
> I think you can close this issue....

I have  Home Assistant 0.110.3 with Python 3.8.0 and I have the same error, could you explain how update the dependency?
I  run this command 
apt-get install -y python3-pycountry
and I reboot HA but nothing change

**Comment by KTibow** [comment]
Try rebooting. You use pip, not apt, for most Python packages.

**Comment by biagioDO** [comment]
I also run this command
pip3 install pycountry
and I received this message
Requirement already satisfied: pycountry in /usr/lib/python3/dist-packages (17.5.14)

**Comment by KTibow** [comment]
Are you sure you're running that on HA and not your local machine?

**Comment by biagioDO** [comment]
Home Assistant run on Odroid C1 with DietPi v6.34.3, sorry I don't understand your question

**Comment by KTibow** [comment]
How are you running the command? Command line? SSH add-on?

**Comment by biagioDO** [comment]
I run the command in command line, I don't have installed SSH addon

**Comment by hmoffatt** [comment]
But did you run it in the homeassistant pyenv?

**Comment by mvimercati** [comment]
> I have Home Assistant 0.110.3 with Python 3.8.0 and I have the same error, could you explain how update the dependency?

My problem probably was due to version of pip itself, that I forced to be updated to 20.3.1 while hass needed 20.2.something.
Please check which version of pip you have installed in your home assistant python environment. I understood that if you update the hass installation you get back all the correct dependencies.

**Comment by biagioDO** [comment]
I think it run in pyenv, I installed HA through dietpi-software that is an automatism for install software.
I also run this command
su -s /bin/bash homeassistant
pip3 install pycountry
Requirement already satisfied: pycountry in /usr/lib/python3/dist-packages (17.5.14)

**Comment by biagioDO** [comment]
My pip version is 
pip 18.1 from /usr/lib/python3/dist-packages/pip 
How force update version?

**Comment by biagioDO** [comment]
Solved
On the system there are python 3.7 and when I run pip3  install pycountry don't update HA, because HA use another version of python inside homeassistant folder.
 So i run this command
/home/homeassistant/.pyenv/versions/3.8.0/bin/pip3 install pycountry
and finally I reinstalled the LG components
