### ISSUE TITLE
Dryer beta testing

### ISSUE THREAD

**Issue by towerhand** [ollo69/ha-smartthinq-sensors#12]
I got this error with v0.2.1

```
Logger: homeassistant.core
Source: custom_components/smartthinq_washer/sensor.py:447 
First occurred: 12:03:38 PM (3 occurrences) 
Last logged: 12:04:37 PM

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 552, in _update_entity_states
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 284, in async_update_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 328, in _async_write_ha_state
    attr.update(self.device_state_attributes or {})
  File "/config/custom_components/smartthinq_washer/sensor.py", line 382, in device_state_attributes
    ATTR_RESERVE_TIME: self._reserve_time,
  File "/config/custom_components/smartthinq_washer/sensor.py", line 447, in _reserve_time
    if int(reserve_min) < 10:
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
```

**Comment by ollo69** [comment]
Ok, so dryer do not have reserved time (I was having this doubt) :)
I will remove and release shortly a new version...

**Comment by ollo69** [comment]
0.2.2 available

**Comment by towerhand** [comment]
```
2020-04-13 12:16:51 WARNING (MainThread) [custom_components.smartthinq_washer.wideq.device] ThinQ: received unknown DRYER status '@WM_OPTION_TEMP_MEDIUM_W' of type 'TempControl'
2020-04-13 12:16:51 WARNING (MainThread) [custom_components.smartthinq_washer.wideq.device] ThinQ: received unknown DRYER status '@WM_OPTION_DRY_NORMAL_W' of type 'DryLevel'
```
I'm assuming this are the right ones. I'm gonna confirm  and be back in a few minutes.

'TempControl'
'@WM_OPTION_TEMP_HIGH_W'
'@WM_OPTION_TEMP_MIDHIGH_W'
'@WM_OPTION_TEMP_MEDIUM_W'
'@WM_OPTION_TEMP_LOW_W'
'@WM_OPTION_TEMP_ULTRALOW_W'

'DryLevel'
'@WM_OPTION_DRY_VERY_W' 
'@WM_OPTION_DRY_MORE_W' 
'@WM_OPTION_DRY_NORMAL_W' 
'@WM_OPTION_DRY_LESS_W' 
'@WM_OPTION_DRY_DAMP_W'

**Comment by daveonkels** [comment]
No errors in the log and most of the attributes are recognized. Nice job @ollo69 

<img width="353" alt="Screen Shot 2020-04-13 at 10 21 16 AM" src="https://user-images.githubusercontent.com/533642/79142601-9b16e700-7d70-11ea-852a-7a2fe355f9d6.png">

**Comment by ollo69** [comment]
Seems that your dryer have "reserve time", so probably I have to manage cases. Which version are you ussing for this test, 0.2.1?

**Comment by ollo69** [comment]
> These errors on the logs.
> 
> ```
> 2020-04-13 12:16:51 WARNING (MainThread) [custom_components.smartthinq_washer.wideq.device] ThinQ: received unknown DRYER status '@WM_OPTION_TEMP_MEDIUM_W' of type 'TempControl'
> 2020-04-13 12:16:51 WARNING (MainThread) [custom_components.smartthinq_washer.wideq.device] ThinQ: received unknown DRYER status '@WM_OPTION_DRY_NORMAL_W' of type 'DryLevel'
> ```
> 
> I'm assuming this are the right ones. I'm gonna confirm and be back in a few minutes.
> 
> 'TempControl'
> '@WM_OPTION_TEMP_HIGH_W'
> '@WM_OPTION_TEMP_MEDIUM_HIGH_W'
> '@WM_OPTION_TEMP_MEDIUM_W'
> '@WM_OPTION_TEMP_LOW_W'
> '@WM_OPTION_TEMP_ULTRA_LOW_W'
> 
> 'DryLevel'
> '@WM_OPTION_DRY_VERY_DRY_W'
> '@WM_OPTION_DRY_MORE_DRY_W'
> '@WM_OPTION_DRY_NORMAL_W'
> '@WM_OPTION_DRY_LESS_DRY_W'
> '@WM_OPTION_DRY_DAMP_DRY_W'
> 
> Edit: updated it.

Wait for your confirmation, then I will update states list and release with new version

**Comment by daveonkels** [comment]
I was running 0.2.1 in that post - updating to 0.2.2 now and will report back.

**Comment by towerhand** [comment]
Updated my previous post @ollo69

**Comment by ollo69** [comment]
But I only removed reserves time that  will not compare to you anymore.
It is better that you stay on this version, I will release a new one later managing the availbility of the attribute.

**Comment by daveonkels** [comment]
Here's the log output after upgrading to 0.2.2
```
2020-04-13 10:34:32 WARNING (MainThread) [custom_components.smartthinq_washer.wideq.device] ThinQ: received unknown WASHER status '@WM_STATE_COMPLETE_W' of type 'status'
2020-04-13 10:34:32 WARNING (MainThread) [custom_components.smartthinq_washer.wideq.device] ThinQ: received unknown DRYER status 'unknown' of type 'TempControl'
```

**Comment by sagitt** [comment]
Not show my dryer :(

**Comment by ollo69** [comment]
> Not show my dryer :(

Do you login with APIv2 in login? I need log, possible at debug level, or I will not able to fix

**Comment by sagitt** [comment]
> > Not show my dryer :(
> 
> Do you login with APIv2 in login? I need log, possible at debug level, or I will not able to fix

How can do this?

**Comment by towerhand** [comment]
@sagitt After installing the custom component via HACS, add the integration and tick the checkmark for V2 API.

@ollo69 Any reason to keep the option for V1 API?

**Comment by ollo69** [comment]
> @ollo69 Any reason to keep the option for V1 API?

Just in case someone have issue with V2. But use ApiV2 should be checked by default, isn't it?

**Comment by towerhand** [comment]
I don't think it did but I wasn't really paying attention at that.

**Comment by sagitt** [comment]
> @sagitt After installing the custom component via HACS, add the integration and tick the checkmark for V2 API.
> 
> @ollo69 Any reason to keep the option for V1 API?

done, so yaml mode can't do this, right?

**Comment by ollo69** [comment]
right, with configuration.yaml you cannot configure APIv2. Fridge in the future....

**Comment by towerhand** [comment]
Just making sure you saw I updated the post with the missing states.
```
2020-04-13 12:16:51 WARNING (MainThread) [custom_components.smartthinq_washer.wideq.device] ThinQ: received unknown DRYER status '@WM_OPTION_TEMP_MEDIUM_W' of type 'TempControl'
2020-04-13 12:16:51 WARNING (MainThread) [custom_components.smartthinq_washer.wideq.device] ThinQ: received unknown DRYER status '@WM_OPTION_DRY_NORMAL_W' of type 'DryLevel'
2020-04-13 12:23:33 WARNING (MainThread) [custom_components.smartthinq_washer.wideq.device] ThinQ: received unknown DRYER status '@WM_OPTION_TEMP_MEDIUM_HIGH_W' of type 'TempControl'
2020-04-13 12:24:01 WARNING (MainThread) [custom_components.smartthinq_washer.wideq.device] ThinQ: received unknown DRYER status '@WM_OPTION_TEMP_ULTRA_LOW_W' of type 'TempControl'
2020-04-13 12:24:01 WARNING (MainThread) [custom_components.smartthinq_washer.wideq.device] ThinQ: received unknown DRYER status '@WM_OPTION_DRY_DAMP_DRY_W' of type 'DryLevel'
2020-04-13 12:24:32 WARNING (MainThread) [custom_components.smartthinq_washer.wideq.device] ThinQ: received unknown DRYER status '@WM_OPTION_TEMP_HIGH_W' of type 'TempControl'
2020-04-13 12:24:32 WARNING (MainThread) [custom_components.smartthinq_washer.wideq.device] ThinQ: received unknown DRYER status '@WM_OPTION_DRY_VERY_DRY_W' of type 'DryLevel'
2020-04-13 12:31:17 WARNING (MainThread) [custom_components.smartthinq_washer.wideq.device] ThinQ: received unknown DRYER status '@WM_OPTION_TEMP_LOW_W' of type 'TempControl'
2020-04-13 12:31:17 WARNING (MainThread) [custom_components.smartthinq_washer.wideq.device] ThinQ: received unknown DRYER status '@WM_OPTION_DRY_MORE_DRY_W' of type 'DryLevel'
2020-04-13 12:31:45 WARNING (MainThread) [custom_components.smartthinq_washer.wideq.device] ThinQ: received unknown DRYER status '@WM_OPTION_DRY_LESS_DRY_W' of type 'DryLevel'
```
'TempControl'
'@WM_OPTION_TEMP_HIGH_W'
'@WM_OPTION_TEMP_MEDIUM_HIGH_W'
'@WM_OPTION_TEMP_MEDIUM_W'
'@WM_OPTION_TEMP_LOW_W'
'@WM_OPTION_TEMP_ULTRA_LOW_W'

'DryLevel'
'@WM_OPTION_DRY_VERY_DRY_W'
'@WM_OPTION_DRY_MORE_DRY_W'
'@WM_OPTION_DRY_NORMAL_W'
'@WM_OPTION_DRY_LESS_DRY_W'
'@WM_OPTION_DRY_DAMP_DRY_W'

**Comment by kenmaples** [comment]
Couple errors in the logs running 0.2.2, but overall impressive.
![Dryer](https://user-images.githubusercontent.com/2633530/79153270-70ce2500-7d82-11ea-87d9-a274bac9552c.png)

Logger: custom_components.smartthinq_washer.wideq.device
Source: custom_components/smartthinq_washer/wideq/device.py:715
First occurred: 11:46:34 AM (3 occurrences)
Last logged: 11:46:36 AM

ThinQ: received unknown WASHER status '@WM_STATE_COMPLETE_W' of type 'status'
ThinQ: received unknown DRYER status 'unknown' of type 'TempControl'
ThinQ: received unknown DRYER status '@WM_TERM_NO_SELECT_W' of type 'DryLevel'

`2020-04-13 11:46:34 WARNING (MainThread) [custom_components.smartthinq_washer.wideq.device] ThinQ: received unknown WASHER status '@WM_STATE_COMPLETE_W' of type 'status'
2020-04-13 11:46:36 WARNING (MainThread) [custom_components.smartthinq_washer.wideq.device] ThinQ: received unknown DRYER status 'unknown' of type 'TempControl'
2020-04-13 11:46:36 WARNING (MainThread) [custom_components.smartthinq_washer.wideq.device] ThinQ: received unknown DRYER status '@WM_TERM_NO_SELECT_W' of type 'DryLevel'`

**Comment by towerhand** [comment]
Looking good on my end with v0.2.3 so far. No errors. Great job and thanks.

**Comment by kenmaples** [comment]
I got one error on 0.2.3:

`2020-04-13 15:22:55 WARNING (MainThread) [custom_components.smartthinq_washer.wideq.device] ThinQ: received unknown DRYER status '@WM_TERM_NO_SELECT_W' of type 'DryLevel'`

**Comment by pigmos** [comment]
I got this error: on 0.2.4:

2020-04-14 10:18:56 WARNING (MainThread) [custom_components.smartthinq_washer.wideq.device] ThinQ: received unknown DRYER status '@WM_DRY24_DRY_LEVEL_CUPBOARD_W' of type 'DryLevel'

**Comment by sagitt** [comment]
i see this

Dettagli registro (WARNING)
Logger: custom_components.smartthinq_washer.wideq.device
Source: custom_components/smartthinq_washer/wideq/device.py:720
First occurred: 8:05:24 (1 occurrences)
Last logged: 8:05:24

ThinQ: received unknown DRYER status 'unknown' of type 'status'

![Schermata 2020-04-14 alle 10 34 00](https://user-images.githubusercontent.com/169086/79203537-789dd000-7e3b-11ea-900e-5ef591e33276.png)

**Comment by boralyl** [comment]
Haven't tried running the dryer yet, but so far it was found automatically and no errors in the logs.
![image](https://user-images.githubusercontent.com/109865/79410421-38cb0b80-7f55-11ea-97e8-f43b84291b34.png)

**Comment by boralyl** [comment]
Haven't tried running the dryer yet, but it was found automatically with no errors in the logs.

![Untitled](https://user-images.githubusercontent.com/109865/79410512-80519780-7f55-11ea-8175-539d8d8a6172.png)
