### ISSUE TITLE
[BUG] Washer is unavailable

### ISSUE THREAD

**Issue by neskycz** [ollo69/ha-smartthinq-sensors#144]
**Describe the bug**
After update HA is washer unavailable

**Environment details:**
 - Environment (HASSIO, Raspbian, etc): hassio
 - Home Assistant version installed: Home Assistant OS 5.13, supervisor-2021.03.9, core-2021.4.0
 - Component version installed: last
 - Last know working version: before last
 - LG device type and model with issue: WTDN3-FL (WASHER), Firmware: QC_Modem_1.2.79 

**Output of HA logs**
Logger: homeassistant.components.sensor
Source: util/async_.py:139
Integration: Senzor (documentation, issues)
First occurred: 12:53:25 (2 occurrences)
Last logged: 13:09:15

Error while setting up smartthinq_washer platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 205, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/smartthinq_washer/sensor.py", line 80, in async_setup_entry
    dev = LGEWasherDevice(client, device, base_name)
  File "/config/custom_components/smartthinq_washer/sensor.py", line 112, in __init__
    super().__init__(WasherDevice(client, device), name)
  File "/config/custom_components/smartthinq_washer/wideq/device.py", line 566, in __init__
    model_data = client.model_info(device)
  File "/config/custom_components/smartthinq_washer/wideq/core_v2.py", line 732, in model_info
    self._model_info[url] = device.load_model_info()
  File "/config/custom_components/smartthinq_washer/wideq/device.py", line 233, in load_model_info
    return requests.get(info_url, timeout=DEFAULT_TIMEOUT).json()
  File "/usr/local/lib/python3.8/site-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 394, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/local/lib/python3.8/site-packages/urllib3/connection.py", line 234, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/usr/local/lib/python3.8/http/client.py", line 1255, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.8/http/client.py", line 1266, in _send_request
    self.putrequest(method, url, **skips)
  File "/usr/local/lib/python3.8/site-packages/urllib3/connection.py", line 214, in putrequest
    return _HTTPConnection.putrequest(self, method, url, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/util/async_.py", line 150, in protected_loop_func
    check_loop()
  File "/usr/src/homeassistant/homeassistant/util/async_.py", line 139, in check_loop
    raise RuntimeError(
RuntimeError: I/O must be done in the executor; Use `await hass.async_add_executor_job()` at custom_components/smartthinq_washer/wideq/device.py, line 233: return requests.get(info_url, timeout=DEFAULT_TIMEOUT).json()

**Comment by ollo69** [comment]
Looking at your log you are using a very old version of the component: 

/config/custom_components/**smartthinq_washer**/sensor.py

The folder `smartthinq_washer` was changed in `smartthinq_sensors` about 1 years ago.

You need to clean-up your configuration and re-install and reconfigure the integration.

**Comment by neskycz** [comment]
Thank you for the quick reply.

**Comment by ollo69** [comment]
Can we close this issue?
