### ISSUE TITLE
Sensor update failure

### ISSUE THREAD

**Issue by daveonkels** [ollo69/ha-smartthinq-sensors#15]
Browsing through my logs this morning and noticed the following error in the event it's useful.

**HA Version:** Home Assistant Core 0.108.6
**SmartThinQ Integration:** 0.2.4

`2020-04-18 08:23:11 ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor.lg_washer fails
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/urllib3/connection.py", line 160, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "/usr/local/lib/python3.7/site-packages/urllib3/util/connection.py", line 61, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/local/lib/python3.7/socket.py", line 752, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Try again
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 677, in urlopen
    chunked=chunked,
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 381, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 976, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.7/site-packages/urllib3/connection.py", line 308, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.7/site-packages/urllib3/connection.py", line 172, in _new_conn
    self, "Failed to establish a new connection: %s" % e
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7fe3e16e4bd0>: Failed to establish a new connection: [Errno -3] Try again
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 725, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/usr/local/lib/python3.7/site-packages/urllib3/util/retry.py", line 439, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='aic-service.lgthinq.com', port=46030): Max retries exceeded with url: /v1/service/application/dashboard (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fe3e16e4bd0>: Failed to establish a new connection: [Errno -3] Try again'))
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 279, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 476, in async_device_update
    await self.hass.async_add_executor_job(self.update)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/smartthinq_washer/__init__.py", line 335, in update
    raise ex
  File "/config/custom_components/smartthinq_washer/__init__.py", line 321, in update
    state = self._device.poll()
  File "/config/custom_components/smartthinq_washer/wideq/washer.py", line 29, in poll
    res = self.device_poll("washerDryer")
  File "/config/custom_components/smartthinq_washer/wideq/device.py", line 651, in device_poll
    self._client.refresh_devices()
  File "/config/custom_components/smartthinq_washer/wideq/core_v2.py", line 605, in refresh_devices
    self._load_devices(True)
  File "/config/custom_components/smartthinq_washer/wideq/core_v2.py", line 560, in _load_devices
    self._devices = self._session.get_devices()
  File "/config/custom_components/smartthinq_washer/wideq/core_v2.py", line 421, in get_devices
    devices = self.get2("service/application/dashboard").get("item", [])
  File "/config/custom_components/smartthinq_washer/wideq/core_v2.py", line 413, in get2
    language=self.auth.gateway.language,
  File "/config/custom_components/smartthinq_washer/wideq/core_v2.py", line 133, in thinq2_get
    timeout=DEFAULT_TIMEOUT,
  File "/usr/local/lib/python3.7/site-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='aic-service.lgthinq.com', port=46030): Max retries exceeded with url: /v1/service/application/dashboard (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fe3e16e4bd0>: Failed to establish a new connection: [Errno -3] Try again'))`

**Comment by ollo69** [comment]
This are network related issue.
