### ISSUE TITLE
Entities not created during initial configuration

### ISSUE THREAD

**Issue by sbrighty** [ollo69/ha-smartthinq-sensors#151]
**Describe the bug**
During the initial configuration two devices are created but the associated entities are not

**Screenshots**
![image](https://user-images.githubusercontent.com/83114211/116813903-9ac6d500-ab99-11eb-9bad-4295300822e0.png)
![image](https://user-images.githubusercontent.com/83114211/116813923-afa36880-ab99-11eb-9ded-f40437eca27f.png)

**Environment details:**
HACS Docker
LG Aircon, L/P28AWN-14

**Output of HA logs**
2021-05-02 12:26:09 ERROR (MainThread) [homeassistant.components.sensor] The thinq_v2 platform for the sensor integration does not support platform setup. Please remove it from your config.
2021-05-02 12:26:09 ERROR (MainThread) [homeassistant.components.climate] The thinq_v2 platform for the climate integration does not support platform setup. Please remove it from your config.
2021-05-02 12:26:14 ERROR (MainThread) [homeassistant.components.climate] Error adding entities for domain climate with platform thinq_v2
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 322, in async_add_entities
await asyncio.gather(*tasks)
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 429, in _async_add_entity
capabilities=entity.capability_attributes,
File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 190, in capability_attributes
ATTR_HVAC_MODES: self.hvac_modes,
File "/config/custom_components/thinq_v2/climate.py", line 222, in hvac_modes
return [
File "/config/custom_components/thinq_v2/climate.py", line 226, in <listcomp>
in self._ac.model.value("airState.opMode").options.values()
File "/usr/local/lib/python3.8/site-packages/wideq/client.py", line 347, in value
d = self.data["Value"][name]
KeyError: 'airState.opMode'
2021-05-02 12:26:14 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 322, in async_add_entities
await asyncio.gather(*tasks)
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 429, in _async_add_entity
capabilities=entity.capability_attributes,
File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 190, in capability_attributes
ATTR_HVAC_MODES: self.hvac_modes,
File "/config/custom_components/thinq_v2/climate.py", line 222, in hvac_modes
return [
File "/config/custom_components/thinq_v2/climate.py", line 226, in <listcomp>
in self._ac.model.value("airState.opMode").options.values()
File "/usr/local/lib/python3.8/site-packages/wideq/client.py", line 347, in value
d = self.data["Value"][name]
KeyError: 'airState.opMode'

**Additional context**
I've tried removing and re-adding the integration. Can confirm that everything works fine in the LG ThinQ ios App.

**Comment by ollo69** [comment]
You probably open issue in wrong repository, I don't know what is `thinq_v2` integration. AC is still not supported here, please close this issue and move to right repository.

**Comment by sbrighty** [comment]
Apologies, closing. Opened in the correct repository. https://github.com/marciogranzotto/hass-smartthinq/issues/19
