### ISSUE TITLE
[Feature Request] - Control the refrigerator temperature

### ISSUE THREAD

**Issue by roleoroleo** [ollo69/ha-smartthinq-sensors#153]
Would it be possible to add the functionality to set the temperature for the fridge and the freezer?
If I'm not wrong wideq supports it.

Thanks for your work.

**Comment by ollo69** [comment]
Yes, it is possible, but I have to think how exactly manage this in HA. In last version I started adding a switch to control ecoFriendly functionality, could you check if is working (if you refrigerator have this feature)? Thx

**Comment by roleoroleo** [comment]
Sorry but my fridge doesn't support ecoFriendly.
Maybe a climate entity? Like a thermostat?

**Comment by roleoroleo** [comment]
There isn't ecoFriendly but there is express freeze if it can help you.

**Comment by ollo69** [comment]
> Maybe a climate entity? Like a thermostat?

Yes, it could be an option,


> There isn't ecoFriendly but there is express freeze if it can help you.

No problem, I will try to manage also other features as soon as I have some available time.

**Comment by roleoroleo** [comment]
Thank you!

**Comment by Enzokot** [comment]
> Yes, it is possible, but I have to think how exactly manage this in HA. In last version I started adding a switch to control ecoFriendly functionality, could you check if is working (if you refrigerator have this feature)? Thx

ecoFriendly work's for me, but in the latest version it's broken. see log's from HA
Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/smartthinq_sensors/wideq/core_v2.py:224
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 12:10:38 (1 occurrences)
Last logged: 12:10:38

[2771558112]
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 185, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1491, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1526, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 213, in handle_service
    await self.hass.helpers.service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 658, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 760, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 695, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 785, in async_turn_on
    await self.hass.async_add_executor_job(ft.partial(self.turn_on, **kwargs))
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/smartthinq_sensors/switch.py", line 244, in turn_on
    self._def[ATTR_TURN_ON_FN](self)
  File "/config/custom_components/smartthinq_sensors/switch.py", line 78, in <lambda>
    ATTR_TURN_ON_FN: lambda x: x._api.device.set_eco_friendly(True),
  File "/config/custom_components/smartthinq_sensors/wideq/refrigerator.py", line 144, in set_eco_friendly
    self.set(keys[0], keys[1], key=keys[2], value=status_value)
  File "/config/custom_components/smartthinq_sensors/wideq/device.py", line 978, in set
    self._set_control(full_key, None)
  File "/config/custom_components/smartthinq_sensors/wideq/device.py", line 948, in _set_control
    self._client.session.set_device_controls(
  File "/config/custom_components/smartthinq_sensors/wideq/core_v2.py", line 579, in set_device_controls
    res = self.post("rti/rtiControl", payload)
  File "/config/custom_components/smartthinq_sensors/wideq/core_v2.py", line 435, in post
    return lgedm2_post(
  File "/config/custom_components/smartthinq_sensors/wideq/core_v2.py", line 199, in lgedm2_post
    return manage_lge_result(out, is_api_v2)
  File "/config/custom_components/smartthinq_sensors/wideq/core_v2.py", line 224, in manage_lge_result
    raise API2_ERRORS[code]()
custom_components.smartthinq_sensors.wideq.core_exceptions.InvalidRequestError

**Comment by ollo69** [comment]
Are you able identify last integration version that `ecoFriendly` control was working?
Could you provide JSON info for your refrigerator?
I think that you have a THINQ1 version and this is the first feed-back I'm receiving, this is important to understand how the call must be implemented for this specific version of devices.

**Comment by Enzokot** [comment]
> Are you able identify last integration version that `ecoFriendly` control was working?
on 0.8.6 work for me, but on 0.8.9 doesn't
> Could you provide JSON info for your refrigerator?
Any mini guide to get this information from refrigerator?

**Comment by Enzokot** [comment]
> Are you able identify last integration version that `ecoFriendly` control was working?

on 0.8.6 work for me, but on 0.8.9 doesn't

> Could you provide JSON info for your refrigerator?

Any mini guide to get this information from refrigerator?

**Comment by Enzokot** [comment]
@ollo69 and may be possible to add "fast freeze" switch? I can test this feature with my refrigerator

**Comment by ollo69** [comment]
> Any mini guide to get this information from refrigerator?

During HA startup, you should find in the LOG file a line that say something like `Loading information for ....` and at the end is provided a `https` address to use to download the file.
Just take this address and copy it in your browser, download should start automatically.



> and may be possible to add "fast freeze" switch? I can test this feature with my refrigerator

One step at time. Problem with this features is that, as I see in the app, when `ecoFriendly` is enabled others option are disabled. So it is not so simple to manage all possible combination,

**Comment by Enzokot** [comment]
[JS0903055001572269.txt](https://github.com/ollo69/ha-smartthinq-sensors/files/6663600/JS0903055001572269.txt)


> Just take this address and copy it in your browser, download should start automatically.

Got it

**Comment by ollo69** [comment]
With last release I implemented temperature control and try to fix command for ThinQ1 devices. Please provide feedback about new feature and if now is possible to control ThinQ1 device. I have a ThinQ2 refrigerator so I cannot make any test on ThinQ1.

**Comment by Enzokot** [comment]
@ollo69 climate for set temp (ref and freeze, both) and switch for eco work for me. Thank you very much! Is it possible to add switch for fast freeze?

**Comment by Enzokot** [comment]
@ollo69 and now, all functions for my refrigerator available in the lg application, doesn't before 0.8.14. Thanks a lot!

**Comment by Enzokot** [comment]
@ollo69 switch 'express freeze' work for me. Thank you very much!

**Comment by roleoroleo** [comment]
I can confirm.
0.8.16 works correctly with my refrigerator.
Both set temp and express freeze fetaures.
Thank you for your support.

**Comment by Gulivert** [comment]
I'm currently having problems with my fridge to change temperature.

```
2021-07-13 11:07:51 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [2770890488] set_device_controls() got an unexpected keyword argument 'value'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 185, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1491, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1526, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 213, in handle_service
    await self.hass.helpers.service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 658, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 760, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 695, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 548, in async_service_temperature_set
    await entity.async_set_temperature(**kwargs)
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 408, in async_set_temperature
    await self.hass.async_add_executor_job(
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/smartthinq_sensors/climate.py", line 455, in set_temperature
    self._def[ATTR_TARGET_TEMP_FN](self, new_temp)
  File "/config/custom_components/smartthinq_sensors/climate.py", line 74, in 
    ATTR_TARGET_TEMP_FN: lambda x, y: x._api.device.set_freezer_target_temp(y),
  File "/config/custom_components/smartthinq_sensors/wideq/refrigerator.py", line 366, in set_freezer_target_temp
    self.set(keys[0], keys[1], key=keys[2], value=temp_key)
  File "/config/custom_components/smartthinq_sensors/wideq/device.py", line 978, in set
    self._set_control(full_key, None)
  File "/config/custom_components/smartthinq_sensors/wideq/device.py", line 948, in _set_control
    self._client.session.set_device_controls(
TypeError: set_device_controls() got an unexpected keyword argument 'value'
```

Do you know what can be?

**Comment by ollo69** [comment]
> I'm currently having problems with my fridge to change temperature.

Please check if last release fix the issue.

**Comment by Gulivert** [comment]
> > I'm currently having problems with my fridge to change temperature.
> 
> Please check if last release fix the issue.

Now it gives me this log whe i try to change tempertaure, or activete functions as Eco Friendly:

`2021-07-19 07:31:50 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [2876720248] set_device_controls() takes 3 positional arguments but 6 were given
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 185, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1491, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1526, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 213, in handle_service
    await self.hass.helpers.service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 658, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 760, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 695, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 548, in async_service_temperature_set
    await entity.async_set_temperature(**kwargs)
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 408, in async_set_temperature
    await self.hass.async_add_executor_job(
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/smartthinq_sensors/climate.py", line 467, in set_temperature
    self._def[ATTR_TARGET_TEMP_FN](self, new_temp)
  File "/config/custom_components/smartthinq_sensors/climate.py", line 75, in 
    ATTR_TARGET_TEMP_FN: lambda x, y: x._api.device.set_fridge_target_temp(y),
  File "/config/custom_components/smartthinq_sensors/wideq/refrigerator.py", line 350, in set_fridge_target_temp
    self.set(keys[0], keys[1], key=keys[2], value=temp_key)
  File "/config/custom_components/smartthinq_sensors/wideq/device.py", line 980, in set
    self._set_control(full_key)
  File "/config/custom_components/smartthinq_sensors/wideq/device.py", line 948, in _set_control
    self._client.session.set_device_controls(
TypeError: set_device_controls() takes 3 positional arguments but 6 were given
`

**Comment by ollo69** [comment]
I think your config is still using old `core` lib. You must reconfigure the integration to fix this issue.

**Comment by Gulivert** [comment]
Your where right. After reinstall it it works. Thanks.

**Comment by ollo69** [comment]
I close this Issue because the feature is implemented, please open dedicate Issue if requested.
