### ISSUE TITLE
Do you plan to add refrigerators?

### ISSUE THREAD

**Issue by petersoniq** [ollo69/ha-smartthinq-sensors#16]
Please think about it. Thank you.

**Comment by ollo69** [comment]
Yes, is in my plan...

**Comment by petersoniq** [comment]
ollo69 thank you. If you will needs to test it, I welcome.

**Comment by ollo69** [comment]
For sure I'll need, I don't have LG refrigerator :)

**Comment by sagitt** [comment]
i'm upgrading for refrigerator test.
i bought you another coffe for today for your works.

i have GMJ936NSHV

no refrigerator in my entities.

**Comment by ollo69** [comment]
Just a stupid log message that was checking a porperty not used by fridge, please try again with new version.

> NOTE: anyway now is LG ThinQ and not SmartThinQ. you renamed the project, for me the best name is "LG-ThinQ". no sensors, no washer, only lg thinq. :) only an advice for future of this wonderful integration. Thanks for your work and i hope this will be integrated officially in Home Assistant integrations.

Probably you are right, anyway from today the components is merged in HACS default, so I will not rename it for the moment, we will see in the future. For the moment was required to remove the word "Washer".

**Comment by sagitt** [comment]
> Just a stupid log message that was checking a porperty not used by fridge, please try again with new version.
> 
> > NOTE: anyway now is LG ThinQ and not SmartThinQ. you renamed the project, for me the best name is "LG-ThinQ". no sensors, no washer, only lg thinq. :) only an advice for future of this wonderful integration. Thanks for your work and i hope this will be integrated officially in Home Assistant integrations.
> 
> Probably you are right, anyway from today the **components is merged in HACS default**, so I will not rename it for the moment, we will see in the future. For the moment was important to remove the word "Washer".

of course, restarting hass now the fridge not work.

![Schermata 2020-04-19 alle 15 05 28](https://user-images.githubusercontent.com/169086/79688535-39162000-824f-11ea-8429-4dea68bf7882.png)
![Schermata 2020-04-19 alle 15 05 47](https://user-images.githubusercontent.com/169086/79688548-4501e200-824f-11ea-9d4f-3a479aae5e52.png)

**Comment by petersoniq** [comment]
I have sane issue. After restart HA, sensors without data.

**Comment by ollo69** [comment]
Need debug log to analizy and fix.
You should enable debug log adding this to your configuration.yaml:

```
logger:
  default: warning
  logs:
    custom_components.smartthinq_sensors: debug
```

Then let the HA run for 10 minutes and send me the `home-assistant.log` files to my e-mail `aolivero@gmail.com`.

If you want check before the log file for sensible information (mac-address, e-mail, etc) and remove it.

**Comment by sagitt** [comment]
> aolivero@gmail.com

check your inbox

**Comment by ollo69** [comment]
> check your inbox

Did you update to last version (v0.3.1)?
Because I still see the error `RefrigeratorStatus' object has no attribute 'run_state` that I fixed with last release.
Did you reboot HA after update?

**Comment by sagitt** [comment]
> > check your inbox
> 
> Did you update to last version (v0.3.1)?
> Because I still see the error `RefrigeratorStatus' object has no attribute 'run_state` that I fixed with last release.
> Did you reboot HA after update?

updated, same problem.

**Comment by ollo69** [comment]
Please send log after update, thanks

**Comment by sagitt** [comment]
> Please send log after update, thanks

done

**Comment by ollo69** [comment]
Now should be ok, please try version 0.3.2.
I still need to add some device attribute, I'll do it later or next days.

**Comment by karkaaa** [comment]
Hello,

I install 0.3.2 and get this:
```
Log Details (WARNING)
Logger: custom_components.smartthinq_sensors
Source: custom_components/smartthinq_sensors/__init__.py:354 
First occurred: 7:52:33 PM (2 occurrences) 
Last logged: 7:54:35 PM

Status update failed.
```

![image](https://user-images.githubusercontent.com/34538939/79694331-53b0bf00-8278-11ea-822c-e2d0cd7ccee1.png)

**Comment by ollo69** [comment]
I need from you more log, Please enable debug and send me your log as I explained [here](https://github.com/ollo69/ha-smartthinq-sensors/issues/16#issuecomment-616133690)

**Comment by karkaaa** [comment]
> I need from you more log, Please enable debug and send me your log as I explained [here](https://github.com/ollo69/ha-smartthinq-sensors/issues/16#issuecomment-616133690)

Done

**Comment by sagitt** [comment]
for me works fine. there is a way to know status of water and air filters? and maybe express freeze on\off status? is good in the main sensor without

**Comment by karkaaa** [comment]
i can check "Smart Diagnosis" from app and on/off express freeze (now off)

**Comment by ollo69** [comment]
> for me works fine. there is a way to know status of water and air filters? and maybe express freeze on\off status? is good in the main sensor without

Yes it is, but as I say before, later / next days....

**Comment by ollo69** [comment]
> > I need from you more log, Please enable debug and send me your log as I explained [here](https://github.com/ollo69/ha-smartthinq-sensors/issues/16#issuecomment-616133690)
> 
> Done

You have Fridge based on ApiV2, some more jobs for me...

**Comment by karkaaa** [comment]
> > > I need from you more log, Please enable debug and send me your log as I explained [here](https://github.com/ollo69/ha-smartthinq-sensors/issues/16#issuecomment-616133690)
> > 
> > 
> > Done
> 
> You have Fridge based on ApiV2, some more jobs for me...

sorry :/

**Comment by ollo69** [comment]
Don't worry, I was expecting....

**Comment by petersoniq** [comment]
After update to 0.3.2 works fine. Thanks.

**Comment by sagitt** [comment]
> > > I need from you more log, Please enable debug and send me your log as I explained [here](https://github.com/ollo69/ha-smartthinq-sensors/issues/16#issuecomment-616133690)
> > 
> > 
> > Done
> 
> You have Fridge based on ApiV2, some more jobs for me...

very strange. my fridge is really new and use olds api?

**Comment by karkaaa** [comment]
> Don't worry, I was expecting....
> It's fine because I'm also able to manage version with APIv2

Working APIv2 with 0.3.3.

Thank you.

**Comment by petersoniq** [comment]
HI ollo69.
In your mailbox you can see my mail, with latest log.
Again same error.

**Comment by ollo69** [comment]
> HI ollo69.
> In your mailbox you can see my mail, with latest log.
> Again same error.

Ops, find the issue, I will release fix by tonight...

**Comment by ollo69** [comment]
Just released a new version (v0.3.4) that should fix the issue.
Please try and let me know...

**Comment by petersoniq** [comment]
Again my log in mailbox.

**Comment by ollo69** [comment]
This are not **Errors**, but **"managed Warning"** issued by the system.
- the first is generated by HA core because you use Custom Component, 
- the second notify you that your refrigerator is providing a status that is not "mapped":
`received unknown REFRIGERATOR status 'NOT_USE' of type 'SmartSavingMode'`

**Can you confirm that integration is working now?**

You should run the integration for some time (eg. 1 day) and collect all this warning so that I can add these states to the list of possible cases.

Thx

**Comment by petersoniq** [comment]
> These are not **Errors**, but **"managed Warning"** issued by the system.
> 
> * the first is generated by HA core because you use Custom Component,
> * the second notify you that your refrigerator is providing a status that is not "mapped":
>   `received unknown REFRIGERATOR status 'NOT_USE' of type 'SmartSavingMode'`
> 
> **Can you confirm that integration is working now?**
> 
> You should run the integration for some time (eg. 1 day) and collect all this warning so that I can add these states to the list of possible cases.
> 
> Thx

Yes. Other works well. After 1-2 days I will send log again.

Thank you again for your job.

**Comment by ollo69** [comment]
> 
> Yes. Other works well. After 1-2 days I will send log again.
> 
> Thank you again for your job.

You can directly post these warnings here. 
There are not sensible info, are informations that is better to share, will help to extend support to additional models.  

Thx

**Comment by petersoniq** [comment]
Hi ollo69
log from 26h:
2020-04-21 10:16:12 WARNING (MainThread) [custom_components.smartthinq_sensors.wideq.device] ThinQ: received unknown REFRIGERATOR status 'NOT_USE' of type 'SmartSavingMode'
2020-04-21 10:42:07 WARNING (SyncWorker_4) [custom_components.smartthinq_sensors] Status update failed.
2020-04-21 10:49:51 WARNING (SyncWorker_2) [custom_components.smartthinq_sensors] Status update failed.
2020-04-21 10:51:55 WARNING (SyncWorker_2) [custom_components.smartthinq_sensors] Status update failed.
2020-04-21 12:05:47 WARNING (SyncWorker_0) [custom_components.smartthinq_sensors] Status update failed.
2020-04-21 12:14:34 WARNING (SyncWorker_13) [custom_components.smartthinq_sensors] Status update failed.
2020-04-21 13:34:37 WARNING (SyncWorker_6) [custom_components.smartthinq_sensors] Status update failed.
2020-04-21 16:04:25 WARNING (SyncWorker_9) [custom_components.smartthinq_sensors] Status update failed.
2020-04-21 16:25:05 WARNING (SyncWorker_16) [custom_components.smartthinq_sensors] Status update failed.
2020-04-22 08:35:36 WARNING (SyncWorker_5) [custom_components.smartthinq_sensors] Status update failed.
2020-04-22 08:44:54 WARNING (SyncWorker_9) [custom_components.smartthinq_sensors] Status update failed.
2020-04-22 08:53:10 WARNING (SyncWorker_16) [custom_components.smartthinq_sensors] Status update failed.
2020-04-22 11:12:38 WARNING (SyncWorker_0) [custom_components.smartthinq_sensors] Status update failed.
2020-04-22 11:35:53 WARNING (SyncWorker_5) [custom_components.smartthinq_sensors] Status update failed.
2020-04-22 11:37:57 WARNING (SyncWorker_1) [custom_components.smartthinq_sensors] Status update failed.
2020-04-22 11:44:40 WARNING (SyncWorker_15) [custom_components.smartthinq_sensors] Status update failed.
2020-04-22 12:00:09 WARNING (SyncWorker_6) [custom_components.smartthinq_sensors] Status update failed.
2020-04-22 12:14:05 WARNING (SyncWorker_13) [custom_components.smartthinq_sensors] Status update failed.
2020-04-22 12:19:46 WARNING (SyncWorker_14) [custom_components.smartthinq_sensors] Status update failed.
2020-04-22 12:21:50 WARNING (SyncWorker_18) [custom_components.smartthinq_sensors] Status update failed.
2020-04-22 12:35:15 WARNING (SyncWorker_0) [custom_components.smartthinq_sensors] Status update failed.
2020-04-22 12:38:21 WARNING (SyncWorker_0) [custom_components.smartthinq_sensors] Status update failed.

**Comment by ollo69** [comment]
I think that you are having internet issues...

**Comment by wgjhstt247** [comment]
I have an LG thinq refrigerator. Using your latest commit, I'm seeing this in the home assistant logs:
2020-04-24 00:02:23 ERROR (MainThread) [homeassistant.util.logging] Exception in async_state_update when dispatching 'thinq_remote_update-REFRIGERATOR': ()
Traceback (most recent call last):
  File "/config/custom_components/smartthinq_sensors/sensor.py", line 335, in async_state_update
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 297, in async_write_ha_state
    self._async_write_ha_state()  # type: ignore
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 320, in _async_write_ha_state
    state = self.state
  File "/config/custom_components/smartthinq_sensors/sensor.py", line 307, in state
    return self._def[ATTR_VALUE_FN](self)
  File "/config/custom_components/smartthinq_sensors/sensor.py", line 168, in <lambda>
    ATTR_VALUE_FN: lambda x: x._temp_refrigerator,
  File "/config/custom_components/smartthinq_sensors/sensor.py", line 717, in _temp_refrigerator
    return self._api.state.temp_refrigerator
  File "/config/custom_components/smartthinq_sensors/wideq/refrigerator.py", line 85, in temp_refrigerator
    temp = self.lookup_enum("TempRefrigerator")
  File "/config/custom_components/smartthinq_sensors/wideq/device.py", line 735, in lookup_enum
    return self._device.model_info.enum_name(curr_key, self._data[curr_key])
  File "/config/custom_components/smartthinq_sensors/wideq/device.py", line 314, in enum_name
    options = self.value(key).options
AttributeError: 'RangeValue' object has no attribute 'options'

**Comment by ollo69** [comment]
I added a check in last version to avoid exception, but I don't know if provided values will be correct.
To really solve this issue I need debud log from you as explained [here](https://github.com/ollo69/ha-smartthinq-sensors/issues/16#issuecomment-616133690)

**Comment by wgjhstt247** [comment]
@ollo69 Your latest code fixed the issues I was experiencing. Thank you! I'm now seeing this is the main log:
2020-04-28 00:49:15 WARNING (MainThread) [custom_components.smartthinq_sensors.wideq.device] ThinQ: received unknown REFRIGERATOR status '255' of type 'EcoFriendly'

**Comment by ollo69** [comment]
Closing this old thread.
Please open a new one if you still have Warning for "unknown states"
