### ISSUE TITLE
[BUG] Can't change swing modes anymore...

### ISSUE THREAD

**Issue by RedWheiler80** [ollo69/ha-smartthinq-sensors#167]
Some days ago it worked fine to set both vertical as horizontal swing modes, now it's broken...

Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/smartthinq_sensors/climate.py:253
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 11:25:37 (3 occurrences)
Last logged: 11:26:22

[547538504912] 'str' object has no attribute 'removeprefix'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 167, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1481, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1516, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 213, in handle_service
    await self.hass.helpers.service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 658, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 726, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 695, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 442, in async_set_swing_mode
    await self.hass.async_add_executor_job(self.set_swing_mode, swing_mode)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/smartthinq_sensors/climate.py", line 253, in set_swing_mode
    dev_mode = swing_mode.removeprefix(
AttributeError: 'str' object has no attribute 'removeprefix'

**Comment by RedWheiler80** [comment]
In addition: I did a rollback to 0.8.2 and it works again.

**Comment by ollo69** [comment]
Just understand now that string function `removeprefix` is available only from Python 3.9, my bad. Probably you are still using Python 3.8 right?. I will fix this later.

**Comment by Jeltel** [comment]
I can confirm this bug and the work-around for now.

Also, @ollo69 great work on incorporating apiV2 appliances into Home Assistant :) Thanks a lot.

**Comment by ollo69** [comment]
This should be fixes in v0.8.5.

**Comment by RedWheiler80** [comment]
Thank you, for me it works again.
