### ISSUE TITLE
Dishwasher testing

### ISSUE THREAD

**Issue by daveonkels** [ollo69/ha-smartthinq-sensors#18]
@ollo69 - No pressure but when you're ready, I have a 2019 model dishwasher to test.

**Comment by ollo69** [comment]
On coming week end....

**Comment by wgjhstt247** [comment]
@ollo69 I also have a newer dishwasher that we can test with.

**Comment by jaganath-b** [comment]
@ollo69 ..i too can join the dishwasher test...

**Comment by ollo69** [comment]
With release 0.4.0 DishWasher is available.
Device based on APIv1 may work, device based on APIv2 very probably will not work because I need some debug info to complete.

To provide me right information you must enable debug log adding this to your configuration.yaml:

```
logger:
  default: warning
  logs:
    custom_components.smartthinq_sensors: debug
```

Then let the HA run for 5-10 minutes and send me the `home-assistant.log` files to my e-mail `aolivero@gmail.com`.

If you want check before the log file for sensible information (mac-address, e-mail, etc) and remove it.

If the new version not work at all, send me the log and then roll-back to last 0.3.x waiting for update.

Thanks.

**Comment by ollo69** [comment]
I would really like to talk with the person that define standard in LG!!!
On dishwasher with APIv2 the format for the info is completely different from the others, some job to do here....

**Comment by jaganath-b** [comment]
Ok @ollo69 .. I have shared the logs as requested..thanks for your assistance again

**Comment by LongDono** [comment]
Noticed this today after a restart... hasn't occurred since.
```
2020-05-07 11:39:48 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.lg_dishwasher is taking over 10 seconds
2020-05-07 11:39:48 ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor.lg_dishwasher fails
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 426, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 421, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/lib/python3.7/http/client.py", line 1344, in getresponse
    response.begin()
  File "/usr/local/lib/python3.7/http/client.py", line 306, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python3.7/http/client.py", line 267, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/local/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
  File "/usr/local/lib/python3.7/site-packages/urllib3/contrib/pyopenssl.py", line 326, in recv_into
    raise timeout("The read operation timed out")
socket.timeout: The read operation timed out
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 725, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/usr/local/lib/python3.7/site-packages/urllib3/util/retry.py", line 403, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python3.7/site-packages/urllib3/packages/six.py", line 735, in reraise
    raise value
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 677, in urlopen
    chunked=chunked,
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 428, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 336, in _raise_timeout
    self, url, "Read timed out. (read timeout=%s)" % timeout_value
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='aic.lgthinq.com', port=46030): Read timed out. (read timeout=10)
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 279, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 472, in async_device_update
    await self.hass.async_add_executor_job(self.update)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/smartthinq_sensors/sensor.py", line 377, in update
    self._api.device_update()
  File "/usr/src/homeassistant/homeassistant/util/__init__.py", line 240, in wrapper
    result = method(*args, **kwargs)
  File "/config/custom_components/smartthinq_sensors/__init__.py", line 322, in device_update
    self._restart_monitor()
  File "/config/custom_components/smartthinq_sensors/__init__.py", line 306, in _restart_monitor
    raise ex
  File "/config/custom_components/smartthinq_sensors/__init__.py", line 293, in _restart_monitor
    self._device.monitor_start()
  File "/config/custom_components/smartthinq_sensors/wideq/device.py", line 715, in monitor_start
    mon.start()
  File "/config/custom_components/smartthinq_sensors/wideq/device.py", line 107, in start
    self.work_id = self.session.monitor_start(self.device_id)
  File "/config/custom_components/smartthinq_sensors/wideq/core_v2.py", line 437, in monitor_start
    "workId": gen_uuid(),
  File "/config/custom_components/smartthinq_sensors/wideq/core_v2.py", line 389, in post
    language=self.auth.gateway.language,
  File "/config/custom_components/smartthinq_sensors/wideq/core_v2.py", line 177, in lgedm2_post
    timeout=DEFAULT_TIMEOUT,
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 578, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/adapters.py", line 529, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='aic.lgthinq.com', port=46030): Read timed out. (read timeout=10)
2020-05-07 11:40:48 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.lg_dishwasher is taking over 10 seconds
2020-05-07 11:40:48 ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor.lg_dishwasher fails
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/urllib3/contrib/pyopenssl.py", line 488, in wrap_socket
    cnx.do_handshake()
  File "/usr/local/lib/python3.7/site-packages/OpenSSL/SSL.py", line 1934, in do_handshake
    self._raise_ssl_error(self._ssl, result)
  File "/usr/local/lib/python3.7/site-packages/OpenSSL/SSL.py", line 1646, in _raise_ssl_error
    raise WantReadError()
OpenSSL.SSL.WantReadError
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 381, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 976, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.7/site-packages/urllib3/connection.py", line 370, in connect
    ssl_context=context,
  File "/usr/local/lib/python3.7/site-packages/urllib3/util/ssl_.py", line 377, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/local/lib/python3.7/site-packages/urllib3/contrib/pyopenssl.py", line 491, in wrap_socket
    raise timeout("select timed out")
socket.timeout: select timed out
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 725, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/usr/local/lib/python3.7/site-packages/urllib3/util/retry.py", line 403, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python3.7/site-packages/urllib3/packages/six.py", line 735, in reraise
    raise value
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 677, in urlopen
    chunked=chunked,
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=conn.timeout)
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 336, in _raise_timeout
    self, url, "Read timed out. (read timeout=%s)" % timeout_value
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='aic.lgthinq.com', port=46030): Read timed out. (read timeout=10)
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 279, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 472, in async_device_update
    await self.hass.async_add_executor_job(self.update)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/smartthinq_sensors/sensor.py", line 377, in update
    self._api.device_update()
  File "/usr/src/homeassistant/homeassistant/util/__init__.py", line 240, in wrapper
    result = method(*args, **kwargs)
  File "/config/custom_components/smartthinq_sensors/__init__.py", line 322, in device_update
    self._restart_monitor()
  File "/config/custom_components/smartthinq_sensors/__init__.py", line 306, in _restart_monitor
    raise ex
  File "/config/custom_components/smartthinq_sensors/__init__.py", line 293, in _restart_monitor
    self._device.monitor_start()
  File "/config/custom_components/smartthinq_sensors/wideq/device.py", line 715, in monitor_start
    mon.start()
  File "/config/custom_components/smartthinq_sensors/wideq/device.py", line 107, in start
    self.work_id = self.session.monitor_start(self.device_id)
  File "/config/custom_components/smartthinq_sensors/wideq/core_v2.py", line 437, in monitor_start
    "workId": gen_uuid(),
  File "/config/custom_components/smartthinq_sensors/wideq/core_v2.py", line 389, in post
    language=self.auth.gateway.language,
  File "/config/custom_components/smartthinq_sensors/wideq/core_v2.py", line 177, in lgedm2_post
    timeout=DEFAULT_TIMEOUT,
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 578, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/adapters.py", line 529, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='aic.lgthinq.com', port=46030): Read timed out. (read timeout=10)
```

**Comment by ollo69** [comment]
This are timeout due to network issue.
I will put a easier error message on next release...
