### ISSUE TITLE
Error setting temperature on LG Refrigerator

### ISSUE THREAD

**Issue by ejpenney** [ollo69/ha-smartthinq-sensors#192]
![Screenshot_20210808-193732](https://user-images.githubusercontent.com/21226768/128655257-847417fb-f6f4-4074-a97b-836df7bfe61f.png)

Log:

`Log Details (ERROR)
Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/smartthinq_sensors/wideq/core_v2.py:215
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 7:37:16 PM (2 occurrences)
Last logged: 7:37:30 PM

[2949383744] ('9006', {'data': ''})
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 185, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1491, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1526, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 213, in handle_service
    await self.hass.helpers.service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 658, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 856, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 695, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 588, in async_service_temperature_set
    await entity.async_set_temperature(**kwargs)
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 444, in async_set_temperature
    await self.hass.async_add_executor_job(
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/smartthinq_sensors/climate.py", line 481, in set_temperature
    self._def[ATTR_TARGET_TEMP_FN](self, new_temp)
  File "/config/custom_components/smartthinq_sensors/climate.py", line 80, in <lambda>
    ATTR_TARGET_TEMP_FN: lambda x, y: x._api.device.set_fridge_target_temp(y),
  File "/config/custom_components/smartthinq_sensors/wideq/refrigerator.py", line 350, in set_fridge_target_temp
    self.set(keys[0], keys[1], key=keys[2], value=temp_key)
  File "/config/custom_components/smartthinq_sensors/wideq/device.py", line 987, in set
    self._set_control(ctrl_key, command, key=key, value=value, data=data)
  File "/config/custom_components/smartthinq_sensors/wideq/device.py", line 958, in _set_control
    self._client.session.set_device_v2_controls(
  File "/config/custom_components/smartthinq_sensors/wideq/core_v2.py", line 604, in set_device_v2_controls
    res = self.post2(path, payload)
  File "/config/custom_components/smartthinq_sensors/wideq/core_v2.py", line 455, in post2
    return lgedm2_post(
  File "/config/custom_components/smartthinq_sensors/wideq/core_v2.py", line 202, in lgedm2_post
    return manage_lge_result(out, is_api_v2)
  File "/config/custom_components/smartthinq_sensors/wideq/core_v2.py", line 215, in manage_lge_result
    raise exc.APIError(code, message)
custom_components.smartthinq_sensors.wideq.core_exceptions.APIError: ('9006', {'data': ''})
`

**Comment by pghattas** [comment]
Same error for calling switch service for ice plus entity.  When changed from app, HA integration properly reports the correct state but unable to change the state via HA.

**Comment by ollo69** [comment]
Can you download and share JSON device information. You can find the `url` to download it in HA log provided as `info` during startup.

**Comment by ejpenney** [comment]
Assuming you meant the line that begins: `Loading model info for Refrigerator. Model: 2REF12EICD__2,`

Downloaded here: [LGRef.txt](https://github.com/ollo69/ha-smartthinq-sensors/files/7198777/LGRef.txt)

**Comment by ollo69** [comment]
Please can you try if last release (v0.9.3) fix this issue.

**Comment by ejpenney** [comment]
Yup, this is working for me now!  Thanks!

**Comment by ollo69** [comment]
Can we close this issue?

**Comment by pghattas** [comment]
I'm good now. Thank you!

**Comment by ollo69** [comment]
Ok, I close the issue, open a new one if some other issue persists.
