### ISSUE TITLE
ThinQ error while updating device status

### ISSUE THREAD

**Issue by nckslater** [ollo69/ha-smartthinq-sensors#193]
Just updated my hassio os to Home Assistant 2021.8.4 and after restart got the following errors: 

`Logger: custom_components.smartthinq_sensors
Source: custom_components/smartthinq_sensors/wideq/core_v2.py:273
Integration: SmartThinQ LGE Sensors (documentation, issues)
First occurred: 1:36:52 (1 occurrences)
Last logged: 1:36:52

ThinQ error while updating device status
Traceback (most recent call last):
  File "/config/custom_components/smartthinq_sensors/__init__.py", line 414, in _restart_monitor
    if not self._refresh_client(refresh_gateway):
  File "/config/custom_components/smartthinq_sensors/__init__.py", line 397, in _refresh_client
    self._device.client.refresh(refresh_gateway)
  File "/config/custom_components/smartthinq_sensors/wideq/core_v2.py", line 816, in refresh
    self._auth = self.auth.refresh()
  File "/config/custom_components/smartthinq_sensors/wideq/core_v2.py", line 387, in refresh
    new_access_token = refresh_auth(self.oauth_url, self.refresh_token)
  File "/config/custom_components/smartthinq_sensors/wideq/core_v2.py", line 308, in refresh_auth
    out = auth_request(
  File "/config/custom_components/smartthinq_sensors/wideq/core_v2.py", line 273, in auth_request
    raise exc.TokenError()
custom_components.smartthinq_sensors.wideq.core_exceptions.TokenError`

`Logger: custom_components.smartthinq_sensors
Source: custom_components/smartthinq_sensors/__init__.py:479
Integration: SmartThinQ LGE Sensors (documentation, issues)
First occurred: 1:36:52 (1 occurrences)
Last logged: 1:36:52

Status for device LG WFFN was reset because not connected`

Everything was working fine until today

**Comment by nckslater** [comment]
I restored a snapshot then restarted a couple of times and it sees to work again

**Comment by ollo69** [comment]
Close this issue because seems solved.
