### ISSUE TITLE
Temp and spin error and showing wrong model

### ISSUE THREAD

**Issue by Golab** [ollo69/ha-smartthinq-sensors#20]
I’m on version V0.3.4
I have 2 problems

In my log I get this error

Log Details (WARNING)
Logger: custom_components.smartthinq_sensors.wideq.device
Source: custom_components/smartthinq_sensors/wideq/device.py:726
First occurred: 10:57:11 PM (2 occurrences) 
Last logged: 10:57:11 PM

ThinQ: received unknown WASHER status '@WM_FL24_TITAN_SPIN_SPEED_1000_W' of type 'spin_option'
ThinQ: received unknown WASHER status '@WM_FL24_TITAN_TEMP_60_W' of type 'water_temp'

And in washing machine/dryer it doesn’t show the Temp and also it doesn’t show spinning, I have made a screenshot showing info

And also in one of the pictures showing status it seems it is identifying wrong model of my machine

I have a picture of the tag on my machine showing correct model

![image](https://user-images.githubusercontent.com/1252745/80034332-8a900a80-84ee-11ea-8996-54c577fc1633.png)
![image](https://user-images.githubusercontent.com/1252745/80034345-911e8200-84ee-11ea-8ff9-afd654a012a1.png)
![image](https://user-images.githubusercontent.com/1252745/80034742-2de11f80-84ef-11ea-97c1-30b3d8e2813f.jpeg)
![image](https://user-images.githubusercontent.com/1252745/80034938-76004200-84ef-11ea-9fd8-6285276ebe6f.jpeg)
![image](https://user-images.githubusercontent.com/1252745/80034958-7c8eb980-84ef-11ea-9d06-8c878ed18911.jpeg)

**Comment by Golab** [comment]
![Uploading 80034665...]()

**Comment by ollo69** [comment]
Model is what is provided from the API, also for me is not the same as the label.

For the states I added new states on last release based on your warnings, please let me know if now are correctly filled.

**Comment by Golab** [comment]
It works better now but now I get this error


Log Details (WARNING)
Logger: custom_components.smartthinq_sensors.wideq.device
Source: custom_components/smartthinq_sensors/wideq/device.py:729
Integration: SmartThinQ LGE Sensors (documentation) 
First occurred: 11:02:36 AM (1 occurrences) 
Last logged: 11:02:36 AM

ThinQ: received unknown WASHER status '@WM_FL24_TITAN_SPIN_SPEED_1400_W' of type 'spin_option'

``![image](https://user-images.githubusercontent.com/1252745/80303175-c48f3400-87ae-11ea-9526-9e7bdb8bbbee.jpeg)``

**Comment by ollo69** [comment]
Added states in last version

**Comment by Golab** [comment]
Now I’m getting more errors

I’m running v0.3.8

Error Nr1


Log Details (ERROR)
Logger: homeassistant.helpers.entity
Source: custom_components/smartthinq_sensors/wideq/core_v2.py:177
First occurred: 7:29:06 PM (3 occurrences) 
Last logged: 7:30:49 PM

Update for sensor.tvattmaskin fails
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/urllib3/contrib/pyopenssl.py", line 488, in wrap_socket
    cnx.do_handshake()
  File "/usr/local/lib/python3.7/site-packages/OpenSSL/SSL.py", line 1934, in do_handshake
    self._raise_ssl_error(self._ssl, result)
  File "/usr/local/lib/python3.7/site-packages/OpenSSL/SSL.py", line 1646, in _raise_ssl_error
    raise WantReadError()
OpenSSL.SSL.WantReadError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 381, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 976, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.7/site-packages/urllib3/connection.py", line 370, in connect
    ssl_context=context,
  File "/usr/local/lib/python3.7/site-packages/urllib3/util/ssl_.py", line 377, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/local/lib/python3.7/site-packages/urllib3/contrib/pyopenssl.py", line 491, in wrap_socket
    raise timeout("select timed out")
socket.timeout: select timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 725, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/usr/local/lib/python3.7/site-packages/urllib3/util/retry.py", line 403, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python3.7/site-packages/urllib3/packages/six.py", line 735, in reraise
    raise value
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 677, in urlopen
    chunked=chunked,
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=conn.timeout)
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 336, in _raise_timeout
    self, url, "Read timed out. (read timeout=%s)" % timeout_value
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='eic.lgthinq.com', port=46030): Read timed out. (read timeout=10)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 279, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 472, in async_device_update
    await self.hass.async_add_executor_job(self.update)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/smartthinq_sensors/sensor.py", line 326, in update
    self._api.device_update()
  File "/usr/src/homeassistant/homeassistant/util/__init__.py", line 240, in wrapper
    result = method(*args, **kwargs)
  File "/config/custom_components/smartthinq_sensors/__init__.py", line 333, in device_update
    raise ex
  File "/config/custom_components/smartthinq_sensors/__init__.py", line 321, in device_update
    state = self._device.poll()
  File "/config/custom_components/smartthinq_sensors/wideq/washer.py", line 35, in poll
    res = self.device_poll("washerDryer")
  File "/config/custom_components/smartthinq_sensors/wideq/device.py", line 673, in device_poll
    data = self.mon.poll()
  File "/config/custom_components/smartthinq_sensors/wideq/device.py", line 115, in poll
    self.work_id = self.session.monitor_start(self.device_id)
  File "/config/custom_components/smartthinq_sensors/wideq/core_v2.py", line 437, in monitor_start
    "workId": gen_uuid(),
  File "/config/custom_components/smartthinq_sensors/wideq/core_v2.py", line 389, in post
    language=self.auth.gateway.language,
  File "/config/custom_components/smartthinq_sensors/wideq/core_v2.py", line 177, in lgedm2_post
    timeout=DEFAULT_TIMEOUT,
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 578, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/adapters.py", line 529, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='eic.lgthinq.com', port=46030): Read timed out. (read timeout=10)





Error Nr2

![image](https://user-images.githubusercontent.com/1252745/80403835-8bdf7f80-88c0-11ea-9548-2f8e6d63b12e.jpeg)




Error Nr3

![image](https://user-images.githubusercontent.com/1252745/80403858-9863d800-88c0-11ea-8b06-3d0d42de4a94.jpeg)


Error Nr4

![image](https://user-images.githubusercontent.com/1252745/80403895-aa457b00-88c0-11ea-99b2-984a91856843.jpeg)

**Comment by ollo69** [comment]
New states  are because I added DryLevel attribute for washer/dryer combo device. I will add status for your model with new release.
About timeout, I cannot help, network issues

**Comment by navigatortc** [comment]
In my log I get a WARNING:
![warning](https://user-images.githubusercontent.com/63975753/80417080-dae7dd80-88dd-11ea-94dd-62403b471e27.jpg)
The temperature during washing is not displayed.

Installed: v0.3.8

**Comment by Golab** [comment]
What does '@WM_FL24_TITAN_DRY_120_W' of type 'DryLevel'   men?

Is 120_W power it’s using?

**Comment by ollo69** [comment]
Think time. see #24

**Comment by Golab** [comment]
After the latest release I get this error![image](https://user-images.githubusercontent.com/1252745/80749072-37d5d480-8b26-11ea-8b49-fcc1bc17f1fc.jpeg)

**Comment by ollo69** [comment]
Warning != Error.

With new version, in the HA log file you should have an information log like this:

```
2020-04-30 01:46:54 INFO (SyncWorker_0) [custom_components.smartthinq_sensors.wideq.core_v2] Loading model info for LAVATRICE. Model: WTWN3, Url: <the url>
```

Can you please post the url indicated in your log so that I can download json file related to your model and map all possible state?

Thx

**Comment by Golab** [comment]
Like this?


2020-04-30 18:30:30 INFO (SyncWorker_8) [custom_components.smartthinq_sensors.wideq.core_v2] Loading model info for TVÄTTMASKIN. Model: WTHTGH, Url: https://eic.lgthinq.com:46030/api/webContents/modelJSON?modelName=WTHTGH&countryCode=WW&contentsId=JS0521042724689449&authKey=thinq

**Comment by chewyikai** [comment]
Hi, im getting this warning on my washer 

ThinQ: received unknown WASHER status '@WM_TL_MP_OPTION_SPIN_MEDIUM_W' of type 'SpinSpeed'

**Comment by ollo69** [comment]
Please provide me [this](https://github.com/ollo69/ha-smartthinq-sensors/issues/20#issuecomment-622057350) to fix unknown states for your device.

**Comment by e9henrik** [comment]
Thanks Ollo, great component!

New model:
`2020-05-15 15:54:07 INFO (SyncWorker_2) [custom_components.smartthinq_sensors.wideq.core_v2] Loading model info for TVÄTTMASKIN. Model: WPHT, Url:` [WPHT](https://eic.lgthinq.com:46030/api/webContents/modelJSON?modelName=WPHT&countryCode=WW&contentsId=JS0911021801883542&authKey=thinq) 

Thanks!

**Comment by ollo69** [comment]
> Thanks Ollo, great component!
> 
> New model:
> `2020-05-15 15:54:07 INFO (SyncWorker_2) [custom_components.smartthinq_sensors.wideq.core_v2] Loading model info for TVÄTTMASKIN. Model: WPHT, Url:` [WPHT](https://eic.lgthinq.com:46030/api/webContents/modelJSON?modelName=WPHT&countryCode=WW&contentsId=JS0911021801883542&authKey=thinq)
> 
> Thanks!

This infos are added in last release.

I close this old thread.
Please open a new one if you still have Warning for "unknown states"
