### ISSUE TITLE
[BUG] Refrigerator express cool mode show errors, but is enabled

### ISSUE THREAD

**Issue by OldShaterhan** [ollo69/ha-smartthinq-sensors#200]
**Describe the bug**
When enabling refrigerator using switch option:
![image](https://user-images.githubusercontent.com/1622866/131194531-f64d2be4-efc0-4c06-a162-409a31e4c351.png)

I got following error:
![image](https://user-images.githubusercontent.com/1622866/131194494-d56fd00d-7f02-4f6a-b0b4-7fd8f4293fa4.png)

However status is changed. Switch button also doesn't describe anything and seems to be located a bit too high - it looks like I can enable kitchen room and there's no description what this switch does.

**Expected behavior**
If applicable, a clear and concise description of what you expected to happen.

**Screenshots**

**Environment details:**
 - Environment: HASSIO
 - Home Assistant version installed: 2021.8.8
 - Component version installed: 0.8.20
 - Last know working version: -
 - LG device type and model with issue: LG 2REB1GLVB1___-BF (REFRIGERATOR) (from data from HA)
 - LG devices connected (list): only LG refrigerator

**Output of HA logs**
Paste the relavant output of the HA log here.

```
Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/smartthinq_sensors/wideq/core_v2.py:215
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 0:18:32 (5 occurrences)
Last logged: 0:25:34

[548216217024] ('0103', {'data': None})
[547922063568] ('0103', {'data': None})
[548181061744] ('0103', {'data': None})
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 185, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1491, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1526, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/components/homeassistant/__init__.py", line 115, in async_handle_turn_service
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/core.py", line 1491, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1526, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 213, in handle_service
    await self.hass.helpers.service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 658, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 856, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 695, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 891, in async_turn_on
    await self.hass.async_add_executor_job(ft.partial(self.turn_on, **kwargs))
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/smartthinq_sensors/switch.py", line 271, in turn_on
    self._def[ATTR_TURN_ON_FN](self)
  File "/config/custom_components/smartthinq_sensors/switch.py", line 83, in <lambda>
    ATTR_TURN_ON_FN: lambda x: x._api.device.set_express_fridge(True),
  File "/config/custom_components/smartthinq_sensors/wideq/refrigerator.py", line 327, in set_express_fridge
    self._set_feature(turn_on, REFR_STATE_EXPRESS_FRIDGE, CMD_STATE_EXPRESS_FRIDGE)
  File "/config/custom_components/smartthinq_sensors/wideq/refrigerator.py", line 306, in _set_feature
    self.set(keys[0], keys[1], key=keys[2], value=status_value)
  File "/config/custom_components/smartthinq_sensors/wideq/device.py", line 980, in set
    self._set_control(full_key)
  File "/config/custom_components/smartthinq_sensors/wideq/device.py", line 958, in _set_control
    self._client.session.set_device_v2_controls(
  File "/config/custom_components/smartthinq_sensors/wideq/core_v2.py", line 604, in set_device_v2_controls
    res = self.post2(path, payload)
  File "/config/custom_components/smartthinq_sensors/wideq/core_v2.py", line 455, in post2
    return lgedm2_post(
  File "/config/custom_components/smartthinq_sensors/wideq/core_v2.py", line 202, in lgedm2_post
    return manage_lge_result(out, is_api_v2)
  File "/config/custom_components/smartthinq_sensors/wideq/core_v2.py", line 215, in manage_lge_result
    raise exc.APIError(code, message)
custom_components.smartthinq_sensors.wideq.core_exceptions.APIError: ('0103', {'data': None})
```

```
Logger: homeassistant
Source: custom_components/smartthinq_sensors/wideq/core_v2.py:215
Integration: SmartThinQ LGE Sensors (documentation, issues)
First occurred: 0:18:38 (4 occurrences)
Last logged: 0:23:59

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 856, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 695, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 891, in async_turn_on
    await self.hass.async_add_executor_job(ft.partial(self.turn_on, **kwargs))
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/smartthinq_sensors/switch.py", line 271, in turn_on
    self._def[ATTR_TURN_ON_FN](self)
  File "/config/custom_components/smartthinq_sensors/switch.py", line 75, in <lambda>
    ATTR_TURN_ON_FN: lambda x: x._api.device.set_eco_friendly(True),
  File "/config/custom_components/smartthinq_sensors/wideq/refrigerator.py", line 311, in set_eco_friendly
    self._set_feature(turn_on, REFR_STATE_ECO_FRIENDLY, CMD_STATE_ECO_FRIENDLY)
  File "/config/custom_components/smartthinq_sensors/wideq/refrigerator.py", line 306, in _set_feature
    self.set(keys[0], keys[1], key=keys[2], value=status_value)
  File "/config/custom_components/smartthinq_sensors/wideq/device.py", line 980, in set
    self._set_control(full_key)
  File "/config/custom_components/smartthinq_sensors/wideq/device.py", line 958, in _set_control
    self._client.session.set_device_v2_controls(
  File "/config/custom_components/smartthinq_sensors/wideq/core_v2.py", line 604, in set_device_v2_controls
    res = self.post2(path, payload)
  File "/config/custom_components/smartthinq_sensors/wideq/core_v2.py", line 455, in post2
    return lgedm2_post(
  File "/config/custom_components/smartthinq_sensors/wideq/core_v2.py", line 202, in lgedm2_post
    return manage_lge_result(out, is_api_v2)
  File "/config/custom_components/smartthinq_sensors/wideq/core_v2.py", line 215, in manage_lge_result
    raise exc.APIError(code, message)
custom_components.smartthinq_sensors.wideq.core_exceptions.APIError: ('0103', {'data': None})
```

**Additional context**
I think I have no more valuable data.

**Comment by ollo69** [comment]
Can you download and share JSON device information. You can find the `url` to download it in HA log provided as `info` during startup.

**Comment by OldShaterhan** [comment]
@ollo69 I don't see any within logs (/config/home-assistant.log neither on Configuration -> Logs) - do I need to find or set something to see it by default?

Please find updated logs in the meantime:

`
2021-09-21 02:24:17 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [547428939040] ('0103', {'data': None})
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 185, in handle_call_service
await hass.services.async_call(
File "/usr/src/homeassistant/homeassistant/core.py", line 1492, in async_call
task.result()
File "/usr/src/homeassistant/homeassistant/core.py", line 1527, in _execute_service
await handler.job.target(service_call)
File "/usr/src/homeassistant/homeassistant/components/homeassistant/__init__.py", line 121, in async_handle_turn_service
await asyncio.gather(*tasks)
File "/usr/src/homeassistant/homeassistant/core.py", line 1492, in async_call
task.result()
File "/usr/src/homeassistant/homeassistant/core.py", line 1527, in _execute_service
await handler.job.target(service_call)
File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 213, in handle_service
await self.hass.helpers.service.entity_service_call(
File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 658, in entity_service_call
future.result() # pop exception if have
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 843, in async_request_call
await coro
File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 695, in _handle_entity_call
await result
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 895, in async_turn_on
await self.hass.async_add_executor_job(ft.partial(self.turn_on, **kwargs))
File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
result = self.fn(*self.args, **self.kwargs)
File "/config/custom_components/smartthinq_sensors/switch.py", line 214, in turn_on
self.entity_description.turn_on_fn(self._wrap_device)
File "/config/custom_components/smartthinq_sensors/switch.py", line 70, in <lambda>
turn_on_fn=lambda x: x.device.set_express_fridge(True),
File "/config/custom_components/smartthinq_sensors/wideq/refrigerator.py", line 327, in set_express_fridge
self._set_feature(turn_on, REFR_STATE_EXPRESS_FRIDGE, CMD_STATE_EXPRESS_FRIDGE)
File "/config/custom_components/smartthinq_sensors/wideq/refrigerator.py", line 306, in _set_feature
self.set(keys[0], keys[1], key=keys[2], value=status_value)
File "/config/custom_components/smartthinq_sensors/wideq/device.py", line 981, in set
self._set_control(full_key)
File "/config/custom_components/smartthinq_sensors/wideq/device.py", line 959, in _set_control
self._client.session.set_device_v2_controls(
File "/config/custom_components/smartthinq_sensors/wideq/core_v2.py", line 604, in set_device_v2_controls
res = self.post2(path, payload)
File "/config/custom_components/smartthinq_sensors/wideq/core_v2.py", line 455, in post2
return lgedm2_post(
File "/config/custom_components/smartthinq_sensors/wideq/core_v2.py", line 202, in lgedm2_post
return manage_lge_result(out, is_api_v2)
File "/config/custom_components/smartthinq_sensors/wideq/core_v2.py", line 215, in manage_lge_result
raise exc.APIError(code, message)
custom_components.smartthinq_sensors.wideq.core_exceptions.APIError: ('0103', {'data': None})
2021-09-21 02:24:30 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [547228625744]
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 185, in handle_call_service
await hass.services.async_call(
File "/usr/src/homeassistant/homeassistant/core.py", line 1492, in async_call
task.result()
File "/usr/src/homeassistant/homeassistant/core.py", line 1527, in _execute_service
await handler.job.target(service_call)
File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 213, in handle_service
await self.hass.helpers.service.entity_service_call(
File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 658, in entity_service_call
future.result() # pop exception if have
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 843, in async_request_call
await coro
File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 695, in _handle_entity_call
await result
File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 470, in async_set_hvac_mode
await self.hass.async_add_executor_job(self.set_hvac_mode, hvac_mode)
File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
result = self.fn(*self.args, **self.kwargs)
File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 466, in set_hvac_mode
raise NotImplementedError()
NotImplementedError
2021-09-21 02:24:40 ERROR (SyncWorker_5) [spotipy.client] Max Retries reached
2021-09-21 02:24:44 ERROR (DHCPWatcher) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 843, in async_request_call
await coro
File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 695, in _handle_entity_call
await result
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 895, in async_turn_on
await self.hass.async_add_executor_job(ft.partial(self.turn_on, **kwargs))
File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
result = self.fn(*self.args, **self.kwargs)
File "/config/custom_components/smartthinq_sensors/switch.py", line 214, in turn_on
self.entity_description.turn_on_fn(self._wrap_device)
File "/config/custom_components/smartthinq_sensors/switch.py", line 63, in <lambda>
turn_on_fn=lambda x: x.device.set_eco_friendly(True),
File "/config/custom_components/smartthinq_sensors/wideq/refrigerator.py", line 311, in set_eco_friendly
self._set_feature(turn_on, REFR_STATE_ECO_FRIENDLY, CMD_STATE_ECO_FRIENDLY)
File "/config/custom_components/smartthinq_sensors/wideq/refrigerator.py", line 306, in _set_feature
self.set(keys[0], keys[1], key=keys[2], value=status_value)
File "/config/custom_components/smartthinq_sensors/wideq/device.py", line 981, in set
self._set_control(full_key)
File "/config/custom_components/smartthinq_sensors/wideq/device.py", line 959, in _set_control
self._client.session.set_device_v2_controls(
File "/config/custom_components/smartthinq_sensors/wideq/core_v2.py", line 604, in set_device_v2_controls
res = self.post2(path, payload)
File "/config/custom_components/smartthinq_sensors/wideq/core_v2.py", line 455, in post2
return lgedm2_post(
File "/config/custom_components/smartthinq_sensors/wideq/core_v2.py", line 202, in lgedm2_post
return manage_lge_result(out, is_api_v2)
File "/config/custom_components/smartthinq_sensors/wideq/core_v2.py", line 215, in manage_lge_result
raise exc.APIError(code, message)
custom_components.smartthinq_sensors.wideq.core_exceptions.APIError: ('0103', {'data': None})
2021-09-21 02:24:44 ERROR (DHCPWatcher) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 843, in async_request_call
await coro
File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 695, in _handle_entity_call
await result
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 895, in async_turn_on
await self.hass.async_add_executor_job(ft.partial(self.turn_on, **kwargs))
File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
result = self.fn(*self.args, **self.kwargs)
File "/config/custom_components/smartthinq_sensors/switch.py", line 214, in turn_on
self.entity_description.turn_on_fn(self._wrap_device)
File "/config/custom_components/smartthinq_sensors/switch.py", line 78, in <lambda>
turn_on_fn=lambda x: x.device.set_express_mode(True),
File "/config/custom_components/smartthinq_sensors/wideq/refrigerator.py", line 335, in set_express_mode
self._set_feature(turn_on, REFR_STATE_EXPRESS_MODE, CMD_STATE_EXPRESS_MODE)
File "/config/custom_components/smartthinq_sensors/wideq/refrigerator.py", line 306, in _set_feature
self.set(keys[0], keys[1], key=keys[2], value=status_value)
File "/config/custom_components/smartthinq_sensors/wideq/device.py", line 981, in set
self._set_control(full_key)
File "/config/custom_components/smartthinq_sensors/wideq/device.py", line 959, in _set_control
self._client.session.set_device_v2_controls(
File "/config/custom_components/smartthinq_sensors/wideq/core_v2.py", line 604, in set_device_v2_controls
res = self.post2(path, payload)
File "/config/custom_components/smartthinq_sensors/wideq/core_v2.py", line 455, in post2
return lgedm2_post(
File "/config/custom_components/smartthinq_sensors/wideq/core_v2.py", line 202, in lgedm2_post
return manage_lge_result(out, is_api_v2)
File "/config/custom_components/smartthinq_sensors/wideq/core_v2.py", line 215, in manage_lge_result
raise exc.APIError(code, message)
custom_components.smartthinq_sensors.wideq.core_exceptions.APIError: ('0103', {'data': None})
2021-09-21 02:25:07 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [547228625744] ('0103', {'data': None})
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 185, in handle_call_service
await hass.services.async_call(
File "/usr/src/homeassistant/homeassistant/core.py", line 1492, in async_call
task.result()
File "/usr/src/homeassistant/homeassistant/core.py", line 1527, in _execute_service
await handler.job.target(service_call)
File "/usr/src/homeassistant/homeassistant/components/homeassistant/__init__.py", line 121, in async_handle_turn_service
await asyncio.gather(*tasks)
File "/usr/src/homeassistant/homeassistant/core.py", line 1492, in async_call
task.result()
File "/usr/src/homeassistant/homeassistant/core.py", line 1527, in _execute_service
await handler.job.target(service_call)
File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 213, in handle_service
await self.hass.helpers.service.entity_service_call(
File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 658, in entity_service_call
future.result() # pop exception if have
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 843, in async_request_call
await coro
File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 695, in _handle_entity_call
await result
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 895, in async_turn_on
await self.hass.async_add_executor_job(ft.partial(self.turn_on, **kwargs))
File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
result = self.fn(*self.args, **self.kwargs)
File "/config/custom_components/smartthinq_sensors/switch.py", line 214, in turn_on
self.entity_description.turn_on_fn(self._wrap_device)
File "/config/custom_components/smartthinq_sensors/switch.py", line 63, in <lambda>
turn_on_fn=lambda x: x.device.set_eco_friendly(True),
File "/config/custom_components/smartthinq_sensors/wideq/refrigerator.py", line 311, in set_eco_friendly
self._set_feature(turn_on, REFR_STATE_ECO_FRIENDLY, CMD_STATE_ECO_FRIENDLY)
File "/config/custom_components/smartthinq_sensors/wideq/refrigerator.py", line 306, in _set_feature
self.set(keys[0], keys[1], key=keys[2], value=status_value)
File "/config/custom_components/smartthinq_sensors/wideq/device.py", line 981, in set
self._set_control(full_key)
File "/config/custom_components/smartthinq_sensors/wideq/device.py", line 959, in _set_control
self._client.session.set_device_v2_controls(
File "/config/custom_components/smartthinq_sensors/wideq/core_v2.py", line 604, in set_device_v2_controls
res = self.post2(path, payload)
File "/config/custom_components/smartthinq_sensors/wideq/core_v2.py", line 455, in post2
return lgedm2_post(
File "/config/custom_components/smartthinq_sensors/wideq/core_v2.py", line 202, in lgedm2_post
return manage_lge_result(out, is_api_v2)
File "/config/custom_components/smartthinq_sensors/wideq/core_v2.py", line 215, in manage_lge_result
raise exc.APIError(code, message)
custom_components.smartthinq_sensors.wideq.core_exceptions.APIError: ('0103', {'data': None})
2021-09-21 02:25:12 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [547191306464] ('0103', {'data': None})
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 185, in handle_call_service
await hass.services.async_call(
File "/usr/src/homeassistant/homeassistant/core.py", line 1492, in async_call
task.result()
File "/usr/src/homeassistant/homeassistant/core.py", line 1527, in _execute_service
await handler.job.target(service_call)
File "/usr/src/homeassistant/homeassistant/components/homeassistant/__init__.py", line 121, in async_handle_turn_service
await asyncio.gather(*tasks)
File "/usr/src/homeassistant/homeassistant/core.py", line 1492, in async_call
task.result()
File "/usr/src/homeassistant/homeassistant/core.py", line 1527, in _execute_service
await handler.job.target(service_call)
File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 213, in handle_service
await self.hass.helpers.service.entity_service_call(
File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 658, in entity_service_call
future.result() # pop exception if have
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 843, in async_request_call
await coro
File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 695, in _handle_entity_call
await result
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 895, in async_turn_on
await self.hass.async_add_executor_job(ft.partial(self.turn_on, **kwargs))
File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
result = self.fn(*self.args, **self.kwargs)
File "/config/custom_components/smartthinq_sensors/switch.py", line 214, in turn_on
self.entity_description.turn_on_fn(self._wrap_device)
File "/config/custom_components/smartthinq_sensors/switch.py", line 63, in <lambda>
turn_on_fn=lambda x: x.device.set_eco_friendly(True),
File "/config/custom_components/smartthinq_sensors/wideq/refrigerator.py", line 311, in set_eco_friendly
self._set_feature(turn_on, REFR_STATE_ECO_FRIENDLY, CMD_STATE_ECO_FRIENDLY)
File "/config/custom_components/smartthinq_sensors/wideq/refrigerator.py", line 306, in _set_feature
self.set(keys[0], keys[1], key=keys[2], value=status_value)
File "/config/custom_components/smartthinq_sensors/wideq/device.py", line 981, in set
self._set_control(full_key)
File "/config/custom_components/smartthinq_sensors/wideq/device.py", line 959, in _set_control
self._client.session.set_device_v2_controls(
File "/config/custom_components/smartthinq_sensors/wideq/core_v2.py", line 604, in set_device_v2_controls
res = self.post2(path, payload)
File "/config/custom_components/smartthinq_sensors/wideq/core_v2.py", line 455, in post2
return lgedm2_post(
File "/config/custom_components/smartthinq_sensors/wideq/core_v2.py", line 202, in lgedm2_post
return manage_lge_result(out, is_api_v2)
File "/config/custom_components/smartthinq_sensors/wideq/core_v2.py", line 215, in manage_lge_result
raise exc.APIError(code, message)
custom_components.smartthinq_sensors.wideq.core_exceptions.APIError: ('0103', {'data': None})
2021-09-21 02:25:15 ERROR (DHCPWatcher) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 843, in async_request_call
await coro
File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 695, in _handle_entity_call
await result
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 895, in async_turn_on
await self.hass.async_add_executor_job(ft.partial(self.turn_on, **kwargs))
File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
result = self.fn(*self.args, **self.kwargs)
File "/config/custom_components/smartthinq_sensors/switch.py", line 214, in turn_on
self.entity_description.turn_on_fn(self._wrap_device)
File "/config/custom_components/smartthinq_sensors/switch.py", line 78, in <lambda>
turn_on_fn=lambda x: x.device.set_express_mode(True),
File "/config/custom_components/smartthinq_sensors/wideq/refrigerator.py", line 335, in set_express_mode
self._set_feature(turn_on, REFR_STATE_EXPRESS_MODE, CMD_STATE_EXPRESS_MODE)
File "/config/custom_components/smartthinq_sensors/wideq/refrigerator.py", line 306, in _set_feature
self.set(keys[0], keys[1], key=keys[2], value=status_value)
File "/config/custom_components/smartthinq_sensors/wideq/device.py", line 981, in set
self._set_control(full_key)
File "/config/custom_components/smartthinq_sensors/wideq/device.py", line 959, in _set_control
self._client.session.set_device_v2_controls(
File "/config/custom_components/smartthinq_sensors/wideq/core_v2.py", line 604, in set_device_v2_controls
res = self.post2(path, payload)
File "/config/custom_components/smartthinq_sensors/wideq/core_v2.py", line 455, in post2
return lgedm2_post(
File "/config/custom_components/smartthinq_sensors/wideq/core_v2.py", line 202, in lgedm2_post
return manage_lge_result(out, is_api_v2)
File "/config/custom_components/smartthinq_sensors/wideq/core_v2.py", line 215, in manage_lge_result
raise exc.APIError(code, message)
custom_components.smartthinq_sensors.wideq.core_exceptions.APIError: ('0103', {'data': None})
`

The error occurs only when I use switch:
![image](https://user-images.githubusercontent.com/1622866/134094825-d05a639a-913e-4ece-a4a0-de289e4bdc2c.png)

which btw for me is in quite strange place

Thanks!

**Comment by ollo69** [comment]
Log message with URL for download JSON device info is shown during HA startup and not when you activate the switch. 

In any case that switch seems a group switch used to set all the switch in the group at same time, you should avoid use this. You should be able to disable it in `lovelace` configuration.

![image](https://user-images.githubusercontent.com/60491700/134095941-48509221-fde8-48b1-954a-3adec42860d4.png)

What happen if you use one switch at time?

**Comment by OldShaterhan** [comment]
I don't see url for it unfortunately :(

Where it should be editable in Lovelace?

Switching one at time works properly.

**Comment by ollo69** [comment]
Switch all together simply does not make sense. There is nothing to fix here, just don't use group switch for this.

**Comment by ollo69** [comment]
Close this issue because not integration problem.
