### ISSUE TITLE
 [BUG] Sensors not available anymore

### ISSUE THREAD

**Issue by MrockHunter12** [ollo69/ha-smartthinq-sensors#219]
After upgrading to v0.10.0 I only get one entity (power off). Everything was working before updating (temp, time ...).
Downgrading did not fix the issue.

![image](https://user-images.githubusercontent.com/88487145/135730833-f7ee5765-0002-4a22-a6bc-d4e8258f34db.png)

![image](https://user-images.githubusercontent.com/88487145/135731300-32ec9e95-e79f-4da3-bbd0-ee85bd6f5f08.png)

 In the log I have observed new error entries:
![image](https://user-images.githubusercontent.com/88487145/135730967-ac05b101-31b9-4e21-958b-87cdab3fa8d4.png)
![image](https://user-images.githubusercontent.com/88487145/135730993-367ca029-a290-488f-bf50-8b9defb87960.png)

 - Environment : RPI4
 - Home Assistant version installed: 2021.8.1
 - Component version installed: v0.9.2 / v0.9.3 / v0.10.0
 - Last know working version: v0.9.3 (after downgrading it did not work anymore)
 - LG device type and model with issue: LG Washer/DryerTWINWash
 - LG devices connected (list): ?
 
**Log1**

Logger: homeassistant.config_entries
Source: helpers/entity_component.py:181
First occurred: 20:11:29 (2 occurrences)
Last logged: 20:11:29

Error unloading entry LGE Devices for sensor
Error unloading entry LGE Devices for binary_sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 432, in async_unload
    result = await component.async_unload_entry(hass, self)  # type: ignore
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 96, in async_unload_entry
    return await component.async_unload_entry(entry)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 181, in async_unload_entry
    raise ValueError("Config entry was never loaded!")
ValueError: Config entry was never loaded!

**Log 2**

benutzerdefinierte

Logger: homeassistant.config_entries
Source: custom_components/smartthinq_sensors/sensor.py:245
Integration: SmartThinQ LGE Sensors (documentation, issues)
First occurred: 19:56:50 (4 occurrences)
Last logged: 20:11:33

Error setting up entry LGE Devices for sensor
Error setting up entry LGE Devices for binary_sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 293, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 90, in async_setup_entry
    return await component.async_setup_entry(entry)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 149, in async_setup_entry
    platform = await async_prepare_setup_platform(
  File "/usr/src/homeassistant/homeassistant/setup.py", line 329, in async_prepare_setup_platform
    platform = integration.get_platform(domain)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 498, in get_platform
    cache[full_name] = self._import_platform(platform_name)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 503, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/config/custom_components/smartthinq_sensors/sensor.py", line 245, in <module>
    ThinQSensorEntityDescription(
TypeError: __init__() got an unexpected keyword argument 'native_unit_of_measurement'

**Comment by ollo69** [comment]
I think this is at last the 5th ticket with the same issue reported. Upgrade HA tp 2021.9.x as specified in [release note](https://github.com/ollo69/ha-smartthinq-sensors/releases).

**Comment by MrockHunter12** [comment]
I am sorry, I just realized it now. Thank you for the answer ! I ll take care next time

**Comment by MrockHunter12** [comment]
working again with Home Assistant 2021.10.0b2.
