### ISSUE TITLE
[BUG] Error on AirPurifier filter life calculation

### ISSUE THREAD

**Issue by mo1seev** [ollo69/ha-smartthinq-sensors#235]
Integration not working since 0.10.1 (0.10.0 worked!)

I try reinstall, try "clear" install - still not work(

```
2021-10-24 20:55:51 WARNING (MainThread) [custom_components.smartthinq_sensors] Connection not available. ThinQ platform not ready
Traceback (most recent call last):
  File "/config/custom_components/smartthinq_sensors/__init__.py", line 197, in async_setup_entry
    lge_devices = await lge_devices_setup(hass, client)
  File "/config/custom_components/smartthinq_sensors/__init__.py", line 564, in lge_devices_setup
    if not await dev.init_device():
  File "/config/custom_components/smartthinq_sensors/__init__.py", line 337, in init_device
    features = self._state.device_features
  File "/config/custom_components/smartthinq_sensors/wideq/device.py", line 1371, in device_features
    self._update_features()
  File "/config/custom_components/smartthinq_sensors/wideq/airpurifier.py", line 157, in _update_features
    self.lower_filter_life,
  File "/config/custom_components/smartthinq_sensors/wideq/airpurifier.py", line 141, in lower_filter_life
    FEAT_LOWER_FILTER_LIFE, self._get_lower_filter_life(), False
  File "/config/custom_components/smartthinq_sensors/wideq/airpurifier.py", line 124, in _get_lower_filter_life
    return use_time/max_time*100
TypeError: unsupported operand type(s) for /: 'float' and 'str'
2021-10-24 20:55:51 WARNING (MainThread) [homeassistant.config_entries] Config entry 'LGE Devices' for smartthinq_sensors integration not ready yet: None; Retrying in background
2021-10-24 20:56:01 WARNING (MainThread) [custom_components.smartthinq_sensors] Connection not available. ThinQ platform not ready
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/usr/local/lib/python3.9/site-packages/urllib3/util/connection.py", line 73, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/local/lib/python3.9/socket.py", line 954, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Try again

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 358, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0xe7c93250>: Failed to establish a new connection: [Errno -3] Try again

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.9/site-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='ruic-service.lgthinq.com', port=46030): Max retries exceeded with url: /v1/service/application/dashboard (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xe7c93250>: Failed to establish a new connection: [Errno -3] Try again'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/smartthinq_sensors/__init__.py", line 172, in async_setup_entry
    client = await hass.async_add_executor_job(
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/smartthinq_sensors/__init__.py", line 126, in createClientFromToken
    client = ClientV2.from_token(
  File "/config/custom_components/smartthinq_sensors/wideq/core_v2.py", line 837, in from_token
    client.refresh()
  File "/config/custom_components/smartthinq_sensors/wideq/core_v2.py", line 819, in refresh
    self._load_devices()
  File "/config/custom_components/smartthinq_sensors/wideq/core_v2.py", line 685, in _load_devices
    self._devices = self._session.get_devices()
  File "/config/custom_components/smartthinq_sensors/wideq/core_v2.py", line 494, in get_devices
    dashboard = self.get2("service/application/dashboard")
  File "/config/custom_components/smartthinq_sensors/wideq/core_v2.py", line 481, in get2
    return thinq2_get(
  File "/config/custom_components/smartthinq_sensors/wideq/core_v2.py", line 146, in thinq2_get
    res = s.get(
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='ruic-service.lgthinq.com', port=46030): Max retries exceeded with url: /v1/service/application/dashboard (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xe7c93250>: Failed to establish a new connection: [Errno -3] Try again'))
2021-10-24 20:56:15 WARNING (MainThread) [custom_components.smartthinq_sensors] Connection not available. ThinQ platform not ready
Traceback (most recent call last):
  File "/config/custom_components/smartthinq_sensors/__init__.py", line 197, in async_setup_entry
    lge_devices = await lge_devices_setup(hass, client)
  File "/config/custom_components/smartthinq_sensors/__init__.py", line 564, in lge_devices_setup
    if not await dev.init_device():
  File "/config/custom_components/smartthinq_sensors/__init__.py", line 337, in init_device
    features = self._state.device_features
  File "/config/custom_components/smartthinq_sensors/wideq/device.py", line 1371, in device_features
    self._update_features()
  File "/config/custom_components/smartthinq_sensors/wideq/airpurifier.py", line 157, in _update_features
    self.lower_filter_life,
  File "/config/custom_components/smartthinq_sensors/wideq/airpurifier.py", line 141, in lower_filter_life
    FEAT_LOWER_FILTER_LIFE, self._get_lower_filter_life(), False
  File "/config/custom_components/smartthinq_sensors/wideq/airpurifier.py", line 124, in _get_lower_filter_life
    return use_time/max_time*100
TypeError: unsupported operand type(s) for /: 'float' and 'str'
```

**Comment by mo1seev** [comment]
Still don't work on 0.10.3


```
2021-10-30 10:13:51 WARNING (MainThread) [custom_components.smartthinq_sensors] Connection not available. ThinQ platform not ready
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 458, in connect
    cert = self.sock.getpeercert()
  File "/usr/local/lib/python3.9/ssl.py", line 1123, in getpeercert
    self._check_connected()
  File "/usr/local/lib/python3.9/ssl.py", line 1088, in _check_connected
    self.getpeername()
OSError: [Errno 107] Socket not connected

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.9/site-packages/urllib3/util/retry.py", line 532, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python3.9/site-packages/urllib3/packages/six.py", line 769, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 458, in connect
    cert = self.sock.getpeercert()
  File "/usr/local/lib/python3.9/ssl.py", line 1123, in getpeercert
    self._check_connected()
  File "/usr/local/lib/python3.9/ssl.py", line 1088, in _check_connected
    self.getpeername()
urllib3.exceptions.ProtocolError: ('Connection aborted.', OSError(107, 'Socket not connected'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/smartthinq_sensors/__init__.py", line 198, in async_setup_entry
    lge_devices = await lge_devices_setup(hass, client)
  File "/config/custom_components/smartthinq_sensors/__init__.py", line 565, in lge_devices_setup
    if not await dev.init_device():
  File "/config/custom_components/smartthinq_sensors/__init__.py", line 326, in init_device
    result = await self._hass.async_add_executor_job(
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/smartthinq_sensors/wideq/device.py", line 1038, in init_device_info
    self._model_data = self._client.model_url_info(
  File "/config/custom_components/smartthinq_sensors/wideq/core_v2.py", line 889, in model_url_info
    self._model_url_info[url] = self._load_json_info(url)
  File "/config/custom_components/smartthinq_sensors/wideq/core_v2.py", line 860, in _load_json_info
    resp = requests.get(info_url, timeout=DEFAULT_TIMEOUT).text
  File "/usr/local/lib/python3.9/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', OSError(107, 'Socket not connected'))
```

**Comment by ollo69** [comment]
Error here is completely different (`Connection aborted.', OSError(107, 'Socket not connected`) and have nothing to do with open issue. Check your network connection.

**Comment by mo1seev** [comment]
Ommm, but it work on 0.10.0 (i roll-back again).

**Comment by ollo69** [comment]
It could be just a temporary network issue. Can you try to install the last version again?

**Comment by mo1seev** [comment]
Yeah. After "clear" install its ok! Thx!
