### ISSUE TITLE
[BUG]Error retrieving login URL from ThinQ. Counry code India Language eng

### ISSUE THREAD

**Issue by drabishek22** [ollo69/ha-smartthinq-sensors#241]
**Describe the bug**
**Error retrieving login URL from ThinQ.**
[](url)
**Expected behavior**
If applicable, a clear and concise description of what you expected to happen.

**Screenshots**

**Environment details:**
 - Environment (HASSIO, Raspbian, etc):
 - Home Assistant version installed:
 - Component version installed:
 - Last know working version:
 - LG device type and model with issue:
 - LG devices connected (list):

**Output of HA logs**
Paste the relavant output of the HA log here.

This error originated from a custom integration.

Logger: custom_components.smartthinq_sensors
Source: custom_components/smartthinq_sensors/wideq/core_v2.py:146
Integration: SmartThinQ LGE Sensors (documentation, issues)
First occurred: 11:51:57 AM (10 occurrences)
Last logged: 12:13:03 PM

Error retrieving login URL from ThinQ
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/usr/local/lib/python3.9/site-packages/urllib3/util/connection.py", line 73, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/local/lib/python3.9/socket.py", line 954, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Try again

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 358, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x6410c2c8>: Failed to establish a new connection: [Errno -3] Try again

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.9/site-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='route.lgthinq.com', port=46030): Max retries exceeded with url: /v1/service/application/gateway-uri (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x6410c2c8>: Failed to establish a new connection: [Errno -3] Try again'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/smartthinq_sensors/__init__.py", line 105, in getLoginUrl
    login_url = client.gateway.oauth_url()
  File "/config/custom_components/smartthinq_sensors/wideq/core_v2.py", line 715, in gateway
    self._gateway = Gateway.discover(self._country, self._language)
  File "/config/custom_components/smartthinq_sensors/wideq/core_v2.py", line 327, in discover
    gw = gateway_info(country, language)
  File "/config/custom_components/smartthinq_sensors/wideq/core_v2.py", line 237, in gateway_info
    return thinq2_get(V2_GATEWAY_URL, country=country, language=language)
  File "/config/custom_components/smartthinq_sensors/wideq/core_v2.py", line 146, in thinq2_get
    res = s.get(
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='route.lgthinq.com', port=46030): Max retries exceeded with url: /v1/service/application/gateway-uri (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x6410c2c8>: Failed to establish a new connection: [Errno -3] Try again'))

**Additional context**

**Comment by drabishek22** [comment]
Error retrieving login URL from ThinQ
12:13:03 PM – (ERROR) SmartThinQ LGE Sensors (custom integration) - message first occurred at 11:51:57 AM and shows up 10 times

**Comment by drabishek22** [comment]
It can get it to work with region USA and English

**Comment by DanielAmigo** [comment]
Hi, I have the same problem from Spain. I have been using your integration for about 6 months without any problem (since it supports more than 1 AC, thank you) but today it has failed. Trying to make it work again, I deleted it and initialise the integration but when I try to log in, this is the response from the LG website.
![image](https://user-images.githubusercontent.com/17901737/142296322-cbf890f8-559d-4be5-85b1-76d71fe980f9.png)

Which means:
Sorry! The server encountered an internal error and could not complete your request, if the problem persists, please contact us at contact.lgaccount@lge.com.

If @drabishek22 have tried and the only solution is to change all devices to another account at  USA, well, I will do it, but maybe there are other way.

**Comment by akusokuzan** [comment]
Having the same issue device randomly all sensors are unavailable. Decided to try and reinstall and now I can't even do that. I noticed the LG app is still working but now it takes forever cycling through random art before it starts working

**Comment by krzysztof-magosa** [comment]
Stopped working for Poland as well.

**Comment by ollo69** [comment]
Please double check your that your account is working using LG App on your phone

**Comment by krzysztof-magosa** [comment]
LG App is working correctly.
In HA I'm not even getting link for logon, so have no chance to enter credentials.

**Comment by DeadlySin2** [comment]
Same for Russian Federation. I am login in the app but i can't login via HA. IF i'm using URL - i recive wrong URL error. If i'm using login and password - wrong credentials. 
Moreover i recieve many errors that LGE can't connect to server.

**Comment by ollo69** [comment]
Just want to clarify that if you are not able to retrieve the login URL, possible cause are:

- there is a firewall on your system that is blocking the gateway URL
- your internet provider is not allowing the access to the gateway URL

When integration try to retrieve URL, just make a rest request to gateway URL `https://route.lgthinq.com:46030/v1/service/application/gateway-uri` using `country` and `language` as header for the request. I try my side to generate URL using India and Russian language and country, and the URL is generated without problem. So you have to check your firewall and internet provider, there is nothing that I can change at integration side to fix this problem.

**Comment by sleeplesslord** [comment]
I had this issue too. Leaving a comment on how I solved it in case it helps other people

I'm running HA in a docker container on my raspberry pi. I had the same connection error, and I figured out that it was because DNS resolution wasn't working from the docker container. I solved it by adding google DNS to `/etc/resolv.conf` inside the container. After doing that I was able to setup the integration without issue.

**Comment by aldets** [comment]
I have another bizarre situation.
I fill the information after "Add Integration". My e-mail, password, Country Code and Language Code are Estonian.
I get to the part where it gives me the SMartThingQ login URL. I go there and login with my email and password. After pressing OK, it just changes the login site to English and that's it. Does not give me a Redirection URL.
I can access the app on my phone and everything is working there.
I don't remember why but at one point the HA integration just stopped working.
