### ISSUE TITLE
Fridge/Freezer Temps Incorrect

### ISSUE THREAD

**Issue by LongDono** [ollo69/ha-smartthinq-sensors#25]
First, it's great to have your work on this integration!

I've noticed for my LG Fridge that the fridge and freezer temps both report as 9 degrees (should be 4 and -18). I tried turning on my LG Dishwasher out of curiosity but that appears to not be supported yet.

In addition to the debut log I can email to you, I did note the following (possibly unrelated translation) errors:

2020-04-26 11:04:20 ERROR (SyncWorker_14) [homeassistant.util.json] JSON file reading failed: /config/custom_components/smartthinq_sensors/.translations/sensor.en.json
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/util/json.py", line 30, in load_json
    with open(filename, encoding="utf-8") as fdesc:
NotADirectoryError: [Errno 20] Not a directory: '/config/custom_components/smartthinq_sensors/.translations/sensor.en.json'
2020-04-26 11:04:20 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.140320224258064] Error handling message: Unknown error
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/util/json.py", line 30, in load_json
    with open(filename, encoding="utf-8") as fdesc:
NotADirectoryError: [Errno 20] Not a directory: '/config/custom_components/smartthinq_sensors/.translations/sensor.en.json'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 20, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/frontend/__init__.py", line 549, in websocket_get_translations
    resources = await async_get_translations(hass, msg["language"])
  File "/usr/src/homeassistant/homeassistant/helpers/translation.py", line 152, in async_get_translations
    resources = await async_get_component_resources(hass, language)
  File "/usr/src/homeassistant/homeassistant/helpers/translation.py", line 135, in async_get_component_resources
    loaded_translations = await load_translations_job
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/translation.py", line 74, in load_translations_files
    loaded_json = load_json(translation_file)
  File "/usr/src/homeassistant/homeassistant/util/json.py", line 40, in load_json
    raise HomeAssistantError(error)
homeassistant.exceptions.HomeAssistantError: [Errno 20] Not a directory: '/config/custom_components/smartthinq_sensors/.translations/sensor.en.json'
2020-04-26 11:04:20 ERROR (SyncWorker_0) [homeassistant.util.json] JSON file reading failed: /config/custom_components/smartthinq_sensors/.translations/sensor.en.json
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/util/json.py", line 30, in load_json
    with open(filename, encoding="utf-8") as fdesc:
NotADirectoryError: [Errno 20] Not a directory: '/config/custom_components/smartthinq_sensors/.translations/sensor.en.json'
2020-04-26 11:04:20 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.140320213398672] Error handling message: Unknown error
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/util/json.py", line 30, in load_json
    with open(filename, encoding="utf-8") as fdesc:
NotADirectoryError: [Errno 20] Not a directory: '/config/custom_components/smartthinq_sensors/.translations/sensor.en.json'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 20, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/frontend/__init__.py", line 549, in websocket_get_translations
    resources = await async_get_translations(hass, msg["language"])
  File "/usr/src/homeassistant/homeassistant/helpers/translation.py", line 152, in async_get_translations
    resources = await async_get_component_resources(hass, language)
  File "/usr/src/homeassistant/homeassistant/helpers/translation.py", line 135, in async_get_component_resources
    loaded_translations = await load_translations_job
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/translation.py", line 74, in load_translations_files
    loaded_json = load_json(translation_file)
  File "/usr/src/homeassistant/homeassistant/util/json.py", line 40, in load_json
    raise HomeAssistantError(error)
homeassistant.exceptions.HomeAssistantError: [Errno 20] Not a directory: '/config/custom_components/smartthinq_sensors/.translations/sensor.en.json'

**Comment by ollo69** [comment]
What is the version of HA that you are using?

**Comment by LongDono** [comment]
I just upgraded to Home Assistant 0.108.9 from .8, I am not sure if I was on 0.107 prior to installing the ThinQ integration.

**Comment by ollo69** [comment]
It looks like is not finding ".tranlslation" directory. Is this directory present in the component folder? How do you install component, did you use HACS?

**Comment by LongDono** [comment]
Yes, installed with HACS. 

.translations is a file, translations is a folder:

donovan@Crushinator:/usr/share/hassio/homeassistant/custom_components/smartthinq_sensors$ ls -lA
total 76
-rw-r--r-- 1 root root   279 Apr 26 10:41 binary_sensor.py
-rw-r--r-- 1 root root 10599 Apr 26 10:41 config_flow.py
-rw-r--r-- 1 root root   779 Apr 26 10:41 const.py
-rw-r--r-- 1 root root 11257 Apr 26 10:41 __init__.py
-rw-r--r-- 1 root root   238 Apr 26 10:41 manifest.json
drwxr-xr-x 2 root root  4096 Apr 26 10:41 __pycache__
-rw-r--r-- 1 root root 23184 Apr 26 10:41 sensor.py
drwxr-xr-x 2 root root  4096 Apr 26 10:41 translations
-rw-r--r-- 1 root root    12 Apr 26 10:41 .translations
drwxr-xr-x 3 root root  4096 Apr 26 10:41 wideq

donovan@Crushinator:/usr/share/hassio/homeassistant/custom_components/smartthinq_sensors/translations$ ls -lA
total 4
-rw-r--r-- 1 root root 2003 Apr 26 10:41 en.json

**Comment by ollo69** [comment]
My mistake, please use last released version (0.3.7) that fix .translation folder issue

**Comment by LongDono** [comment]
That's great, thanks. That cleared up the translation errors. Regarding the temperatures being incorrect, should I leave this report open, create another, or close as it's a known issue? Thanks again.

**Comment by ollo69** [comment]
To fix this I need that you enable debug and send to me your log file as described [here](https://github.com/ollo69/ha-smartthinq-sensors/issues/16#issuecomment-616133690).
I need this to analize your model and fix issue.

**Comment by ollo69** [comment]
Sorry, I see just now that you send me debug. But can you attach log file instead of copying log in the e-mail? 
Thanks

**Comment by ollo69** [comment]
Please retry now with last version and let me know if temperatures are correctly shown.

**Comment by LongDono** [comment]
Yes! You got it! They are correct now. Awesome job.
