### ISSUE TITLE
Lags in AC status since upgrade to HA 2021.12.0. Sometimes cannot switch unit off. 

### ISSUE THREAD

**Issue by chrisuk-web** [ollo69/ha-smartthinq-sensors#251]
**Describe the bug**
Lag between turning A/C on and seeing status in HA. Sometimes can't turn a unit off from HA, but then I wait a couple of minutes try again and it works ok if I try again.

**Expected behavior**
Normally updates are instant

**Screenshots**
N/A

**Environment details:**
 - Environment (HASSIO, Raspbian, etc): hassio 7.0.rc1
 - Home Assistant version installed: 2021.12.0
 - Component version installed: 0.10.7
 - Last know working version: 2021.11.x
 - LG device type and model with issue: S09ET NSJ
 - LG devices connected (list): four devices:
 - Lounge AC, Office, Wall-mounted type 1, Bedroom 1

**Output of HA logs**
Logger: homeassistant.core
Source: custom_components/smartthinq_sensors/wideq/core_v2.py:186
Integration: SmartThinQ LGE Sensors (documentation, issues)
First occurred: 21:32:51 (6 occurrences)
Last logged: 22:05:42

Error executing service: <ServiceCall climate.set_hvac_mode (c:845df3620246588455cf27ca706b8c2d): entity_id=['climate.wall_mounted_type2'], hvac_mode=fan_only>
Error executing service: <ServiceCall climate.set_hvac_mode (c:3ed4624b3303899033e91af692ed8e09): entity_id=['climate.wall_mounted_type2'], hvac_mode=off>
Error executing service: <ServiceCall climate.set_hvac_mode (c:535ea99c41f570c9bc0b0442c0a8d619): entity_id=['climate.wall_mounted_type2'], hvac_mode=off>
Error executing service: <ServiceCall climate.set_hvac_mode (c:b2387370699b7e5501c1103b9beb351c): entity_id=['climate.wall_mounted_type2'], hvac_mode=heat>
Error executing service: <ServiceCall climate.set_hvac_mode (c:69573c0d035cfd9a601c38f8562eade9): entity_id=['climate.wall_mounted_type1'], hvac_mode=heat>
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/lib/python3.9/http/client.py", line 1371, in getresponse
    response.begin()
  File "/usr/local/lib/python3.9/http/client.py", line 319, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python3.9/http/client.py", line 280, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/local/lib/python3.9/socket.py", line 704, in readinto
    return self._sock.recv_into(b)
  File "/usr/local/lib/python3.9/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/local/lib/python3.9/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.9/site-packages/urllib3/util/retry.py", line 532, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python3.9/site-packages/urllib3/packages/six.py", line 770, in reraise
    raise value
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 447, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 336, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='eic-service.lgthinq.com', port=46030): Read timed out. (read timeout=10)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/core.py", line 1511, in catch_exceptions
    await coro_or_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1530, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 209, in handle_service
    await self.hass.helpers.service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 663, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 896, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 700, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 470, in async_set_hvac_mode
    await self.hass.async_add_executor_job(self.set_hvac_mode, hvac_mode)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/smartthinq_sensors/climate.py", line 242, in set_hvac_mode
    self._device.power(False)
  File "/config/custom_components/smartthinq_sensors/wideq/ac.py", line 566, in power
    self.set(keys[0], keys[1], key=keys[2], value=op_value)
  File "/config/custom_components/smartthinq_sensors/wideq/ac.py", line 647, in set
    super().set(
  File "/config/custom_components/smartthinq_sensors/wideq/device.py", line 1019, in set
    self._set_control(
  File "/config/custom_components/smartthinq_sensors/wideq/device.py", line 987, in _set_control
    self._client.session.set_device_v2_controls(
  File "/config/custom_components/smartthinq_sensors/wideq/core_v2.py", line 621, in set_device_v2_controls
    res = self.post2(cmd_path, payload)
  File "/config/custom_components/smartthinq_sensors/wideq/core_v2.py", line 455, in post2
    return lgedm2_post(
  File "/config/custom_components/smartthinq_sensors/wideq/core_v2.py", line 186, in lgedm2_post
    res = s.post(
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 590, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 529, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='eic-service.lgthinq.com', port=46030): Read timed out. (read timeout=10)

**Additional context**

**Comment by ollo69** [comment]
In the log only see timeouts errors, and I don't think that this can be related to HA or integration version.
Timeout is quite high (10 seconds) so you should check that you don't have network issue and that your HA device do not have issue like high cpu usage that can create performance problems,

**Comment by ollo69** [comment]
I do not received any feed-back on this issue opened about 3 months ago, so I close it. If you still have problem open a new one with all possible details.
