### ISSUE TITLE
Not working anymore

### ISSUE THREAD

**Issue by xXDjMikeXx** [ollo69/ha-smartthinq-sensors#254]
Today it stopped working, I tried to set it up again, but I get an Error wich say:

Invalid redirection URL. Make sure you can access the ThinQ app on your phone. You can get support [over here](https://git.io/JTjid).

 - Home Assistant 2021.12.2
 - Component version installed: 0.10.7
 - Last know working version: 0.10.7

**Output of HA logs**

Logger: custom_components.smartthinq_sensors
Source: custom_components/smartthinq_sensors/wideq/core_v2.py:270 
Integration: SmartThinQ LGE Sensors (documentation, issues) 
First occurred: 22:24:53 (1 occurrences) 
Last logged: 22:24:53

Error retrieving OAuth info from ThinQ
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/usr/local/lib/python3.9/site-packages/urllib3/util/connection.py", line 73, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/local/lib/python3.9/socket.py", line 954, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name does not resolve

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 358, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f7d139880>: Failed to establish a new connection: [Errno -2] Name does not resolve

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.9/site-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='gb.lgeapi.com', port=443): Max retries exceeded with url: /oauth/1.0/oauth2/token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f7d139880>: Failed to establish a new connection: [Errno -2] Name does not resolve'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/smartthinq_sensors/__init__.py", line 122, in getOAuthInfoFromUrl
    oauth_info = ClientV2.oauthinfo_from_url(callback_url)
  File "/config/custom_components/smartthinq_sensors/wideq/core_v2.py", line 862, in oauthinfo_from_url
    access_token, refresh_token = login(oauth_url, auth_code)
  File "/config/custom_components/smartthinq_sensors/wideq/core_v2.py", line 290, in login
    out = auth_request(
  File "/config/custom_components/smartthinq_sensors/wideq/core_v2.py", line 270, in auth_request
    res = s.post(url, headers=headers, data=data, timeout=DEFAULT_TIMEOUT)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 590, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='gb.lgeapi.com', port=443): Max retries exceeded with url: /oauth/1.0/oauth2/token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f7d139880>: Failed to establish a new connection: [Errno -2] Name does not resolve'))

**Comment by ollo69** [comment]
Double check your network configuration. Seems to be a problem related to network name resolution (DNS), or a problem on LG servers.

**Comment by xXDjMikeXx** [comment]
Hmm thanks…I will try it in a few hours again

**Comment by xXDjMikeXx** [comment]
It’s working again…🤷🏻‍♂️😂
