### ISSUE TITLE
The fridge sensors are no longer charged

### ISSUE THREAD

**Issue by sidwin9** [ollo69/ha-smartthinq-sensors#264]
**Describe the bug**
Since version 0.12.1 the sensors in my fridge are not charged and active

**Expected behavior**
If applicable, a clear and concise description of what you expected to happen.

**Screenshots**

**Environment details:**
 - Environment (HASSIO, Raspbian, etc): HASSIO
 - Home Assistant version installed: 2021.12.8
 - Component version installed:
 - Last know working version:
 - LG device type and model with issue: Combi LG GBB92STAXP
 - LG devices connected (list): Combi LG GBB92STAXP

**Output of HA logs**
Paste the relavant output of the HA log here.

```
Logger: homeassistant
Source: custom_components/hacs/repositories/base.py:942
Integration: HACS (documentation, issues)
First occurred: 17:54:52 (1 occurrences)
Last logged: 17:54:52

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/hacs/base.py", line 580, in startup_tasks
    await self.recurring_tasks_installed()
  File "/config/custom_components/hacs/base.py", line 678, in recurring_tasks_installed
    await self.handle_critical_repositories()
  File "/config/custom_components/hacs/base.py", line 656, in handle_critical_repositories
    await critical_queue.execute()
  File "/config/custom_components/hacs/utils/queue_manager.py", line 69, in execute
    await asyncio.gather(*local_queue)
  File "/config/custom_components/hacs/utils/decorator.py", line 22, in wrapper
    await function(*args, **kwargs)
  File "/config/custom_components/hacs/repositories/integration.py", line 104, in update_repository
    if not await self.common_update(ignore_issues, force) and not force:
  File "/config/custom_components/hacs/utils/decorator.py", line 22, in wrapper
    await function(*args, **kwargs)
  File "/config/custom_components/hacs/repositories/base.py", line 516, in common_update
    await self.common_update_data(ignore_issues=ignore_issues, force=force)
  File "/config/custom_components/hacs/repositories/base.py", line 942, in common_update_data
    raise HacsRepositoryArchivedException("Repository is archived.")
custom_components.hacs.exceptions.HacsRepositoryArchivedException: Repository is archived.

Logger: homeassistant.setup
Source: setup.py:153
First occurred: 17:53:34 (1 occurrences)
Last logged: 17:53:34

Setup failed for smartthinq_sensors: Integration not found.
```

**Additional context**

**Comment by ollo69** [comment]
This is an issue related to HACS (see #261). Please upgrade HACS to last version and re-install integration. Please remember to close this issue if problem is solved.

**Comment by ollo69** [comment]
Closing this issue because should not related to the integration. Open a new one if after upgrading HACS you still have problems.
