### ISSUE TITLE
My error :(

### ISSUE THREAD

**Issue by drako86** [ollo69/ha-smartthinq-sensors#265]
I tried to search ... but I didn't find anything like it, I've already updated HACS is downloaded the integration several times ...

Questo errore ha avuto origine da un'integrazione personalizzata.

Logger: custom_components.smartthinq_sensors
Source: custom_components/smartthinq_sensors/wideq/core_v2.py:438 
Integration: SmartThinQ LGE Sensors (documentation, issues) 
First occurred: 21:55:11 (2 occurrences) 
Last logged: 21:56:36

Connection not available. ThinQ platform not ready
Traceback (most recent call last):
  File "/config/custom_components/smartthinq_sensors/__init__.py", line 191, in async_setup_entry
    client = await hass.async_add_executor_job(
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/smartthinq_sensors/__init__.py", line 130, in create_client_from_token
    client = ClientV2.from_token(
  File "/config/custom_components/smartthinq_sensors/wideq/core_v2.py", line 1094, in from_token
    client.refresh()
  File "/config/custom_components/smartthinq_sensors/wideq/core_v2.py", line 1053, in refresh
    self._auth = self.auth.refresh(True)
  File "/config/custom_components/smartthinq_sensors/wideq/core_v2.py", line 602, in refresh
    access_token, token_validity = refresh_auth(self.oauth_url, self.refresh_token)
  File "/config/custom_components/smartthinq_sensors/wideq/core_v2.py", line 473, in refresh_auth
    out = auth_request(
  File "/config/custom_components/smartthinq_sensors/wideq/core_v2.py", line 438, in auth_request
    raise exc.TokenError()
custom_components.smartthinq_sensors.wideq.core_exceptions.TokenError

**Comment by ollo69** [comment]
This error normally occur because your refresh token us not valid anymore. Check in mobile phone app if there are new terms condition to accept, than try removing and reconfiguring integration in HA.
