### ISSUE TITLE
Connection not available. ThinQ platform not ready

### ISSUE THREAD

**Issue by jgasparelo** [ollo69/ha-smartthinq-sensors#273]
Logger: custom_components.smartthinq_sensors
Source: custom_components/smartthinq_sensors/wideq/core_v2.py:1131
Integration: SmartThinQ LGE Sensors (documentation, issues)
First occurred: 23:42:43 (3 occurrences)
Last logged: 23:43:10

Connection not available. ThinQ platform not ready
Traceback (most recent call last):
  File "/config/custom_components/smartthinq_sensors/__init__.py", line 217, in async_setup_entry
    lge_devices = await lge_devices_setup(hass, client)
  File "/config/custom_components/smartthinq_sensors/__init__.py", line 442, in lge_devices_setup
    if not await dev.init_device():
  File "/config/custom_components/smartthinq_sensors/__init__.py", line 331, in init_device
    result = await self._hass.async_add_executor_job(
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/smartthinq_sensors/wideq/device.py", line 1283, in init_device_info
    self._model_data = self._client.model_url_info(
  File "/config/custom_components/smartthinq_sensors/wideq/core_v2.py", line 1158, in model_url_info
    self._model_url_info[url] = self._load_json_info(url)
  File "/config/custom_components/smartthinq_sensors/wideq/core_v2.py", line 1131, in _load_json_info
    return json.loads(enc_resp)
  File "/usr/local/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by ollo69** [comment]
There is a dedicate template to create issue. Please open a new issue using correct template and fill all required information.👍
