### ISSUE TITLE
Connection not available. ThinQ platform not read

### ISSUE THREAD

**Issue by jgasparelo** [ollo69/ha-smartthinq-sensors#275]
**Describe the bug**
Equipment is unavailable
![bug](https://user-images.githubusercontent.com/58477613/150696056-ebcc9608-2b9a-4f84-a769-aacf26d95149.png)

**Expected behavior**

**Screenshots**
![bug](https://user-images.githubusercontent.com/58477613/150696056-ebcc9608-2b9a-4f84-a769-aacf26d95149.png)
![bug2](https://user-images.githubusercontent.com/58477613/150696142-1a7d6c40-6379-4f09-97d6-97d90777da17.png)

**Environment details:**
 - HASSIO, Raspbian, etc): hassio, linux
 - Home Assistant version installed: Home Assistant OS 7.1
 - Component version installed: 0.12.5
 - Last know working version: 0.12.5
 - LG device type and model with issue: Air Conditioner
 - LG devices connected (list): RAC_056905_WW-RAC (AC) - Firmware: clip_hna_v1.9.116

**Output of HA logs**
Este erro originou-se de uma integração personalizada.

Logger: custom_components.smartthinq_sensors
Source: custom_components/smartthinq_sensors/wideq/core_v2.py:1131
Integration: SmartThinQ LGE Sensors (documentation, issues)
First occurred: 03:02:58 (550 occurrences)
Last logged: 16:11:04

Connection not available. ThinQ platform not ready
Traceback (most recent call last):
  File "/config/custom_components/smartthinq_sensors/__init__.py", line 217, in async_setup_entry
    lge_devices = await lge_devices_setup(hass, client)
  File "/config/custom_components/smartthinq_sensors/__init__.py", line 442, in lge_devices_setup
    if not await dev.init_device():
  File "/config/custom_components/smartthinq_sensors/__init__.py", line 331, in init_device
    result = await self._hass.async_add_executor_job(
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/smartthinq_sensors/wideq/device.py", line 1283, in init_device_info
    self._model_data = self._client.model_url_info(
  File "/config/custom_components/smartthinq_sensors/wideq/core_v2.py", line 1158, in model_url_info
    self._model_url_info[url] = self._load_json_info(url)
  File "/config/custom_components/smartthinq_sensors/wideq/core_v2.py", line 1131, in _load_json_info
    return json.loads(enc_resp)
  File "/usr/local/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Additional context**
In the LG App it keeps showing up "Unable to connect to network. try later. (E1015)" But all functions work through the app

**Comment by ollo69** [comment]
Integration is not able to retrieve all required information from LG cloud, so is not able to start. In details it fails while is trying to retrieve device JSON info that is mandatory to decode devices status.
If an error also is present in LG App, there is no doubt that is is LG side. You could try to logout and login again in LG App and see what happen.

**Comment by jgasparelo** [comment]
I deleted the devices from the APP and added it again. It worked.

Thank you for your help!!
