### ISSUE TITLE
Retrying setup: ThinQ platform not ready

### ISSUE THREAD

**Issue by virusczz** [ollo69/ha-smartthinq-sensors#303]
**Describe the bug**
A clear and concise description of what the bug is. **Retrying setup: ThinQ platform not ready**
If possible attach the JSON info file for your devices.

**Expected behavior**
If applicable, a clear and concise description of what you expected to happen.

**Screenshots**

**Environment details:**
 - Environment (HASSIO, Raspbian, etc): 
 - Home Assistant version installed: Home Assistant 2022.3.6
## System Health

version | core-2022.3.6
-- | --
installation_type | Home Assistant Supervised
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.9.9
os_name | Linux
os_version | 5.4.0-104-generic
arch | x86_64
timezone | Europe/Prague

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4537
Installed Version | 1.23.0
Stage | running
Available Repositories | 1007
Downloaded Repositories | 14

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | March 24, 2022, 1:00 AM
relayer_connected | true
remote_enabled | true
remote_connected | true
alexa_enabled | false
google_enabled | false
remote_server | eu-central-1-3.ui.nabu.casa
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Ubuntu 20.04.4 LTS
-- | --
update_channel | stable
supervisor_version | supervisor-2022.03.5
docker_version | 20.10.13
disk_total | 58.4 GB
disk_used | 28.9 GB
healthy | true
supported | failed to load: Unsupported
supervisor_api | ok
version_api | ok
installed_addons | Samba share (9.5.1), File editor (5.3.3), Log Viewer (0.13.0), Node-RED (11.1.1), Portainer (2.0.0), Studio Code Server (4.1.0), Terminal & SSH (9.3.0), Mosquitto broker (6.0.1), SQLite Web (3.3.0), MariaDB (2.4.0), phpMyAdmin (0.7.1), InfluxDB (4.4.0), Grafana (7.5.1)

</details>

<details><summary>Lovelace</summary>

dashboards | 1
-- | --
resources | 6
views | 13
mode | storage

</details>

 - Component version installed: latest
 - Last know working version: i tryed also older one, but i think was with HA update to 2022.3
 - LG device type and model with issue:  all (washer, dryer, clima)
 - LG devices connected (list):

**Output of HA logs**
Paste the relavant output of the HA log here.

```
This error originated from a custom integration.

Logger: custom_components.smartthinq_sensors
Source: custom_components/smartthinq_sensors/wideq/core_v2.py:1191
Integration: SmartThinQ LGE Sensors (documentation, issues)
First occurred: 8:02:06 PM (4 occurrences)
Last logged: 8:02:52 PM

Connection not available. ThinQ platform not ready
Traceback (most recent call last):
  File "/config/custom_components/smartthinq_sensors/__init__.py", line 218, in async_setup_entry
    lge_devices, unsupported_devices = await lge_devices_setup(hass, client)
  File "/config/custom_components/smartthinq_sensors/__init__.py", line 449, in lge_devices_setup
    if not await dev.init_device():
  File "/config/custom_components/smartthinq_sensors/__init__.py", line 336, in init_device
    result = await self._hass.async_add_executor_job(
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/smartthinq_sensors/wideq/device.py", line 1303, in init_device_info
    self._model_data = self._client.model_url_info(
  File "/config/custom_components/smartthinq_sensors/wideq/core_v2.py", line 1218, in model_url_info
    self._model_url_info[url] = self._load_json_info(url)
  File "/config/custom_components/smartthinq_sensors/wideq/core_v2.py", line 1191, in _load_json_info
    return json.loads(enc_resp)
  File "/usr/local/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

```

**Additional context**

**Comment by virusczz** [comment]
accoring to this:
https://github.com/ollo69/ha-smartthinq-sensors/issues/275
i falowed the steps and all ok. I started to add them step by step
