### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xbc in position 20359: invalid start byte

### ISSUE THREAD

**Issue by nukusinji** [ollo69/ha-smartthinq-sensors#325]
**Describe the bug**
If possible attach the JSON info file for your devices.

**Expected behavior**
If applicable, a clear and concise description of what you expected to happen.

**Screenshots**

**Environment details:**
 - Environment (HASSIO, Raspbian, etc):
 - Home Assistant version installed:
 - Component version installed:
 - Last know working version:
 - LG device type and model with issue:
 - LG devices connected (list):

**Output of HA logs**
Paste the relavant output of the HA log here.

Logger: custom_components.smartthinq_sensors
Source: custom_components/smartthinq_sensors/wideq/core_async.py:230
Integration: SmartThinQ LGE Sensors ([documentation](https://github.com/ollo69/ha-smartthinq-sensors), [issues](https://github.com/ollo69/ha-smartthinq-sensors/issues))
First occurred: 11:05:27 (35 occurrences)
Last logged: 11:48:26

Connection not available. ThinQ platform not ready
Traceback (most recent call last):
  File "/config/custom_components/smartthinq_sensors/__init__.py", line 203, in async_setup_entry
    lge_devices, unsupported_devices = await lge_devices_setup(hass, client)
  File "/config/custom_components/smartthinq_sensors/__init__.py", line 423, in lge_devices_setup
    if not await dev.init_device():
  File "/config/custom_components/smartthinq_sensors/__init__.py", line 313, in init_device
    if not await self._device.init_device_info():
  File "/config/custom_components/smartthinq_sensors/wideq/device.py", line 969, in init_device_info
    self._model_data = await self._client.model_url_info(
  File "/config/custom_components/smartthinq_sensors/wideq/core_async.py", line 1285, in model_url_info
    self._model_url_info[url] = await self._load_json_info(url)
  File "/config/custom_components/smartthinq_sensors/wideq/core_async.py", line 1257, in _load_json_info
    resp = await self._auth.gateway.core.http_get(info_url)
  File "/config/custom_components/smartthinq_sensors/wideq/core_async.py", line 230, in http_get
    result = await resp.text()
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client_reqrep.py", line 1085, in text
    return self._body.decode(  # type: ignore[no-any-return,union-attr]
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xbc in position 20359: invalid start byte

**Additional context**

**Comment by Veldkornet** [comment]
I have the same problem after updating to 0.20.0

**Comment by ollo69** [comment]
Please try using `v0.20.1` and let me know if this fix the issue.

**Comment by qkddn49** [comment]
v 0.20.1 Error

Logger: custom_components.smartthinq_sensors
Source: custom_components/smartthinq_sensors/wideq/core_async.py:1258
Integration: SmartThinQ LGE Sensors ([documentation](https://github.com/ollo69/ha-smartthinq-sensors), [issues](https://github.com/ollo69/ha-smartthinq-sensors/issues))
First occurred: 18:49:24 (9 occurrences)
Last logged: 18:57:03

Connection not available. ThinQ platform not ready
Traceback (most recent call last):
  File "/config/custom_components/smartthinq_sensors/__init__.py", line 203, in async_setup_entry
    lge_devices, unsupported_devices = await lge_devices_setup(hass, client)
  File "/config/custom_components/smartthinq_sensors/__init__.py", line 423, in lge_devices_setup
    if not await dev.init_device():
  File "/config/custom_components/smartthinq_sensors/__init__.py", line 313, in init_device
    if not await self._device.init_device_info():
  File "/config/custom_components/smartthinq_sensors/wideq/device.py", line 969, in init_device_info
    self._model_data = await self._client.model_url_info(
  File "/config/custom_components/smartthinq_sensors/wideq/core_async.py", line 1284, in model_url_info
    self._model_url_info[url] = await self._load_json_info(url)
  File "/config/custom_components/smartthinq_sensors/wideq/core_async.py", line 1258, in _load_json_info
    return json.loads(enc_resp)
  File "/usr/local/lib/python3.9/json/__init__.py", line 341, in loads
    s = s.decode(detect_encoding(s), 'surrogatepass')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xbc in position 20359: invalid start byte

**Comment by ollo69** [comment]
Seems I have to encode once more. I will fix later this evening.

**Comment by ollo69** [comment]
Please try again with `v0.20.2`, hope now is solved.

**Comment by qkddn49** [comment]
> Please try again with `v0.20.2`, hope now is solved.

Thank you.  It's working fine

**Comment by nukusinji** [comment]
> Please try again with `v0.20.2`, hope now is solved.

Thanks~
