### ISSUE TITLE
Cannot attach integration using Google account.

### ISSUE THREAD

**Issue by GalenOfTheShadows** [ollo69/ha-smartthinq-sensors#333]
I get the auth URL, go to the link and authorize with Google, then am returned to: https://us.m.lgaccount.com/spx/member/showMenuList

**Environment details:**
 - Environment (HASSIO, Raspbian, etc): Homeassistant OS
 - Home Assistant version installed: 
 --Home Assistant Core 2022.5.5
 --Home Assistant Supervisor 2022.05.3
 --Home Assistant OS 8.1
 --Kernel version 5.15.41
 --Agent version 1.2.1
 - Component version installed: V.0.22.0
 - Last know working version: N/A
 - LG device type and model with issue: N/A
 - LG devices connected (list): N/A

**Output of HA logs**
Paste the relavant output of the HA log here.

```
Logger: custom_components.smartthinq_sensors
Source: custom_components/smartthinq_sensors/wideq/core_async.py:93
Integration: SmartThinQ LGE Sensors ([documentation](https://github.com/ollo69/ha-smartthinq-sensors), [issues](https://github.com/ollo69/ha-smartthinq-sensors/issues))
First occurred: 12:48:32 (5 occurrences)
Last logged: 14:46:35

Error retrieving OAuth info from ThinQ
Traceback (most recent call last):
  File "/config/custom_components/smartthinq_sensors/__init__.py", line 96, in get_auth_info_from_url
    return await ClientAsync.oauth_info_from_url(callback_url, aiohttp_session=session)
  File "/config/custom_components/smartthinq_sensors/wideq/core_async.py", line 1250, in oauth_info_from_url
    result = await Auth.oauth_info_from_url(url, core)
  File "/config/custom_components/smartthinq_sensors/wideq/core_async.py", line 669, in oauth_info_from_url
    result = oauth_info_from_url(url)
  File "/config/custom_components/smartthinq_sensors/wideq/core_async.py", line 93, in oauth_info_from_url
    "oauth_url": parsed_info["oauth2_backend_url"],
KeyError: 'oauth2_backend_url'
```

**Additional context**
I have tested this both through the Android app and PC browser based. On Android, the LG app is installed and working properly. Both attempts failed with the same invalid URL message.

**Comment by theturtle32** [comment]
The [README.md](https://github.com/ollo69/ha-smartthinq-sensors/blob/master/README.md) file at the root of this repo says:

> **Important**: The component will **not work if you have logged into the ThinQ application and registered your devices using a social network account** (Google, Facebook or Amazon). In order to use the component you need to create a new independent LG account and make sure you log into the ThinQ app and associate your devices with it.

**Comment by ollo69** [comment]
Closing this issue, as explained social network account are not supported.
