### ISSUE TITLE
platform not ready

### ISSUE THREAD

**Issue by polkovnichenko** [ollo69/ha-smartthinq-sensors#336]
**Describe the bug**
It is not connected by a redirect or a direct connector. No evidence is required on the phone. I changed the password. I rearranged repeatedly, lower the version. The result is the same.

**Expected behavior**
If applicable, a clear and concise description of what you expected to happen.

**Screenshots**
https://prnt.sc/SG-Ynwv1j8m4
https://prnt.sc/Bd5tXRrMqJ5S
https://prnt.sc/DIfvAPcJSD2M
https://prnt.sc/XLhkVwSa3e5e
https://prnt.sc/hHzyikx-aGRM

**Environment details:**
 - Environment (HASSIO, Raspbian, etc):
 - Home Assistant version installed:
 - Component version installed:
 - Last know working version:
 - LG device type and model with issue:
 - LG devices connected (list):

**Output of HA logs**
Paste the relavant output of the HA log here.

```
Эта ошибка возникла в кастомной интеграции.

Logger: custom_components.smartthinq_sensors
Source: custom_components/smartthinq_sensors/wideq/core_async.py:228
Integration: SmartThinQ LGE Sensors (documentation, issues)
First occurred: 17:01:25 (1 occurrences)
Last logged: 17:01:25

Connection not available. ThinQ platform not ready
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 986, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1065, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1050, in create_connection
    sock = await self._connect_sock(
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 961, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/local/lib/python3.9/asyncio/selector_events.py", line 499, in sock_connect
    return await fut
  File "/usr/local/lib/python3.9/asyncio/selector_events.py", line 534, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
TimeoutError: [Errno 110] Connect call failed ('178.18.231.209', 443)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/smartthinq_sensors/__init__.py", line 213, in async_setup_entry
    lge_devices, unsupported_devices = await lge_devices_setup(hass, client)
  File "/config/custom_components/smartthinq_sensors/__init__.py", line 435, in lge_devices_setup
    if not await dev.init_device():
  File "/config/custom_components/smartthinq_sensors/__init__.py", line 323, in init_device
    if not await self._device.init_device_info():
  File "/config/custom_components/smartthinq_sensors/wideq/device.py", line 969, in init_device_info
    self._model_data = await self._client.model_url_info(
  File "/config/custom_components/smartthinq_sensors/wideq/core_async.py", line 1301, in model_url_info
    self._model_url_info[url] = await self._load_json_info(url)
  File "/config/custom_components/smartthinq_sensors/wideq/core_async.py", line 1259, in _load_json_info
    content = await self._auth.gateway.core.http_get_bytes(info_url)
  File "/config/custom_components/smartthinq_sensors/wideq/core_async.py", line 228, in http_get_bytes
    async with self._session.get(
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client.py", line 1138, in __aenter__
    self._resp = await self._coro
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client.py", line 535, in _request
    conn = await self._connector.connect(
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 542, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 907, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 1175, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 992, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host objectcontent.lgthinq.com:443 ssl:default [Connect call failed ('178.18.231.209', 443)]

```

**Additional context**
-

**Comment by polkovnichenko** [comment]
After update work normal
