### ISSUE TITLE
有問題

### ISSUE THREAD

**Issue by mountain0320** [ollo69/ha-smartthinq-sensors#338]
自行安裝整合產生錯誤。

Logger: homeassistant.core
Source: custom_components/smartthinq_sensors/wideq/core_async.py:325
Integration: SmartThinQ LGE Sensors (documentation, issues)
First occurred: 12:55:48 (5 occurrences)
Last logged: 12:57:07

Error executing service: <ServiceCall fan.turn_on (c:01G4VNWYRTJRZFCKRND92E907K): entity_id=['fan.kong_qi_qing_jing_ji'], percentage=50>
Error executing service: <ServiceCall fan.set_percentage (c:01G4VNYBNK1J5P19DZHJBY8QQM): entity_id=['fan.kong_qi_qing_jing_ji'], percentage=100>
Error executing service: <ServiceCall fan.turn_off (c:01G4VNZ7RMJ62VJ1WHZ0TGMNV4): entity_id=['fan.kong_qi_qing_jing_ji']>
Error executing service: <ServiceCall fan.turn_on (c:01G4VNZ8XJ6WGT5KC25F9HH11K): entity_id=['fan.kong_qi_qing_jing_ji']>
Error executing service: <ServiceCall fan.turn_off (c:01G4VNZBVQKT26F71DBQ6S40AE): entity_id=['fan.kong_qi_qing_jing_ji']>
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/core.py", line 1722, in catch_exceptions
    await coro_or_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1741, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 204, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 680, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 964, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 717, in _handle_entity_call
    await result
  File "/config/custom_components/smartthinq_sensors/fan.py", line 172, in async_turn_on
    await self._device.power(True)
  File "/config/custom_components/smartthinq_sensors/wideq/airpurifier.py", line 156, in power
    await self.set(keys[0], keys[1], key=keys[2], value=op_value)
  File "/config/custom_components/smartthinq_sensors/wideq/airpurifier.py", line 187, in set
    await super().set(
  File "/config/custom_components/smartthinq_sensors/wideq/device.py", line 1088, in set
    await self._set_control(
  File "/config/custom_components/smartthinq_sensors/wideq/device.py", line 1046, in _set_control
    await self._client.session.set_device_controls(
  File "/config/custom_components/smartthinq_sensors/wideq/core_async.py", line 965, in set_device_controls
    res = await self.post("rti/rtiControl", payload)
  File "/config/custom_components/smartthinq_sensors/wideq/core_async.py", line 822, in post
    return await self._auth.gateway.core.lgedm2_post(
  File "/config/custom_components/smartthinq_sensors/wideq/core_async.py", line 298, in lgedm2_post
    return self._manage_lge_result(out, is_api_v2)
  File "/config/custom_components/smartthinq_sensors/wideq/core_async.py", line 325, in _manage_lge_result
    raise exc.APIError(code, message)
custom_components.smartthinq_sensors.wideq.core_exceptions.APIError: 등록되지 않은 모델입니다.

**Comment by mountain0320** [comment]
Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/smartthinq_sensors/wideq/core_async.py:325
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 12:56:04 (3 occurrences)
Last logged: 12:57:15

[547860827680] 등록되지 않은 모델입니다.
[547825010000] 등록되지 않은 모델입니다.
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 193, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1704, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1741, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 204, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 680, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 964, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 717, in _handle_entity_call
    await result
  File "/config/custom_components/smartthinq_sensors/fan.py", line 180, in async_turn_off
    await self._device.power(False)
  File "/config/custom_components/smartthinq_sensors/wideq/airpurifier.py", line 156, in power
    await self.set(keys[0], keys[1], key=keys[2], value=op_value)
  File "/config/custom_components/smartthinq_sensors/wideq/airpurifier.py", line 187, in set
    await super().set(
  File "/config/custom_components/smartthinq_sensors/wideq/device.py", line 1088, in set
    await self._set_control(
  File "/config/custom_components/smartthinq_sensors/wideq/device.py", line 1046, in _set_control
    await self._client.session.set_device_controls(
  File "/config/custom_components/smartthinq_sensors/wideq/core_async.py", line 965, in set_device_controls
    res = await self.post("rti/rtiControl", payload)
  File "/config/custom_components/smartthinq_sensors/wideq/core_async.py", line 822, in post
    return await self._auth.gateway.core.lgedm2_post(
  File "/config/custom_components/smartthinq_sensors/wideq/core_async.py", line 298, in lgedm2_post
    return self._manage_lge_result(out, is_api_v2)
  File "/config/custom_components/smartthinq_sensors/wideq/core_async.py", line 325, in _manage_lge_result
    raise exc.APIError(code, message)
custom_components.smartthinq_sensors.wideq.core_exceptions.APIError: 등록되지 않은 모델입니다.

**Comment by ollo69** [comment]
If you need support:

- use English
- provide detail about your issue (based on issue template)

I close this incomprehensible issue.
