### ISSUE TITLE
the integration stopped working after updating from version v0.23.4 to v0.23.5

### ISSUE THREAD

**Issue by mousawm** [ollo69/ha-smartthinq-sensors#358]
**Describe the bug**
the integration stopped working, after going back to version v0.23.4 the integration worked again.

**Output of HA logs**

```
This error originated from a custom integration.

Logger: homeassistant.core
Source: custom_components/smartthinq_sensors/wideq/core_async.py:299
Integration: SmartThinQ LGE Sensors (documentation, issues)
First occurred: 1:09:13 PM (1 occurrences)
Last logged: 1:09:13 PM

Error executing service: <ServiceCall climate.set_hvac_mode (c:01G8QTWZA6TYPRRFC9CZN98P0Z): entity_id=['climate.halla_room_ac'], hvac_mode=cool>
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/core.py", line 1731, in catch_exceptions
    await coro_or_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1750, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 204, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 680, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 930, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 717, in _handle_entity_call
    await result
  File "/config/custom_components/smartthinq_sensors/climate.py", line 267, in async_set_hvac_mode
    await self._device.set_op_mode(operation_mode)
  File "/config/custom_components/smartthinq_sensors/wideq/ac.py", line 581, in set_op_mode
    await self.set(keys[0], keys[1], key=keys[2], value=mode_value)
  File "/config/custom_components/smartthinq_sensors/wideq/ac.py", line 653, in set
    await super().set(
  File "/config/custom_components/smartthinq_sensors/wideq/device.py", line 1088, in set
    await self._set_control(
  File "/config/custom_components/smartthinq_sensors/wideq/device.py", line 1046, in _set_control
    await self._client.session.set_device_controls(
  File "/config/custom_components/smartthinq_sensors/wideq/core_async.py", line 992, in set_device_controls
    res = await self.post("rti/rtiControl", payload)
  File "/config/custom_components/smartthinq_sensors/wideq/core_async.py", line 849, in post
    return await self._auth.gateway.core.lgedm2_post(
  File "/config/custom_components/smartthinq_sensors/wideq/core_async.py", line 299, in lgedm2_post
    async with self._get_session().post(
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client.py", line 1138, in __aenter__
    self._resp = await self._coro
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client.py", line 559, in _request
    await resp.start(conn)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client_reqrep.py", line 893, in start
    with self._timer:
  File "/usr/local/lib/python3.10/site-packages/aiohttp/helpers.py", line 721, in __exit__
    raise asyncio.TimeoutError from None
asyncio.exceptions.TimeoutError

```

**Comment by ollo69** [comment]
Uhm, this look strange! Are you sure that wasn0t just a temporary issue? New version is just creating a dedicated Client session, but timeout is unchanged. Did you check others function? Did entity sensors update?

**Comment by mousawm** [comment]
the problem seems to be temporary so I will close the issue.
