### ISSUE TITLE
Cant Login, at HA3

### ISSUE THREAD

**Issue by Fr3d3rick83** [ollo69/ha-smartthinq-sensors#395]
**Describe the bug**
I downloaded the extension via HACS and try to login, but I´ll get this error message:
Error connecting to SmartThinQ. Try again, and make sure you can access the ThinQ app on your phone.

Its working on my phone.

**Expected behavior**
If applicable, a clear and concise description of what you expected to happen.

**Screenshots**

**Environment details:**
 - Environment (HASSIO, Raspbian, etc):
 - Home Assistant version installed:
 - Component version installed:
 - Last know working version:
 - LG device type and model with issue:
 - LG devices connected (list):

**Output of HA logs**
```
Logger: custom_components.smartthinq_sensors.config_flow
Source: custom_components/smartthinq_sensors/wideq/core_async.py:519
Integration: SmartThinQ LGE Sensors ([documentation](https://github.com/ollo69/ha-smartthinq-sensors), [issues](https://github.com/ollo69/ha-smartthinq-sensors/issues))
First occurred: 12:59:08 (12 occurrences)
Last logged: 13:28:18
Error connecting to ThinQ

Traceback (most recent call last):
  File "/config/custom_components/smartthinq_sensors/config_flow.py", line 202, in _check_connection
    client = await lge_auth.create_client_from_login(
  File "/config/custom_components/smartthinq_sensors/__init__.py", line 117, in create_client_from_login
    return await ClientAsync.from_login(
  File "/config/custom_components/smartthinq_sensors/wideq/core_async.py", line 1226, in from_login
    auth = await Auth.from_user_login(gateway, username, password)
  File "/config/custom_components/smartthinq_sensors/wideq/core_async.py", line 748, in from_user_login
    user_number = await gateway.core.get_user_number(oauth_url, access_token)
  File "/config/custom_components/smartthinq_sensors/wideq/core_async.py", line 519, in get_user_number
    async with self._get_session().get(
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client.py", line 1138, in __aenter__
    self._resp = await self._coro
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client.py", line 466, in _request
    with timer:
  File "/usr/local/lib/python3.10/site-packages/aiohttp/helpers.py", line 721, in __exit__
    raise asyncio.TimeoutError from None
asyncio.exceptions.TimeoutError
```

**Additional context**

**Comment by Fr3d3rick83** [comment]
New warnings:

`Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: custom_components.smartthinq_sensors
Source: custom_components/smartthinq_sensors/wideq/core_async.py:548
Integration: SmartThinQ LGE Sensors (documentation, issues)
First occurred: 10:52:19 (1 occurrences)
Last logged: 10:52:19

Connection not available. ThinQ platform not ready
Traceback (most recent call last):
  File "/config/custom_components/smartthinq_sensors/__init__.py", line 221, in async_setup_entry
    client = await lge_auth.create_client_from_token(refresh_token, oauth_url)
  File "/config/custom_components/smartthinq_sensors/__init__.py", line 127, in create_client_from_token
    return await ClientAsync.from_token(
  File "/config/custom_components/smartthinq_sensors/wideq/core_async.py", line 1255, in from_token
    await client.refresh()
  File "/config/custom_components/smartthinq_sensors/wideq/core_async.py", line 1194, in refresh
    self._auth = await self.auth.refresh(True)
  File "/config/custom_components/smartthinq_sensors/wideq/core_async.py", line 777, in refresh
    access_token, token_validity = await self._gateway.core.refresh_auth(
  File "/config/custom_components/smartthinq_sensors/wideq/core_async.py", line 585, in refresh_auth
    out = await self._auth_request(
  File "/config/custom_components/smartthinq_sensors/wideq/core_async.py", line 548, in _auth_request
    async with self._get_session().post(
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client.py", line 1138, in __aenter__
    self._resp = await self._coro
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client.py", line 466, in _request
    with timer:
  File "/usr/local/lib/python3.10/site-packages/aiohttp/helpers.py", line 721, in __exit__
    raise asyncio.TimeoutError from None
asyncio.exceptions.TimeoutError
`

`Logger: homeassistant.config_entries
Source: config_entries.py:1088
First occurred: 18:13:52 (1 occurrences)
Last logged: 18:13:52

Config entry 'LGE Devices' for smartthinq_sensors integration not ready yet: ThinQ platform not ready; Retrying in background`
