### ISSUE TITLE
integration is constantly falling off

### ISSUE THREAD

**Issue by oksibutch** [ollo69/ha-smartthinq-sensors#396]
**Describe the bug**
Spontaneously, against the background of the correct operation of the API, the integration stops responding and issues the following error
after the HA reboot or integration, everything works correctly for a while

> Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/smartthinq_sensors/wideq/core_async.py:327
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 08:45:26 (3 occurrences)
Last logged: 08:45:41

[547022838208]
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 200, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1744, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1781, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 208, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 678, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 943, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 715, in _handle_entity_call
    await result
  File "/config/custom_components/smartthinq_sensors/climate.py", line 294, in async_set_hvac_mode
    await self._device.set_op_mode(operation_mode)
  File "/config/custom_components/smartthinq_sensors/wideq/ac.py", line 603, in set_op_mode
    await self.set(keys[0], keys[1], key=keys[2], value=mode_value)
  File "/config/custom_components/smartthinq_sensors/wideq/ac.py", line 709, in set
    await super().set(
  File "/config/custom_components/smartthinq_sensors/wideq/device.py", line 1129, in set
    await self._set_control(
  File "/config/custom_components/smartthinq_sensors/wideq/device.py", line 1097, in _set_control
    await self._client.session.set_device_v2_controls(
  File "/config/custom_components/smartthinq_sensors/wideq/core_async.py", line 1025, in set_device_v2_controls
    res = await self.post2(cmd_path, payload)
  File "/config/custom_components/smartthinq_sensors/wideq/core_async.py", line 865, in post2
    return await self._auth.gateway.core.lgedm2_post(
  File "/config/custom_components/smartthinq_sensors/wideq/core_async.py", line 316, in lgedm2_post
    return self._manage_lge_result(out, is_api_v2)
  File "/config/custom_components/smartthinq_sensors/wideq/core_async.py", line 327, in _manage_lge_result
    raise API2_ERRORS[code]()
custom_components.smartthinq_sensors.wideq.core_exceptions.NotLoggedInError

my devices are 2 air conditioners and 1 washing machine. I attach diagnostic data of the devices

[smartthinq_sensors-c57a8c55f0da6be77ce845adac50f79b-Кондиционер Спальня-43d6f5ed36306f25d546f8a74be79038.json.txt](https://github.com/ollo69/ha-smartthinq-sensors/files/9976633/smartthinq_sensors-c57a8c55f0da6be77ce845adac50f79b-.-43d6f5ed36306f25d546f8a74be79038.json.txt)
[smartthinq_sensors-c57a8c55f0da6be77ce845adac50f79b-СТИРАЛЬНАЯ МАШИНА-2ab0f6cc29831a047f2b28e83874688f.json.txt](https://github.com/ollo69/ha-smartthinq-sensors/files/9976634/smartthinq_sensors-c57a8c55f0da6be77ce845adac50f79b-.-2ab0f6cc29831a047f2b28e83874688f.json.txt)

[smartthinq_sensors-c57a8c55f0da6be77ce845adac50f79b-Кондиционер Зал-5876ecc9316ce783762b62cfdfdcb902.json.txt](https://github.com/ollo69/ha-smartthinq-sensors/files/9976635/smartthinq_sensors-c57a8c55f0da6be77ce845adac50f79b-.-5876ecc9316ce783762b62cfdfdcb902.json.txt)

**Comment by smarthomeaf** [comment]
I am having the same issue.   Seemed to start with 2020.11

**Comment by elenril2** [comment]
I have the same problem.

**Comment by ollo69** [comment]
Did you check for new TOS in LG mobile app?

**Comment by mutlucan96** [comment]
@ollo69 Yes, it works for a while anyway. Mine sometimes works for days, then stops until restarting HA.

**Comment by elenril2** [comment]
In my case it also started working correctly. I think after the last integration update.

**Comment by tismofied** [comment]
> Did you check for new TOS in LG mobile app?

I wonder why they keep updating their TSOs. This is the second time I had to redownload the app and accept the terms this month
