### ISSUE TITLE
The 'pycountry' distribution was not found and is required by the application

### ISSUE THREAD

**Issue by skinkie** [ollo69/ha-smartthinq-sensors#411]
**Describe the bug**
```
2022-12-01 23:14:23.180 ERROR (MainThread) [homeassistant.loader] Unexpected exception importing platform custom_components.smartthinq_sensors.config_flow
Traceback (most recent call last):
  File "/home/skinkie/.local/lib/python3.10/site-packages/homeassistant/loader.py", line 722, in get_platform
    cache[full_name] = self._import_platform(platform_name)
  File "/home/skinkie/.local/lib/python3.10/site-packages/homeassistant/loader.py", line 739, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/skinkie/.homeassistant/custom_components/smartthinq_sensors/config_flow.py", line 5, in <module>
    from pycountry import countries as py_countries, languages as py_languages
  File "/home/skinkie/.homeassistant/deps/lib/python3.10/site-packages/pycountry/__init__.py", line 13, in <module>
    __version__ = pkg_resources.get_distribution("pycountry").version
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 478, in get_distribution
    dist = get_provider(dist)
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 354, in get_provider
    return working_set.find(moduleOrReq) or require(str(moduleOrReq))[0]
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 909, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 795, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'pycountry' distribution was not found and is required by the application
```
```
2022-12-01 23:17:13.748 ERROR (MainThread) [homeassistant.loader] Unexpected exception importing platform custom_components.smartthinq_sensors.config_flow
Traceback (most recent call last):
  File "/home/skinkie/.local/lib/python3.10/site-packages/homeassistant/loader.py", line 722, in get_platform
    cache[full_name] = self._import_platform(platform_name)
  File "/home/skinkie/.local/lib/python3.10/site-packages/homeassistant/loader.py", line 739, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/skinkie/.homeassistant/custom_components/smartthinq_sensors/config_flow.py", line 5, in <module>
    from pycountry import countries as py_countries, languages as py_languages
  File "/home/skinkie/.homeassistant/deps/lib/python3.10/site-packages/pycountry/__init__.py", line 31, in <module>
    class ExistingCountries(pycountry.db.Database):
AttributeError: partially initialized module 'pycountry' has no attribute 'db' (most likely due to a circular import)
2022-12-01 23:17:13.754 ERROR (MainThread) [homeassistant.config_entries] Error occurred loading configuration flow for integration smartthinq_sensors: Exception importing custom_components.smartthinq_sensors.config_flow
```

**Environment details:**
 - Environment (HASSIO, Raspbian, etc): Alpine Linux
 - Home Assistant version installed: 
 - Component version installed: 
 - Last know working version:
 - LG device type and model with issue:
 - LG devices connected (list):

**Output of HA logs**
Paste the relavant output of the HA log here.

```

```

**Additional context**

**Comment by skinkie** [comment]
A few restarts resolved the problem.
