### ISSUE TITLE
Duct zone control failed

### ISSUE THREAD

**Issue by xleonx90** [ollo69/ha-smartthinq-sensors#421]
After upgrading to 0.25, an error occurs, everything works, but it pours in the logs.

Logger: custom_components.smartthinq_sensors.wideq.ac
Source: custom_components/smartthinq_sensors/wideq/core_async.py:346
Integration: SmartThinQ LGE Sensors (documentation, issues)
First occurred: 19:36:32 (4 occurrences)
Last logged: 19:38:32

Duct zone control failed
Traceback (most recent call last):
  File "/config/custom_components/smartthinq_sensors/wideq/ac.py", line 791, in poll
    await self.update_duct_zones()
  File "/config/custom_components/smartthinq_sensors/wideq/ac.py", line 374, in update_duct_zones
    states = await self._get_duct_zones()
  File "/config/custom_components/smartthinq_sensors/wideq/ac.py", line 431, in _get_duct_zones
    zones = await self._get_config(DUCT_ZONE_V1)
  File "/config/custom_components/smartthinq_sensors/wideq/device.py", line 556, in _get_config
    data = await self._client.session.get_device_config(self._device_info.id, key)
  File "/config/custom_components/smartthinq_sensors/wideq/core_async.py", line 1080, in get_device_config
    res = await self.post(
  File "/config/custom_components/smartthinq_sensors/wideq/core_async.py", line 888, in post
    return await self._auth.gateway.core.lgedm2_post(
  File "/config/custom_components/smartthinq_sensors/wideq/core_async.py", line 321, in lgedm2_post
    return self._manage_lge_result(out, is_api_v2)
  File "/config/custom_components/smartthinq_sensors/wideq/core_async.py", line 346, in _manage_lge_result
    raise API2_ERRORS[code]()
custom_components.smartthinq_sensors.wideq.core_exceptions.FailedRequestError

**Comment by ollo69** [comment]
Does your device support duct zones? Are you sure that this was not happening before?

**Comment by xleonx90** [comment]
air conditioner B07TS. one zone. Previously, the error was not observed. But everything works fine.

**Comment by ollo69** [comment]
Please, can you attach diagnostics? Nothing changed at that point, so I do not understand why you have this error.

**Comment by xleonx90** [comment]
The error is not repeated yet. but the diagnostic files are attached. Two air conditioners one api v1 the second api v2
[smartthinq_sensors-27ed86ef5c9035ebb5d7f9ee0b3c2bac-Детская-2651618780d21378212a8784e0579799.json (1).txt](https://github.com/ollo69/ha-smartthinq-sensors/files/10196285/smartthinq_sensors-27ed86ef5c9035ebb5d7f9ee0b3c2bac-.-2651618780d21378212a8784e0579799.json.1.txt)
[smartthinq_sensors-27ed86ef5c9035ebb5d7f9ee0b3c2bac-Спальня-26811702418a031406715c21e9e75c10.json.txt](https://github.com/ollo69/ha-smartthinq-sensors/files/10196286/smartthinq_sensors-27ed86ef5c9035ebb5d7f9ee0b3c2bac-.-26811702418a031406715c21e9e75c10.json.txt)

**Comment by xleonx90** [comment]
In general, the error occurs when I control the air conditioner 
(api v1) from the LG application.  The integration can't get control of the air conditioner for a while and accordingly I get this error and several others.
