### ISSUE TITLE
Cant seem to connect to Smart tinQ server

### ISSUE THREAD

**Issue by Ac0ps** [ollo69/ha-smartthinq-sensors#432]
**Describe the bug**
When i try to log into the integration service i get connection errors. 

I think the log file says enough to the experts?

Please help me resolve this issue

Error retrieving login URL from ThinQ
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 986, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 1089, in create_connection
    transport, protocol = await self._create_connection_transport(
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 1119, in _create_connection_transport
    await waiter
  File "/usr/local/lib/python3.10/asyncio/sslproto.py", line 534, in data_received
    ssldata, appdata = self._sslpipe.feed_ssldata(data)
  File "/usr/local/lib/python3.10/asyncio/sslproto.py", line 188, in feed_ssldata
    self._sslobj.do_handshake()
  File "/usr/local/lib/python3.10/ssl.py", line 975, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate is not yet valid (_ssl.c:997)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/smartthinq_sensors/__init__.py", line 102, in get_login_url
    return await ClientAsync.get_oauth_url(
  File "/config/custom_components/smartthinq_sensors/wideq/core_async.py", line 1330, in get_oauth_url
    gateway = await Gateway.discover(
  File "/config/custom_components/smartthinq_sensors/wideq/core_async.py", line 661, in discover
    gw_info = await core.gateway_info()
  File "/config/custom_components/smartthinq_sensors/wideq/core_async.py", line 354, in gateway_info
    return await self.thinq2_get(V2_GATEWAY_URL)
  File "/config/custom_components/smartthinq_sensors/wideq/core_async.py", line 269, in thinq2_get
    async with self._get_session().get(
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client.py", line 1138, in __aenter__
    self._resp = await self._coro
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client.py", line 535, in _request
    conn = await self._connector.connect(
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 542, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 907, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 1175, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 988, in _wrap_create_connection
    raise ClientConnectorCertificateError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorCertificateError: Cannot connect to host route.lgthinq.com:46030 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate is not yet valid (_ssl.c:997)')

**Comment by ollo69** [comment]
> I think the log file says enough to the experts?

No, it's not. May be exists an issue template for some reason? And, by the way, I assumed that you read [readme](https://github.com/ollo69/ha-smartthinq-sensors/blob/master/README.md) with attention before posting this issue.

**Comment by Ac0ps** [comment]
Hi Ollo,

First thanks for you quick reply and sorry for the bad problem description. Yes i read the readme and this forum to try to find a fix for this problem.
I downloaded the app from HACS, restarted HA and made a new account to wich i connected the device.

I just somehow cant find away to log in via the "devices and services"  (if it is called this way) tab in HA.
tried rebooting couple of times more.

**Comment by ollo69** [comment]
Looks like a certificate problem, but because I don't have detail of your environment I cannot provide more info. Update HA to last version and update your OS. Check that date time and time zone are correct, if not solve start providing details requested by issue template.

**Comment by Ac0ps** [comment]
Hi Ollo,

I think you can close this thread, after a full power cycle of the HA host and running the software update for HA i can now log into SmartTinQ. Thanks for the quick reply
