### ISSUE TITLE
Error executing the service

### ISSUE THREAD

**Issue by dukicn** [ollo69/ha-smartthinq-sensors#440]
I use the integration to automatically start and stop my heat pump LG Air To Water Heat Pump HM161M U33. After the recent upgrades, I can control both the heating / cooling and hot water. However, after the added functionality for hot water, I get periodic errors when running automations. Automations for hot water is new, but the automation for heating and cooling was working without any issues for month. Now, they both sporadically failed with the same error. On average, they fail every second time with the error:

Stopped because an error was encountered at 20 December 2022 at 06:00:03 (runtime: 3.54 seconds)
{'data': ''}

Fow now, I made a workaround by using repeat - until loop with 30 seconds delay, but I still see that sometimes it takes several retries until it succeeds.

I am running the service calls:

- service: climate.set_hvac_mode
  data:
    hvac_mode: "{{ states('input_select.climate_mode_master') | lower }}"
  target:
    entity_id: climate.toplinska_pumpa

and

- service: water_heater.set_operation_mode
  data:
    operation_mode: "off"
  target:
    entity_id: water_heater.toplinska_pumpa_water_heater

**Environment details:**
 - Environment (HASSIO, Raspbian, etc): dietpi
 - Home Assistant version installed: 2022.12.3
 - Component version installed: 0.26.1
 - Last know working version:
 - LG device type and model with issue: LG Air To Water Heat Pump HM161M U33
 - LG devices connected (list):

**Output of HA logs**
Paste the relavant output of the HA log here.

```
Stopped because an error was encountered at 20 December 2022 at 06:00:03 (runtime: 3.54 seconds)
{'data': ''}
```

**Comment by ollo69** [comment]
Are this 2 commands run at the same moment? Did you try to remove the WH command and see if the other alone works properly?

**Comment by dukicn** [comment]
Yes. They are part of different automations, but they are both scheduled to run at the same time. The heating / cooling command worked without any issues for months before I introduced water heater. How much time difference should I put between them?

**Comment by ollo69** [comment]
Not sure if this works, it's just an idea. I would suggest a couple of minutes between the 2 command.

**Comment by dukicn** [comment]
@ollo69 , tried with 5 min difference, but still the same issue occur. Eventually it goes through since I have a repeat loop with 10s delay (for example, this morning it took 3 retries). When it fails, I get this error in home-assistant logs:

2022-12-20 06:00:03.969 ERROR (MainThread) [homeassistant.components.automation.climate_auto_scheduler_master] Climate - Auto Master [Schedule]: Error executing script. Unexpected error for choose at pos 1: {'data': ''}
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 451, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 896, in _async_choose_step
    await self._async_run_script(script)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1029, in _async_run_script
    await self._async_run_long_action(
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 648, in _async_run_long_action
    long_task.result()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1524, in async_run
    await asyncio.shield(run.async_run())
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 409, in async_run
    await self._async_step(log_exceptions=False)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 453, in _async_step
    self._handle_exception(
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 476, in _handle_exception
    raise exception
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 451, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 684, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1745, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1782, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 213, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 678, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 943, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 715, in _handle_entity_call
    await result
  File "/config/custom_components/smartthinq_sensors/climate.py", line 288, in async_set_hvac_mode
    await self._device.power(True)
  File "/config/custom_components/smartthinq_sensors/wideq/ac.py", line 687, in power
    await self.set(keys[0], keys[1], key=keys[2], value=op_value)
  File "/config/custom_components/smartthinq_sensors/wideq/ac.py", line 842, in set
    await super().set(
  File "/config/custom_components/smartthinq_sensors/wideq/device.py", line 545, in set
    await self._set_control(
  File "/config/custom_components/smartthinq_sensors/wideq/device.py", line 506, in _set_control
    await self._client.session.set_device_v2_controls(
  File "/config/custom_components/smartthinq_sensors/wideq/core_async.py", line 1075, in set_device_v2_controls
    res = await self.post2(cmd_path, payload)
  File "/config/custom_components/smartthinq_sensors/wideq/core_async.py", line 912, in post2
    return await self._auth.gateway.core.lgedm2_post(
  File "/config/custom_components/smartthinq_sensors/wideq/core_async.py", line 321, in lgedm2_post
    return self._manage_lge_result(out, is_api_v2)
  File "/config/custom_components/smartthinq_sensors/wideq/core_async.py", line 334, in _manage_lge_result
    raise exc.APIError(code, message)
custom_components.smartthinq_sensors.wideq.core_exceptions.APIError: {'data': ''}

**Comment by dukicn** [comment]
Here it is
[config_entry-smartthinq_sensors-cd64a77aab486b55ae97b8ae4105024f.json.txt](https://github.com/ollo69/ha-smartthinq-sensors/files/10278508/config_entry-smartthinq_sensors-cd64a77aab486b55ae97b8ae4105024f.json.txt)

**Comment by ollo69** [comment]
I do not found any reason for this specific error, looks like a problem at LG site. This is quite similar to issue #443, did you try to just restart your device or reconnect it?

**Comment by dukicn** [comment]
I did restart the device, didn't reconnect it to the service. Haven't seen any errors in the last 3 days but it was happening sporadically so can't determine if this fixed it or not. Thanks for the help, if you didn't find any issues in your side, it has to be lg service somehow.

**Comment by dukicn** [comment]
I did restart the device, didn't reconnect it to the service. Haven't seen any errors in the last 3 days but it was happening sporadically so can't determine if this fixed it or not. Thanks for the help, if you didn't find any issues in your side, it has to be lg service somehow.

**Comment by tbclark3** [comment]
I'm seeing a similar problem (error messages quoted below). I have 4 LG thinq devices.  I use sensors to determine when the hot water circulator pump needs to run. I am not sending any commands to the appliances.  At the time of the failure, I was monitoring two washer sensors and one dishwasher sensor. I did not discover the failure for several hours, but when I restarted homeassistant, the sensors updated normally.

2023-02-16 20:14:34.296 WARNING (MainThread) [custom_components.smartthinq_sensors.wideq.device] Unexpected error while updating device status - Device: Washer
Traceback (most recent call last):
  File "/config/custom_components/smartthinq_sensors/wideq/device.py", line 160, in refresh
    state = await self.poll(query_device)
  File "/config/custom_components/smartthinq_sensors/wideq/device.py", line 289, in poll
    return await self._poll_v2(query_device)
  File "/config/custom_components/smartthinq_sensors/wideq/device.py", line 332, in _poll_v2
    await self._client.refresh_devices()
  File "/config/custom_components/smartthinq_sensors/wideq/core_async.py", line 1346, in refresh_devices
    await self._load_devices(True)
  File "/config/custom_components/smartthinq_sensors/wideq/core_async.py", line 1273, in _load_devices
    new_devices = await self._session.get_devices()
  File "/config/custom_components/smartthinq_sensors/wideq/core_async.py", line 1053, in get_devices
    dashboard = await self.get2("service/application/dashboard")
  File "/config/custom_components/smartthinq_sensors/wideq/core_async.py", line 1042, in get2
    return await self._auth.gateway.core.thinq2_get(
  File "/config/custom_components/smartthinq_sensors/wideq/core_async.py", line 304, in thinq2_get
    res = self._manage_lge_result(out, True)
  File "/config/custom_components/smartthinq_sensors/wideq/core_async.py", line 350, in _manage_lge_result
    raise exc.APIError(message, code)
custom_components.smartthinq_sensors.wideq.core_exceptions.APIError: 9995 -

**Comment by Xlinx64** [comment]
I also have the same api error code 9995.

Traceback (most recent call last):
  File "/config/custom_components/smartthinq_sensors/wideq/device.py", line 154, in refresh
    state, retry = await self.poll(query_device)
  File "/config/custom_components/smartthinq_sensors/wideq/device.py", line 265, in poll
    return await self._poll_v2(query_device)
  File "/config/custom_components/smartthinq_sensors/wideq/device.py", line 311, in _poll_v2
    await self._client.refresh_devices()
  File "/config/custom_components/smartthinq_sensors/wideq/core_async.py", line 1346, in refresh_devices
    await self._load_devices(True)
  File "/config/custom_components/smartthinq_sensors/wideq/core_async.py", line 1273, in _load_devices
    new_devices = await self._session.get_devices()
  File "/config/custom_components/smartthinq_sensors/wideq/core_async.py", line 1053, in get_devices
    dashboard = await self.get2("service/application/dashboard")
  File "/config/custom_components/smartthinq_sensors/wideq/core_async.py", line 1042, in get2
    return await self._auth.gateway.core.thinq2_get(
  File "/config/custom_components/smartthinq_sensors/wideq/core_async.py", line 304, in thinq2_get
    res = self._manage_lge_result(out, True)
  File "/config/custom_components/smartthinq_sensors/wideq/core_async.py", line 350, in _manage_lge_result
    raise exc.APIError(message, code)
custom_components.smartthinq_sensors.wideq.core_exceptions.APIError: 9995 -
