### ISSUE TITLE
Error executing service: <ServiceCall climate.set_temperature

### ISSUE THREAD

**Issue by DeadCo0l** [ollo69/ha-smartthinq-sensors#443]
Hi!

For the last couple of weeks I have been getting the following error message in the log. "Climate: Set temperature" doesn't run properly. I get this error in half of the cases when I want to set the temperature
It worked perfectly for two years but now I don't know what could be the problem. I tried rolling back the versions up to 25.0, but it's still not good.

Pls help me :)

**Environment details:**
 - Environment (HASSIO, Raspbian, etc): HASSIO
 - Home Assistant version installed: 2022.12.8
 - Component version installed: 26.1
 - Last know working version: - ( I also tried with version 2.5, but same error)
 - LG device type and model with issue: LG air conditioner
 - LG devices connected (list):

Log:

This error originated from a custom integration.

Logger: homeassistant.core
Source: custom_components/smartthinq_sensors/wideq/core_async.py:348
Integration: SmartThinQ LGE Sensors (documentation, issues)
First occurred: 4:40:30 PM (1 occurrences)
Last logged: 4:40:30 PM

Error executing service: <ServiceCall climate.set_temperature (c:01GMZT8TXYNYWEJ63YD5KXVYFZ): temperature=22.0, hvac_mode=heat, entity_id=['climate.nappali_klima']>
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/core.py", line 1763, in catch_exceptions
    await coro_or_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1782, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 213, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 678, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 943, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 715, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 613, in async_service_temperature_set
    await entity.async_set_temperature(**kwargs)
  File "/config/custom_components/smartthinq_sensors/climate.py", line 351, in async_set_temperature
    await self.async_set_hvac_mode(HVACMode(hvac_mode))
  File "/config/custom_components/smartthinq_sensors/climate.py", line 289, in async_set_hvac_mode
    await self._device.set_op_mode(operation_mode)
  File "/config/custom_components/smartthinq_sensors/wideq/ac.py", line 695, in set_op_mode
    await self.set(keys[0], keys[1], key=keys[2], value=mode_value)
  File "/config/custom_components/smartthinq_sensors/wideq/ac.py", line 842, in set
    await super().set(
  File "/config/custom_components/smartthinq_sensors/wideq/device.py", line 563, in set
    await self._set_control(
  File "/config/custom_components/smartthinq_sensors/wideq/device.py", line 514, in _set_control
    await self._client.session.set_device_controls(
  File "/config/custom_components/smartthinq_sensors/wideq/core_async.py", line 1043, in set_device_controls
    res = await self.post("rti/rtiControl", payload)
  File "/config/custom_components/smartthinq_sensors/wideq/core_async.py", line 896, in post
    return await self._auth.gateway.core.lgedm2_post(
  File "/config/custom_components/smartthinq_sensors/wideq/core_async.py", line 321, in lgedm2_post
    return self._manage_lge_result(out, is_api_v2)
  File "/config/custom_components/smartthinq_sensors/wideq/core_async.py", line 348, in _manage_lge_result
    raise exc.APIError(code, message)
custom_components.smartthinq_sensors.wideq.core_exceptions.APIError: 제품 응답 지연

-----------------------------------------------------------------------------------------------------------------------

And the other log:

Logger: homeassistant
Source: helpers/temperature.py:24
First occurred: 11:33:39 AM (2 occurrences)
Last logged: 11:34:14 AM

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 168, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 316, in _async_refresh
    self.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 121, in async_update_listeners
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 381, in _handle_coordinator_update
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 545, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 585, in _async_write_ha_state
    attr.update(self.state_attributes or {})
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 295, in state_attributes
    ATTR_CURRENT_TEMPERATURE: show_temp(
  File "/usr/src/homeassistant/homeassistant/helpers/temperature.py", line 24, in display_temp
    raise TypeError(f"Temperature is not a number: {temperature}")
TypeError: Temperature is not a number: -

--------------------------------------------------------------------------------------------------
This error originated from a custom integration.

Logger: custom_components.smartthinq_sensors.wideq.device
Source: custom_components/smartthinq_sensors/wideq/device.py:685
Integration: SmartThinQ LGE Sensors (documentation, issues)
First occurred: 11:33:39 AM (1 occurrences)
Last logged: 11:33:39 AM

Connection to ThinQ failed. Timeout error - Device: Nappali klíma

--------------------------------------------------------------------------------------------------
This error originated from a custom integration.

Logger: custom_components.smartthinq_sensors
Source: custom_components/smartthinq_sensors/__init__.py:442
Integration: SmartThinQ LGE Sensors (documentation, issues)
First occurred: 11:33:39 AM (1 occurrences)
Last logged: 11:33:39 AM

Status for device Nappali klíma was reset because disconnected or unreachable

[LG_ThinQ_diag.json.txt](https://github.com/ollo69/ha-smartthinq-sensors/files/10296125/LG_ThinQ_diag.json.txt)

**Comment by DeadCo0l** [comment]
I think this issu by the climate. I reset the wifi ad restart the AC and now working fine... Sorry for the case!
