### ISSUE TITLE
Integration suddenly not working

### ISSUE THREAD

**Issue by thoompje** [ollo69/ha-smartthinq-sensors#451]
**Describe the bug**
If possible attach the JSON info file for your devices.

**Expected behavior**
If applicable, a clear and concise description of what you expected to happen.

**Screenshots**
![image](https://user-images.githubusercontent.com/37865789/209653841-3f703246-a51d-47aa-b4d4-2332eee6ef1d.png)

**Environment details:**
 - Environment (HASSIO, Raspbian, etc):
 - Home Assistant version installed:
 - Component version installed:
 - Last know working version:
 - LG device type and model with issue:
 - LG devices connected (list):

**Output of HA logs**
Paste the relavant output of the HA log here.

Retrying setup: ThinQ platform not ready

2022-12-27 11:32:19.099 WARNING (MainThread) [homeassistant.config_entries] Config entry 'LGE Devices' for smartthinq_sensors integration not ready yet: ThinQ platform not ready; Retrying in background

**Additional context**

**Comment by ollo69** [comment]
May be a temporary LG service down or there are new TOS to accept in mobile application.

**Comment by thoompje** [comment]
No one else who has this problem???

**Comment by ollo69** [comment]
@thoompje,

Please check you log for additional message. Based on information provided I can only suppose a problem related to LG, but if there are others errors in the log I can better investigate.

**Comment by thoompje** [comment]
> @thoompje,
> 
> Please check you log for additional message. Based on information provided I can only suppose a problem related to LG, but if there are others errors in the log I can better investigate.

Hello,

thanks for answering, i have debug log enabled but the only thing what i can see in the logs:

2022-12-27 16:15:29.100 ERROR (MainThread) [homeassistant] Error doing job: Unclosed client session
2022-12-27 16:15:29.103 ERROR (MainThread) [homeassistant] Error doing job: Unclosed connector
2022-12-27 16:15:49.099 WARNING (MainThread) [homeassistant.config_entries] Config entry 'LGE Devices' for smartthinq_sensors integration not ready yet: ThinQ platform not ready; Retrying in background
2022-12-27 16:15:49.113 ERROR (MainThread) [homeassistant] Error doing job: Unclosed client session
2022-12-27 16:15:49.117 ERROR (MainThread) [homeassistant] Error doing job: Unclosed connector

**Comment by ollo69** [comment]
I don't see any specific error, really seems a problem in LG. Did you check your mobile application? Everything is working there?

**Comment by thoompje** [comment]
> I don't see any specific error, really seems a problem in LG. Did you check your mobile application? Everything is working there?

Don't see any errors in the app, everything is working fine. Is there an workaround or things to try?

**Comment by ollo69** [comment]
Woulb be useful if you could enable debug and provide log. Or you could just try to reconfigure the integration.

**Comment by thoompje** [comment]
> Woulb be useful if you could enable debug and provide log. Or you could just try to reconfigure the integration. 

Many thanks for replying! I enabled debug logging but there is no debug log. I deleted the intergration and added it again, but no luck see screenshot.

![image](https://user-images.githubusercontent.com/37865789/209705355-854b6cc9-acf8-4094-bd89-087250987a6d.jpeg)

**Comment by ollo69** [comment]
How do you enable the debug log?

**Comment by thoompje** [comment]
> How do you enable the debug log? 

I enabled the debug like this
![image](https://user-images.githubusercontent.com/37865789/209707906-3b7d438b-8a10-4711-b378-e817ad106c4d.jpeg)

**Comment by modem** [comment]
Also failing for me since last update. I see this log
`Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/smartthinq_sensors/wideq/core_async.py:345
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 23:29:23 (5 occurrences)
Last logged: 23:33:41

[546951289568]
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 200, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1745, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1782, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 213, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 678, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 943, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 715, in _handle_entity_call
    await result
  File "/config/custom_components/smartthinq_sensors/climate.py", line 278, in async_set_hvac_mode
    await self._device.power(False)
  File "/config/custom_components/smartthinq_sensors/wideq/ac.py", line 704, in power
    await self.set(keys[0], keys[1], key=keys[2], value=op_value)
  File "/config/custom_components/smartthinq_sensors/wideq/ac.py", line 859, in set
    await super().set(
  File "/config/custom_components/smartthinq_sensors/wideq/device.py", line 551, in set
    await self._set_control(
  File "/config/custom_components/smartthinq_sensors/wideq/device.py", line 512, in _set_control
    await self._client.session.set_device_v2_controls(
  File "/config/custom_components/smartthinq_sensors/wideq/core_async.py", line 1163, in set_device_v2_controls
    res = await self.post2(cmd_path, payload)
  File "/config/custom_components/smartthinq_sensors/wideq/core_async.py", line 1000, in post2
    return await self._auth.gateway.core.lgedm2_post(
  File "/config/custom_components/smartthinq_sensors/wideq/core_async.py", line 334, in lgedm2_post
    return self._manage_lge_result(out, is_api_v2)
  File "/config/custom_components/smartthinq_sensors/wideq/core_async.py", line 345, in _manage_lge_result
    raise API2_ERRORS[code]()
custom_components.smartthinq_sensors.wideq.core_exceptions.NotLoggedInError
`

**Comment by modem** [comment]
Think I solved, disabled the integration, restarted HA and re-enabled it, then it started to work, at least for now. Maybe the crash condition has not been met yet.

**Comment by thoompje** [comment]
> Think I solved, disabled the integration, restarted HA and re-enabled it, then it started to work, at least for now. Maybe the crash condition has not been met yet.

I disabled it and enabled it again, but no luck. Also de deletion and adding again no luck. Nothing is working at all. What can I do more to investigate the issue and solve it at the end? :)

**Comment by thoompje** [comment]
@modem The most strange thing is when i going to add the integration again it says: Success! 

![image](https://user-images.githubusercontent.com/37865789/209782787-79d52eef-697f-4171-95fc-900bfdd39cd4.png)

What i also did this morning is redownload from hacs the repository and restarted home assistant and trying to add it again. Same result. Also with 1.26.1 and 1.27.1.

Hopefully anyone has an solution for this, we can't control the AC's now from Home Assistant

**Comment by thoompje** [comment]
We can close this one, found it! In the core_async.py i searched for the OAUTH url

`OAUTH_REDIRECT_URI = f"https://kr.m.lgaccount.com/{OAUTH_REDIRECT_PATH}"`

Suddenly my Unifi dream machine blocked this URL because i am using country control, i changed nothing so its really strange that it suddenly stopped working. I added South Korea to the allow list temporary so its working again.

**Comment by ollo69** [comment]
This is interesting, also because this url should not be used anymore with last release.
@thoompje, can you confirm that you are using last release?

**Comment by thoompje** [comment]
> This is interesting, also because this url should not be used anymore with last release. @thoompje, can you confirm that you are using last release?

Really interesting then. I allowed South Korea on the Unifi and directly after it, it started working again.

**Comment by ollo69** [comment]
I think that there are some URL returned by the API that refer to KR, not that specific URL in the constant. But this is really a good catch, I should add some comment about this in readme.
Thanks,👍

**Comment by thoompje** [comment]
> I think that there are some URL returned by the API that refer to KR, not that specific URL in the constant. But this is really a good catch, I should add some comment about this in readme. Thanks,👍

Cheers, you welcome! Have a good NYE!
