### ISSUE TITLE
[BUG] 0.5.0  Washer shows an error state

### ISSUE THREAD

**Issue by jthunt** [ollo69/ha-smartthinq-sensors#48]
**Describe the bug**
After upgrading, washer shows in error state.  reinstalling old version resolves the issue.  But dryer is fine on both versions.

Washer Error State
Problem

But no error message.

**Expected behavior**
After upgrading, expected device to stay in non error state.

**Screenshots**

**Environment details:**
 - Environment (HASSIO, Raspbian, etc): VM HASSIO
 - Home Assistant version installed: 0.110.6
 - Component version installed: 0.5.0
 - Last know working version: 0.4.7
 - LG device type and model with issue: Washer - WT7300CV
 - LG devices connected (list): Washer and Dryer (DLE7300VE)

**Output of HA logs**
Paste the relevant output of the HA log here.
```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 217, in async_setup
    hass, self
  File "/usr/src/homeassistant/homeassistant/components/smartthings/__init__.py", line 120, in async_setup_entry
    entry.data[CONF_REFRESH_TOKEN],
  File "/usr/local/lib/python3.7/site-packages/pysmartthings/smartthings.py", line 210, in generate_tokens
    client_id, client_secret, refresh_token
  File "/usr/local/lib/python3.7/site-packages/pysmartthings/api.py", line 424, in generate_tokens
    raise APIInvalidGrant(data.get("error_description"))
pysmartthings.errors.APIInvalidGrant: Invalid refresh token: <TOKEN REMOVED>
```

**Additional context**

Odd that there is a refresh token error but Dryer still works fine?

Changing nothing between switching versions.  I don't re-setup the integration or anything.

**Comment by ollo69** [comment]
Can you please add a bitmap related to the error shown for the washer?

> Odd that there is a refresh token error but Dryer still works fine?
> Changing nothing between switching versions. I don't re-setup the integration or anything.
> After upgrading and having the issue, I did try to delete/re-setup the integration but that didn't resolve the issue either.

The token error in the log is related to a library called `pysmartthings`, this has nothing to do with this component and LG SmartThinQ (seems related to Samsung SmartThings). May be you have some other integration that is genarating this error?

**Comment by jthunt** [comment]
You are right.. unrelated error.  I got those mixed up..  No errors in the logs about the LG then.

See screenshots

![image](https://user-images.githubusercontent.com/7612193/84180443-1e8d4580-aa4d-11ea-84c5-63ea22954bba.png)

![image](https://user-images.githubusercontent.com/7612193/84180507-382e8d00-aa4d-11ea-8311-118628fb09b4.png)

**Comment by jthunt** [comment]
Now that I had a little more time to look around, I found the following logs (taken right after upgrading to 0.5.0 and restarting).  Reverting back to 0.4.7 shows the same logs.

Along with the error state with 0.5.0, I don't get any status updates (Washer job complete, etc).  But it all starts working again when I switch back to 0.4.7.  No configuration changes on my side.

```
2020-06-09 21:03:57 INFO (MainThread) [custom_components.smartthinq_sensors] SmartThinQ client connected.
2020-06-09 21:03:57 INFO (MainThread) [custom_components.smartthinq_sensors] Starting LGE ThinQ devices...
2020-06-09 21:03:57 INFO (SyncWorker_3) [custom_components.smartthinq_sensors.wideq.core_v2] Loading model info for Dryer. Model: RV13U6AM8W_D_US_WIFI, Url: https://objectstore.lgthinq.com/<TOKEN REMOVED>?Expires=1653783858&Signature=<SIG REMOVED>&Key-Pair-Id=<KEY REMOVED>
2020-06-09 21:03:57 INFO (MainThread) [custom_components.smartthinq_sensors] LGE Device added. Name: Dryer - Type: DRYER - Model: RV13U6AM8W_D_US_WIFI - Mac: <MAC REMOVED> - ID: <ID REMOVED>
2020-06-09 21:03:57 INFO (SyncWorker_10) [custom_components.smartthinq_sensors.wideq.core_v2] Loading model info for Washer. Model: T1789EFH_F, Url: https://objectstore.lgthinq.com/<TOKEN REMOVED>?Expires=1606597587&Signature=<SIG REMOVED>&Key-Pair-Id=<KEY REMOVED>
2020-06-09 21:04:00 INFO (MainThread) [custom_components.smartthinq_sensors] LGE Device added. Name: Washer - Type: WASHER - Model: T1789EFH_F - Mac: <MAC REMOVED> - ID: <ID REMOVED>
2020-06-09 21:04:00 INFO (MainThread) [custom_components.smartthinq_sensors] Founds 2 LGE device(s)
2020-06-09 21:04:00 INFO (MainThread) [custom_components.smartthinq_sensors.sensor] Starting LGE ThinQ sensors...
```

**Comment by ollo69** [comment]
I will release shortly a new version with some fix. In any case should be usefull to have the json info related to your washer, the download url is in the log line that contain:
`oading model info for Washer. Model: T1789EFH_F, Url...`

I cannot download by myself because you remove some piece of the url, can you download and attach the file to this thread?

Thanks.
