### ISSUE TITLE
No devices -- SSL Failure

### ISSUE THREAD

**Issue by ifixrjs** [ollo69/ha-smartthinq-sensors#49]
I'm having a problem with this plugin.  I recently upgraded my raspberry pi and python to the latest versions and now I cannot access the LG devices.  My error log is as follows.

I'm running python 3.8
openssl 1.1.1d
The latest home assistant and the latest ha-smartthinq-sensors

Any help would be greatly appreciated.  I have a feeling I need to run an older version openssl, but I'm not technically involved enough to know how to change my version.  Thanks for any and all help.

2020-06-10 12:22:46 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for smartthinq_sensors which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
2020-06-10 12:22:46 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
2020-06-10 12:22:57 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry LGE Devices for smartthinq_sensors
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.8/site-packages/urllib3/contrib/pyopenssl.py", line 488, in wrap_socket
    cnx.do_handshake()
  File "/srv/homeassistant/lib/python3.8/site-packages/OpenSSL/SSL.py", line 1934, in do_handshake
    self._raise_ssl_error(self._ssl, result)
  File "/srv/homeassistant/lib/python3.8/site-packages/OpenSSL/SSL.py", line 1671, in _raise_ssl_error
    _raise_current_error()
  File "/srv/homeassistant/lib/python3.8/site-packages/OpenSSL/_util.py", line 54, in exception_from_error_queue
    raise exception_type(errors)
OpenSSL.SSL.Error: [('SSL routines', 'ssl_choose_client_version', 'unsupported protocol')]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.8/site-packages/urllib3/connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "/srv/homeassistant/lib/python3.8/site-packages/urllib3/connectionpool.py", line 381, in _make_request
    self._validate_conn(conn)
  File "/srv/homeassistant/lib/python3.8/site-packages/urllib3/connectionpool.py", line 976, in _validate_conn
    conn.connect()
  File "/srv/homeassistant/lib/python3.8/site-packages/urllib3/connection.py", line 361, in connect
    self.sock = ssl_wrap_socket(
  File "/srv/homeassistant/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 377, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/srv/homeassistant/lib/python3.8/site-packages/urllib3/contrib/pyopenssl.py", line 494, in wrap_socket
    raise ssl.SSLError("bad handshake: %r" % e)
ssl.SSLError: ("bad handshake: Error([('SSL routines', 'ssl_choose_client_version', 'unsupported protocol')])",)

**Comment by ifixrjs** [comment]
During setup I choose 
US
en-US
I'm running latest version of rasbian.  Before the update everything was running fine.  However, I'm having problems with my home assistant base install right now, I broke it trying to troubleshoot this error.  I will probably have to remove and reinstall entirely.  I'll reinstall everything and let you know if I have the same error.

**Comment by ollo69** [comment]
Language must match your account registration so you cannot choose different option.
I wait for your feed-back after reinstall, remember to provide all log if you still have issue.

**Comment by ifixrjs** [comment]
I'm based in the US, products are US and registered us.
Location: US
Language: en-US
entered exactly as above, same log results, here they are after the fresh install (some items removed for privacy)

I copy the URL from the installer, brought me to an LG page where I enter my username and pass.  After I get a redirect to a URL with a blank page.  I copy the URL and place that in setup dialog.  After it tells me the item was added successfully.  Once added, no further sensors are there.

Log Details (ERROR)
Logger: homeassistant.config_entries
Source: custom_components/smartthinq_sensors/wideq/core_v2.py:749
First occurred: 7:23:08 PM (1 occurrences)
Last logged: 7:23:08 PM

Error setting up entry LGE Devices for smartthinq_sensors
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.8/site-packages/urllib3/contrib/pyopenssl.py", line 488, in wrap_socket
    cnx.do_handshake()
  File "/srv/homeassistant/lib/python3.8/site-packages/OpenSSL/SSL.py", line 1934, in do_handshake
    self._raise_ssl_error(self._ssl, result)
  File "/srv/homeassistant/lib/python3.8/site-packages/OpenSSL/SSL.py", line 1671, in _raise_ssl_error
    _raise_current_error()
  File "/srv/homeassistant/lib/python3.8/site-packages/OpenSSL/_util.py", line 54, in exception_from_error_queue
    raise exception_type(errors)
OpenSSL.SSL.Error: [('SSL routines', 'ssl_choose_client_version', 'unsupported protocol')]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.8/site-packages/urllib3/connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "/srv/homeassistant/lib/python3.8/site-packages/urllib3/connectionpool.py", line 381, in _make_request
    self._validate_conn(conn)
  File "/srv/homeassistant/lib/python3.8/site-packages/urllib3/connectionpool.py", line 976, in _validate_conn
    conn.connect()
  File "/srv/homeassistant/lib/python3.8/site-packages/urllib3/connection.py", line 361, in connect
    self.sock = ssl_wrap_socket(
  File "/srv/homeassistant/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 377, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/srv/homeassistant/lib/python3.8/site-packages/urllib3/contrib/pyopenssl.py", line 494, in wrap_socket
    raise ssl.SSLError("bad handshake: %r" % e)
ssl.SSLError: ("bad handshake: Error([('SSL routines', 'ssl_choose_client_version', 'unsupported protocol')])",)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/srv/homeassistant/lib/python3.8/site-packages/urllib3/connectionpool.py", line 724, in urlopen
    retries = retries.increment(
  File "/srv/homeassistant/lib/python3.8/site-packages/urllib3/util/retry.py", line 439, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='aic.lgthinq.com', port=46030): Max retries exceeded with url: /api/webContents/modelJSON?modelName=2REF11EIIFM__&countryCode=WW&contentsId=##############&authKey=thinq (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'ssl_choose_client_version', 'unsupported protocol')])")))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/config_entries.py", line 216, in async_setup
    result = await component.async_setup_entry(  # type: ignore
  File "/home/homeassistant/.homeassistant/custom_components/smartthinq_sensors/__init__.py", line 177, in async_setup_entry
    lge_devices = await lge_devices_setup(hass, client)
  File "/home/homeassistant/.homeassistant/custom_components/smartthinq_sensors/__init__.py", line 462, in lge_devices_setup
    result = await hass.async_add_executor_job(dev.init_device)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/homeassistant/.homeassistant/custom_components/smartthinq_sensors/__init__.py", line 295, in init_device
    if self._device.init_device_info():
  File "/home/homeassistant/.homeassistant/custom_components/smartthinq_sensors/wideq/device.py", line 723, in init_device_info
    self._model_data = self._client.model_url_info(
  File "/home/homeassistant/.homeassistant/custom_components/smartthinq_sensors/wideq/core_v2.py", line 776, in model_url_info
    self._model_url_info[url] = self._load_json_info(url)
  File "/home/homeassistant/.homeassistant/custom_components/smartthinq_sensors/wideq/core_v2.py", line 749, in _load_json_info
    return requests.get(info_url, timeout=DEFAULT_TIMEOUT).json()
  File "/srv/homeassistant/lib/python3.8/site-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/srv/homeassistant/lib/python3.8/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/srv/homeassistant/lib/python3.8/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/srv/homeassistant/lib/python3.8/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/srv/homeassistant/lib/python3.8/site-packages/requests/adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='aic.lgthinq.com', port=46030): Max retries exceeded with url: /api/webContents/modelJSON?modelName=2REF11EIIFM__&countryCode=WW&contentsId=#######&authKey=thinq (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'ssl_choose_client_version', 'unsupported protocol')])")))

**Comment by ollo69** [comment]
Ok, this mean that I need to upgrade my system and try there, hoping that same errors occur to me.
I can do this not before next w.e.
Exactly which version of Raspian do you install? How do you install HomeAssistant ?

**Comment by ifixrjs** [comment]
I'm running Rasbian version Buster (Linux raspberrypi 5.4.44-v7+)
I installed home assistant through the manual install in a venv
Home Assistant 0.111.0
Running the SmartThinq LG v 0.5.1

**Comment by ollo69** [comment]
Just finished now to make a test:
- download last raspian [image ](https://downloads.raspberrypi.org/raspios_lite_armhf_latest) and flashed on a new sd card
- Installed home-assistant in venv with [this procedure](https://www.home-assistant.io/docs/installation/raspberry-pi/)
- installed custom component and configured

Everything works without any issue. Do you follow the same step?

**Comment by ifixrjs** [comment]
Yes, exactly the same steps.  What version of open ssl are you running?  I'm running 1.1.1d
Maybe I am doing the setup wrong for the plugin.  Here is what I am doing.

Installed Via HACS (restart HASS)
Add LG SmartThinq Integration
Configure SmartThinq - Region: US Language: en-US
Copy URL from SmartThinq setup into new browser tab
Enter username and password when prompted (not a social media account)
Land on a blank page, copy the URL from blank page and paste back into SmartThinq setup
After that, setup successful

However the same error logs as before and no sensors shown.  Am I doing something wrong in the setup?

**Comment by ollo69** [comment]
OpenSSL is 1.1.1d also for me and the component installation procedure is correct.
What is not clear to me is the raspian and python version that you mention. Linux kernel for last raspian version is 4.19.118, python version is still 3.7. Are you sure you are using the same image of the link I posted?

**Comment by ifixrjs** [comment]
Python v 3.8
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian
ID_LIKE=debian

It's not a fresh flash because I have other things running on it, I recently did a do-release-upgrade to get to the latest version.

**Comment by ollo69** [comment]
Seems lot newer than last version officially available from raspberry site, are you sure you are not running a beta version?
Post here the exact update command that you run so that I can replicate.

**Comment by ifixrjs** [comment]
Modified /etc/apt/sources.list
Replaced old version with buster
```
sudo apt update
sudo apt dist-upgrade
```

updated home assistant with 

```
sudo -u homeassistant -H -s
source /srv/homeassistant/bin/activate
pip3 install --upgrade homeassistant
```

**Comment by ollo69** [comment]
Ok, so you was coming from a previous distribution, may be upgrade broke something.
In any case I'll try to update my buster image to see if additional update are available, I'll update you when finish.

**Comment by ifixrjs** [comment]
That is correct.  Also Im not sure why my kernel is 5.4.44 v7, when on the rasbian site the current kernel is 4.19.  I don't remember doing anything specific with that.

**Comment by ifixrjs** [comment]
Ok so I found something.  It might be because I apperantly have two versions of python installed?  I'm not sure if that is the problem or not.
```
whereis python
python: /usr/bin/python2.7-config /usr/bin/python3.7-config /usr/bin/python3.7 /usr/bin/python3.7m /usr/bin/python /usr/bin/python3.7m-config /usr/bin/python2.7 /usr/lib/python3.7 /usr/lib/python2.7 /etc/python3.7 /etc/python /etc/python2.7 /etc/python3.5 /usr/local/bin/python3.8 /usr/local/bin/python3.8-config /usr/local/lib/python3.8 /usr/local/lib/python3.7 /usr/local/lib/python2.7 /usr/include/python3.7 /usr/include/python3.7m /usr/include/python2.7 /usr/share/python /home/pi/bin/python /usr/share/man/man1/python.1.gz
```
I don't think this would cause the issue, but maybe? What do you think?

**Comment by ifixrjs** [comment]
I cloned a copy of wideQ and ran the example.py
Same errors.  I think this is an issue on my end and not your software.  I might just have to nuke my RasOS install and try again from scratch :(

**Comment by ollo69** [comment]
I think too, and I don't have python 3.8 at all:

`python: /usr/bin/python2.7 /usr/bin/python3.7-config /usr/bin/python3.7m /usr/bin/python3.7 /usr/bin/python3.7m-config /usr/bin/python /usr/lib/python2.7 /usr/lib/python3.7 /etc/python2.7 /etc/python3.7 /etc/python /usr/local/lib/python2.7 /usr/local/lib/python3.7 /usr/include/python3.7m /usr/include/python3.7 /usr/share/python /opt/zigbee2mqtt/bin/python /usr/share/man/man1/python.1.gz`

In any case I'll try to run update, but I don't think it will change my kernel to 5.x.
I think you istall some beta version, don't know exactly how.

**Comment by ifixrjs** [comment]
Entirely possible, thank you for your help.  I'll go ahead and close this as it seems to be an issue related only to me.

**Comment by ifixrjs** [comment]
So I downgraded my pi, running buster, with kernel 4.19, rebuilt the venv with python 3.7, still the same error.  Super frustrating.

**Comment by ollo69** [comment]
The only way I can try to help you is that you provide me your user and password for ThinQ and so I can test here in my env. 
If you want do this I suggest you to change your ThinQ password with a simple one, than you will set back your pwd when done.
Obviosly is up to you, I can give you my e-mail for sending this info.

**Comment by ifixrjs** [comment]
FIXED!!!!RESOLVED!!!!!!!!!!!!!SOLVED

Check out this -- https://github.com/sampsyo/wideq/issues/106
Modify the SSL conf located in 
/etc/ssl/openss.cnf

Modify the line MinProtocol = TLSv1.2 change to TLSv1.0

This worked for me.

**Comment by hmoffatt** [comment]
I also had this problem when originally testing wideq - https://github.com/sampsyo/wideq/issues/55. Some of the Samsung servers have TLS 1.2, some seem to only have 1.0. It depends on your region/language code which server is for you.
