### ISSUE TITLE
sensor.dryer is unavailable

### ISSUE THREAD

**Issue by frznfngrs** [ollo69/ha-smartthinq-sensors#491]
**Describe the bug**
sensor.dryer is unavailable.  everything else seems to be working okay

**Expected behavior**
Expecting a status other than unavailable.   Mostly so the custom card works.

**Screenshots**
<img width="365" alt="image" src="https://user-images.githubusercontent.com/19555532/218293868-4f00a6c2-a847-4696-a9fc-f6d5797e1e1a.png">

**Environment details:**
 - Hass on Docker
 - Home Assistant 2023.2.3
 - Component version installed:
 - Last know working version:
 - LG device type and model with issue: RV13D5JSD_D_US-Dryer (DRYER)
 - LG devices connected (list): RV13D5JSD_D_US-Dryer (DRYER), FAVTU21030-FL (WASHER)

**Output of HA logs**

Logger: homeassistant
Source: custom_components/smartthinq_sensors/device_helpers.py:148
Integration: SmartThinQ LGE Sensors (documentation, issues)
First occurred: 10:57:46 PM (7 occurrences)
Last logged: 11:00:48 PM

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 182, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 330, in _async_refresh
    self.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 135, in async_update_listeners
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 390, in _handle_coordinator_update
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 566, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 610, in _async_write_ha_state
    attr.update(self.extra_state_attributes or {})
  File "/config/custom_components/smartthinq_sensors/sensor.py", line 721, in extra_state_attributes
    ATTR_START_TIME: self._wrap_device.start_time,
  File "/config/custom_components/smartthinq_sensors/device_helpers.py", line 148, in start_time
    int(state.reservetime_hour)
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'

**Comment by ollo69** [comment]
This should be fixed in last release, please test and report result.

**Comment by frznfngrs** [comment]
Fixed that problem.  Thanks.   May be related, may be new problem.  


On attempting to power off appliance from integration.  Same for washer and dryer.    Appliance does not power off to be clear.

This error originated from a custom integration.

Logger: homeassistant.core
Source: custom_components/smartthinq_sensors/wideq/core_async.py:320
Integration: SmartThinQ LGE Sensors (documentation, issues)
First occurred: 10:42:36 AM (3 occurrences)
Last logged: 10:43:24 AM

Error executing service: <ServiceCall switch.turn_off (c:01GS3833AK6854QEZPR7SDQNBN): entity_id=['switch.dryer_power']>
Error executing service: <ServiceCall switch.turn_off (c:01GS383RZGT6ZYHEBVKGVRZKX7): entity_id=['switch.front_load_washer_power']>
Error executing service: <ServiceCall switch.turn_off (c:01GS384J4Q8YMN6YNE8TZ503Q5): entity_id=['switch.dryer_power']>
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/core.py", line 1805, in catch_exceptions
    await coro_or_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1824, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 213, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 680, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 968, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 720, in _handle_entity_call
    await result
  File "/config/custom_components/smartthinq_sensors/switch.py", line 263, in async_turn_off
    await self.entity_description.turn_off_fn(self._wrap_device)
  File "/config/custom_components/smartthinq_sensors/wideq/devices/washerDryer.py", line 238, in power_off
    await self.set(keys[0], keys[1], value=keys[2])
  File "/config/custom_components/smartthinq_sensors/wideq/devices/washerDryer.py", line 273, in set
    await super().set(
  File "/config/custom_components/smartthinq_sensors/wideq/device.py", line 539, in set
    await self._set_control(full_key, ctrl_path=ctrl_path)
  File "/config/custom_components/smartthinq_sensors/wideq/device.py", line 511, in _set_control
    await self._client.session.device_v2_controls(
  File "/config/custom_components/smartthinq_sensors/wideq/core_async.py", line 1183, in device_v2_controls
    res = await self.post2(cmd_path, payload)
  File "/config/custom_components/smartthinq_sensors/wideq/core_async.py", line 1020, in post2
    return await self._auth.gateway.core.lgedm2_post(
  File "/config/custom_components/smartthinq_sensors/wideq/core_async.py", line 320, in lgedm2_post
    async with self._get_session().post(
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client.py", line 1138, in __aenter__
    self._resp = await self._coro
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client.py", line 559, in _request
    await resp.start(conn)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client_reqrep.py", line 893, in start
    with self._timer:
  File "/usr/local/lib/python3.10/site-packages/aiohttp/helpers.py", line 721, in __exit__
    raise asyncio.TimeoutError from None
asyncio.exceptions.TimeoutError

**Comment by ollo69** [comment]
This is duplicated of #489, and I have no idea why this is happening. I close this because original issue is solved.

**Comment by frznfngrs** [comment]
Thanks
