### ISSUE TITLE
Unable to wake up LG front load washer

### ISSUE THREAD

**Issue by nefelodamon** [ollo69/ha-smartthinq-sensors#499]
**Describe the bug**
Whenever I set the washer to remote start, it will go to sleep after a while. Then when calling the wake up service from home assistant it will fail with an error in logs. The device then will power off.

**Expected behavior**
Device wakes up

**Screenshots**
N/A

**Environment details:**
 - Environment (HASSIO, Raspbian, etc): HASSIO
 - Home Assistant version installed: 2023.2.5
 - Component version installed: 0.31.2
 - Last know working version: not sure if it worked before with my setup
 - LG device type and model with issue: F_V7_Y___W.B_2QEUK-FL (WASHER) Firmware: clip_hna_v1.9.183
 - LG devices connected (list):
        RH90V9_WW-Dryer (DRYER) Firmware: clip_hna_v1.9.183
        F_V7_Y___W.B_2QEUK-FL (WASHER) Firmware: clip_hna_v1.9.183

**Output of HA logs**
Paste the relavant output of the HA log here.
[smartthinq_sensors-7d5a5403c7dc62afd8221b7c9fedef22-Zozo-4ec5a99edacc06b193d1b65540a161d7.json.txt](https://github.com/ollo69/ha-smartthinq-sensors/files/10756563/smartthinq_sensors-7d5a5403c7dc62afd8221b7c9fedef22-Zozo-4ec5a99edacc06b193d1b65540a161d7.json.txt)

```
This error originated from a custom integration.

Logger: homeassistant.core
Source: custom_components/smartthinq_sensors/wideq/core_async.py:320
Integration: SmartThinQ LGE Sensors (documentation, issues)
First occurred: 13:32:54 (1 occurrences)
Last logged: 13:32:54

Error executing service: <ServiceCall smartthinq_sensors.wake_up (c:01GSD6TKQX64VSWJN8FV4NY31J): device_id=['4ec5a99edacc06b193d1b65540a161d7']>
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/core.py", line 1805, in catch_exceptions
    await coro_or_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1824, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 795, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 680, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 968, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 720, in _handle_entity_call
    await result
  File "/config/custom_components/smartthinq_sensors/sensor.py", line 696, in async_wake_up
    await self._api.device.wake_up()
  File "/config/custom_components/smartthinq_sensors/wideq/devices/washerDryer.py", line 254, in wake_up
    await self.set(keys[0], keys[1], value=keys[2])
  File "/config/custom_components/smartthinq_sensors/wideq/devices/washerDryer.py", line 275, in set
    await super().set(
  File "/config/custom_components/smartthinq_sensors/wideq/device.py", line 540, in set
    await self._set_control(full_key, ctrl_path=ctrl_path)
  File "/config/custom_components/smartthinq_sensors/wideq/device.py", line 512, in _set_control
    await self._client.session.device_v2_controls(
  File "/config/custom_components/smartthinq_sensors/wideq/core_async.py", line 1183, in device_v2_controls
    res = await self.post2(cmd_path, payload)
  File "/config/custom_components/smartthinq_sensors/wideq/core_async.py", line 1020, in post2
    return await self._auth.gateway.core.lgedm2_post(
  File "/config/custom_components/smartthinq_sensors/wideq/core_async.py", line 320, in lgedm2_post
    async with self._get_session().post(
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client.py", line 1138, in __aenter__
    self._resp = await self._coro
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client.py", line 559, in _request
    await resp.start(conn)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client_reqrep.py", line 893, in start
    with self._timer:
  File "/usr/local/lib/python3.10/site-packages/aiohttp/helpers.py", line 721, in __exit__
    raise asyncio.TimeoutError from None
asyncio.exceptions.TimeoutError

```

**Additional context**

**Comment by alvarocarrera** [comment]
Same problem and same logs here.
My device is: F_V8_F___W.A__QEUK-FL (WASHER)
Firmware: clip_hna_v1.9.183

**Comment by ollo69** [comment]
Duplicated of #489. I close this, continue on other issue and provide all possible details.
