### ISSUE TITLE
Outdated endpoint causing failure to initialize?

### ISSUE THREAD

**Issue by jwfox5150** [ollo69/ha-smartthinq-sensors#508]
This integration has stopped working for me. Below is the relevant log output:

`aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host kic.lgthinq.com:46030 ssl:default [Connect call failed ('13.125.83.188', 46030)]`

This appears to be an outdated address, as it is down. Anyone else having this issue?

**Comment by mcnairsean** [comment]
The integration stopped working for me mid-day yesterday but with a different, possibly related error.
```
Logger: custom_components.smartthinq_sensors.wideq.device
Source: custom_components/smartthinq_sensors/wideq/core_async.py:347
Integration: SmartThinQ LGE Sensors ([documentation](https://github.com/ollo69/ha-smartthinq-sensors), [issues](https://github.com/ollo69/ha-smartthinq-sensors/issues))
First occurred: March 8, 2023 at 11:35:27 PM (1 occurrences)
Last logged: March 8, 2023 at 11:35:27 PM

Unexpected error while updating device status - Device: Dryer
Traceback (most recent call last):
  File "/config/custom_components/smartthinq_sensors/wideq/device.py", line 155, in refresh
    state = await self.poll(query_device)
  File "/config/custom_components/smartthinq_sensors/wideq/device.py", line 283, in poll
    return await self._poll_v2(query_device)
  File "/config/custom_components/smartthinq_sensors/wideq/device.py", line 326, in _poll_v2
    await self._client.refresh_devices()
  File "/config/custom_components/smartthinq_sensors/wideq/core_async.py", line 1342, in refresh_devices
    await self._load_devices(True)
  File "/config/custom_components/smartthinq_sensors/wideq/core_async.py", line 1269, in _load_devices
    new_devices = await self._session.get_devices()
  File "/config/custom_components/smartthinq_sensors/wideq/core_async.py", line 1050, in get_devices
    dashboard = await self.get2("service/application/dashboard")
  File "/config/custom_components/smartthinq_sensors/wideq/core_async.py", line 1039, in get2
    return await self._auth.gateway.core.thinq2_get(
  File "/config/custom_components/smartthinq_sensors/wideq/core_async.py", line 301, in thinq2_get
    res = self._manage_lge_result(out, True)
  File "/config/custom_components/smartthinq_sensors/wideq/core_async.py", line 347, in _manage_lge_result
    raise exc.APIError(code, message)
custom_components.smartthinq_sensors.wideq.core_exceptions.APIError
```

**Comment by btehan** [comment]
Looks like mine stopped a couple of days ago after working for a long time:

`2023-03-14 15:27:26.635 WARNING (MainThread) [custom_components.smartthinq_sensors.wideq.device] Unexpected error while updating device status - Device: WASHER
File "/config/custom_components/smartthinq_sensors/wideq/device.py", line 154, in refresh
File "/config/custom_components/smartthinq_sensors/wideq/device.py", line 264, in poll
File "/config/custom_components/smartthinq_sensors/wideq/device.py", line 273, in _poll_v1
File "/config/custom_components/smartthinq_sensors/wideq/core_async.py", line 1346, in refresh_devices
File "/config/custom_components/smartthinq_sensors/wideq/core_async.py", line 1273, in _load_devices
File "/config/custom_components/smartthinq_sensors/wideq/core_async.py", line 1053, in get_devices
File "/config/custom_components/smartthinq_sensors/wideq/core_async.py", line 1042, in get2
return await self._auth.gateway.core.thinq2_get(
File "/config/custom_components/smartthinq_sensors/wideq/core_async.py", line 304, in thinq2_get
File "/config/custom_components/smartthinq_sensors/wideq/core_async.py", line 350, in _manage_lge_result
custom_components.smartthinq_sensors.wideq.core_exceptions.APIError: 9995 -
2023-03-16 09:44:18.139 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry LGE Devices for smartthinq_sensors
File "/config/custom_components/smartthinq_sensors/__init__.py", line 288, in async_setup_entry
File "/config/custom_components/smartthinq_sensors/__init__.py", line 570, in lge_devices_setup
File "/config/custom_components/smartthinq_sensors/__init__.py", line 437, in init_device
File "/config/custom_components/smartthinq_sensors/__init__.py", line 460, in _create_coordinator
File "/config/custom_components/smartthinq_sensors/__init__.py", line 465, in _async_update
File "/config/custom_components/smartthinq_sensors/__init__.py", line 477, in _async_state_update
File "/config/custom_components/smartthinq_sensors/wideq/devices/washerDryer.py", line 339, in poll
File "/config/custom_components/smartthinq_sensors/wideq/device.py", line 698, in _device_poll
File "/config/custom_components/smartthinq_sensors/wideq/device.py", line 153, in refresh
File "/config/custom_components/smartthinq_sensors/wideq/device.py", line 109, in _refresh_auth`


I've tried reloading and removing/re-adding the integration multiple times today without success.  I've logged out of the android app and logged back in (using a LG account) and still didn't work after that.

**Comment by Codex-** [comment]
Experiencing the same, api changed?

**Comment by MnM001** [comment]
Similar issue here - new install = invalid credentials.
Tried everything (no new ToS to aacept in app, Use URL redirect doesnt work anymore) without success.

**Comment by b-haven** [comment]
Same issue here. Tried a couple different ways to get it to initialize

**Comment by b-haven** [comment]
so I got it to log in now, I removed this from the redirect url before pasting it back in as requested to do &oauth2_backend_url=https://us.lgeapi.com/

All my hvac units show and display the proper temperature, but now I get an error when I try to change their state from within home assistant.

Failed to call service climate/set_hvac_mode. 0011 - 등록되지 않은 모델입니다.

Google translate comes back with "This is an unregistered model"

**Comment by jwfox5150** [comment]
> so I got it to log in now, I removed this from the redirect url before pasting it back in as requested to do &oauth2_backend_url=https://us.lgeapi.com/

unfortunately I get an error when removing that snippet from the URL. when I paste the full URL, it configures successfully, but times out as stated above

**Comment by jwfox5150** [comment]
bumping to prevent stale closure. this is still an issue.

**Comment by b-haven** [comment]
FWIW, I ended up doing a fresh install of homeassistant so I could cut out all of the things that I don't use and were cluttering things up and everything works fine on a fresh install.
