### ISSUE TITLE
AC unexpected behaviour 

### ISSUE THREAD

**Issue by maxoss** [ollo69/ha-smartthinq-sensors#511]
**Describe the bug**
After updating LG Thinq app I experience some strange behavior of the integration. 
- Turning on AC with the integration will turn the AC but then the integration shows AC off after 30 sec
- No current temperature available anymore. 
- Not able to set temperature

**Screenshots**
![AC](https://user-images.githubusercontent.com/757822/227478110-990ab6c3-9002-42bc-bf1b-2a76ca0d4717.PNG)
![AC2](https://user-images.githubusercontent.com/757822/227478142-78315c73-a0af-4a87-848a-c0ba0533767e.PNG)

**Environment details:**
 - Environment (HASSIO, Raspbian, etc): HASSIO
 - Home Assistant version installed: 2023.3.5
 - Component version installed: v0.31.4
 - LQ Thinq app: 4.1.36011

**Output of HA logs**
Deze fout is ontstaan door een aangepaste integratie.

Logger: homeassistant.core
Source: custom_components/smartthinq_sensors/wideq/core_async.py:364
Integration: SmartThinQ LGE Sensors (documentation, issues)
First occurred: 08:09:29 (8 occurrences)
Last logged: 08:25:20

Error executing service: <ServiceCall climate.set_hvac_mode (c:01GW97V2YQTD14RMWKBBRYZEDZ): hvac_mode=heat, entity_id=['climate.air_conditioning_air_care']>
Error executing service: <ServiceCall climate.set_hvac_mode (c:01GW97XVYM2AX1DCGV1BN2AXRJ): hvac_mode=heat, entity_id=['climate.wand_unit']>
Error executing service: <ServiceCall climate.set_hvac_mode (c:01GW981XQCJXB4PSHKM0R5S57M): hvac_mode=heat, entity_id=['climate.wand_unit']>
Error executing service: <ServiceCall climate.set_hvac_mode (c:01GW982FW36AVWDCZRQY32XAKM): entity_id=['climate.wand_unit'], hvac_mode=heat>
Error executing service: <ServiceCall climate.set_hvac_mode (c:01GW983KNCJ96C33MEB9D9ZK2E): hvac_mode=heat, entity_id=['climate.wand_unit']>
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/core.py", line 1826, in catch_exceptions
    await coro_or_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1845, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 213, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 686, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 961, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 726, in _handle_entity_call
    await result
  File "/config/custom_components/smartthinq_sensors/climate.py", line 283, in async_set_hvac_mode
    await self._device.set_op_mode(operation_mode)
  File "/config/custom_components/smartthinq_sensors/wideq/devices/ac.py", line 712, in set_op_mode
    await self.set(keys[0], keys[1], key=keys[2], value=mode_value)
  File "/config/custom_components/smartthinq_sensors/wideq/devices/ac.py", line 873, in set
    await super().set(
  File "/config/custom_components/smartthinq_sensors/wideq/device.py", line 529, in set
    await self._set_control(
  File "/config/custom_components/smartthinq_sensors/wideq/device.py", line 480, in _set_control
    await self._client.session.set_device_controls(
  File "/config/custom_components/smartthinq_sensors/wideq/core_async.py", line 1151, in set_device_controls
    res = await self.post("rti/rtiControl", payload)
  File "/config/custom_components/smartthinq_sensors/wideq/core_async.py", line 1004, in post
    return await self._auth.gateway.core.lgedm2_post(
  File "/config/custom_components/smartthinq_sensors/wideq/core_async.py", line 337, in lgedm2_post
    return self._manage_lge_result(out, is_api_v2)
  File "/config/custom_components/smartthinq_sensors/wideq/core_async.py", line 364, in _manage_lge_result
    raise exc.APIError(message, code)
custom_components.smartthinq_sensors.wideq.core_exceptions.APIError: 0111 - 제품 응답 지연

```

```

**Additional context**

**Comment by maxoss** [comment]
Mysteriously solved. Probably something with the API
