### ISSUE TITLE
New Washer/Dryer added, not updating or controllable

### ISSUE THREAD

**Issue by cjramseyer** [ollo69/ha-smartthinq-sensors#517]
**Describe the bug**

Just purchased and installed Washer & Dryer.
Setup in the ThingQ app using normal email and password (not Google, Facebook, etc.)
Units function in the app correctly including starting, etc.

When dryer is running, the current status is not reflected in the integration.  the status of the dryer at the time the integration was added is shown.  Washer is the same.  Both devices have remote enabled.

The integration is easy to add, but doesn't seem to update
JSON file included below

**Expected behavior**
Expect sensors to update when units are used.
Expect to be able to start/stop the unit via the switch included in the integration.
Several sensors appear disabled

**Environment details:**
 - Environment (HASSIO, Raspbian, etc):HASSIO
 - Home Assistant version installed:2023.3.5
 - Component version installed:0.31.4
 - Last know working version:0.31.4
 - LG device type and model with issue:
 - Washer: WM8900HBA.ABLEEUS
 - Dryer: DLGX8901B.ABLEEUS
 - LG devices connected (list): washer/dryer

**Output of HA logs**
This error originated from a custom integration.

Logger: custom_components.smartthinq_sensors.wideq.device
Source: custom_components/smartthinq_sensors/wideq/device.py:689
Integration: SmartThinQ LGE Sensors (documentation, issues)
First occurred: April 1, 2023 at 7:23:08 PM (2 occurrences)
Last logged: April 1, 2023 at 11:14:41 PM

Connection to ThinQ failed. Timeout error - Device: Front Load Washer
Connection to ThinQ failed. Timeout error - Device: Dryer

This error originated from a custom integration.

Logger: custom_components.smartthinq_sensors.wideq.device
Source: custom_components/smartthinq_sensors/wideq/core_async.py:350
Integration: SmartThinQ LGE Sensors (documentation, issues)
First occurred: 11:25:06 AM (1 occurrences)
Last logged: 11:25:06 AM

Unexpected error while updating device status - Device: Dryer
Traceback (most recent call last):
  File "/config/custom_components/smartthinq_sensors/wideq/device.py", line 154, in refresh
    state, retry = await self.poll(query_device)
  File "/config/custom_components/smartthinq_sensors/wideq/device.py", line 265, in poll
    return await self._poll_v2(query_device)
  File "/config/custom_components/smartthinq_sensors/wideq/device.py", line 311, in _poll_v2
    await self._client.refresh_devices()
  File "/config/custom_components/smartthinq_sensors/wideq/core_async.py", line 1346, in refresh_devices
    await self._load_devices(True)
  File "/config/custom_components/smartthinq_sensors/wideq/core_async.py", line 1273, in _load_devices
    new_devices = await self._session.get_devices()
  File "/config/custom_components/smartthinq_sensors/wideq/core_async.py", line 1053, in get_devices
    dashboard = await self.get2("service/application/dashboard")
  File "/config/custom_components/smartthinq_sensors/wideq/core_async.py", line 1042, in get2
    return await self._auth.gateway.core.thinq2_get(
  File "/config/custom_components/smartthinq_sensors/wideq/core_async.py", line 304, in thinq2_get
    res = self._manage_lge_result(out, True)
  File "/config/custom_components/smartthinq_sensors/wideq/core_async.py", line 350, in _manage_lge_result
    raise exc.APIError(message, code)
custom_components.smartthinq_sensors.wideq.core_exceptions.APIError: 9999 - 

```

```

**Additional context**
[config_entry-smartthinq_sensors-17ea95712b9a5106cd23d51091e94ef0.json.txt](https://github.com/ollo69/ha-smartthinq-sensors/files/11132913/config_entry-smartthinq_sensors-17ea95712b9a5106cd23d51091e94ef0.json.txt)

**Comment by jhuang0** [comment]
Looks like the same issue reported here: https://github.com/ollo69/ha-smartthinq-sensors/issues/506#issue-1600169647

Temporary fix is to go back a release.

**Comment by cjramseyer** [comment]
> Looks like the same issue reported here: [#506 (comment)](https://github.com/ollo69/ha-smartthinq-sensors/issues/506#issue-1600169647)
> 
> Temporary fix is to go back a release.

I would be happy to go back to an earlier release.  I installed via HACS, and unlike other HACS installed integrations, there isn't an option to choose a different release.  Perhaps that could be resolved?

**Comment by koshisan** [comment]
> Looks like the same issue reported here: [#506 (comment)](https://github.com/ollo69/ha-smartthinq-sensors/issues/506#issue-1600169647)
> 
> Temporary fix is to go back a release.

Unfortunately, I have the same problem. The comments in #506 say two things:

1. Revert to 0.31.3 - which isn't offered through HACS anymore, 0.31.4 is the latest version
2. It seems to work again in 0.31.8 (which is the reason #506 is closed) - this also does not seem to be the case for neither @cjramseyer nor me...

Curiously, in my case it seems to be more a problem with the parser:

Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: custom_components.smartthinq_sensors
Source: custom_components/smartthinq_sensors/wideq/model_info.py:382
Integration: SmartThinQ LGE Sensors (documentation, issues)
First occurred: 14:28:13 (2 occurrences)
Last logged: 14:28:45

Unexpected error fetching smartthinq_sensors-Waschmaschine data: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 258, in _async_refresh
    self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 217, in _async_update_data
    return await self.update_method()
  File "/config/custom_components/smartthinq_sensors/__init__.py", line 463, in _async_update
    await self._async_state_update()
  File "/config/custom_components/smartthinq_sensors/__init__.py", line 475, in _async_state_update
    state = await self._device.poll()
  File "/config/custom_components/smartthinq_sensors/wideq/devices/washerDryer.py", line 336, in poll
    res = await self._device_poll(WM_ROOT_DATA)
  File "/config/custom_components/smartthinq_sensors/wideq/device.py", line 701, in _device_poll
    res = self._model_info.decode_monitor(data)
  File "/config/custom_components/smartthinq_sensors/wideq/model_info.py", line 391, in decode_monitor
    return self.decode_monitor_json(data)
  File "/config/custom_components/smartthinq_sensors/wideq/model_info.py", line 382, in decode_monitor_json
    return json.loads(data.decode("utf8"))
  File "/usr/local/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
