### ISSUE TITLE
After few Days (1-3 from restart) integration hangs

### ISSUE THREAD

**Issue by Gh61** [ollo69/ha-smartthinq-sensors#518]
**Describe the bug**
When I do clear restart of HA, everything works fine, but after a day or two (sometimes three) integration hangs and stops updating sensors and entities.

I don't know if this is also related to the problem,
but when I try to do quick reload of integration, nothing happens. The integration is still in the state of 'Initializing' and only restart of whole HA can fix this.

**Expected behavior**
It should work continuously without restart.

**Screenshots**
(don't know if related)
![image](https://user-images.githubusercontent.com/10837736/230599164-28e374b9-bb53-4d3f-a109-3df8abb00db2.png)

**Environment details:**
 - Environment (HASSIO, Raspbian, etc): Raspbian with HA in docker + Supervisor
 - Home Assistant version installed: 2023.4.0
 - Component version installed: 0.31.4
 - Last know working version: some very old version (if any)
 - LG device device mentioned in logs: D0211-DW (DISHWASHER) (Firmware: clip_hna_v1.9.183)
 - LG devices connected (list):
     - D0211-DW (DISHWASHER) (Firmware: clip_hna_v1.9.183)
     - WTWS3-FL (WASHER) (Firmware: QC_Modem_1.2.80)

**Output of HA logs**
```
2023-04-07 10:26:48.418 WARNING (MainThread) [custom_components.smartthinq_sensors.wideq.device] Unexpected error while updating device status - Device: Myčka
Traceback (most recent call last):
  File "/config/custom_components/smartthinq_sensors/wideq/device.py", line 154, in refresh
    state, retry = await self.poll(query_device)
  File "/config/custom_components/smartthinq_sensors/wideq/device.py", line 265, in poll
    return await self._poll_v2(query_device)
  File "/config/custom_components/smartthinq_sensors/wideq/device.py", line 311, in _poll_v2
    await self._client.refresh_devices()
  File "/config/custom_components/smartthinq_sensors/wideq/core_async.py", line 1346, in refresh_devices
    await self._load_devices(True)
  File "/config/custom_components/smartthinq_sensors/wideq/core_async.py", line 1273, in _load_devices
    new_devices = await self._session.get_devices()
  File "/config/custom_components/smartthinq_sensors/wideq/core_async.py", line 1053, in get_devices
    dashboard = await self.get2("service/application/dashboard")
  File "/config/custom_components/smartthinq_sensors/wideq/core_async.py", line 1042, in get2
    return await self._auth.gateway.core.thinq2_get(
  File "/config/custom_components/smartthinq_sensors/wideq/core_async.py", line 304, in thinq2_get
    res = self._manage_lge_result(out, True)
  File "/config/custom_components/smartthinq_sensors/wideq/core_async.py", line 350, in _manage_lge_result
    raise exc.APIError(message, code)
custom_components.smartthinq_sensors.wideq.core_exceptions.APIError: 9995 - 
```

**Additional context**
I don't know if the WARNING is really the cause of the problem, but it is the only thing from this integration in logs.

**Comment by sim642** [comment]
This might be a new broader issue, because today it broke for me as well after being continuously fine for at least a year.

**Comment by Gh61** [comment]
For me this problem is pending for at least half a year? Maybe since I started using this integration.
However I didn't checked the logs before.

**Comment by Gh61** [comment]
Ok, so here is also the error log, once the initializing phase ends.
```
Logger: homeassistant.config_entries
Source: custom_components/smartthinq_sensors/wideq/device.py:109
Integration: SmartThinQ LGE Sensors (documentation, issues)
First occurred: 13:32:12 (1 occurrences)
Last logged: 13:32:12

Error setting up entry LGE Devices for smartthinq_sensors
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 383, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/smartthinq_sensors/__init__.py", line 288, in async_setup_entry
    lge_devices, unsupported_devices, discovered_devices = await lge_devices_setup(
  File "/config/custom_components/smartthinq_sensors/__init__.py", line 570, in lge_devices_setup
    if not await dev.init_device():
  File "/config/custom_components/smartthinq_sensors/__init__.py", line 437, in init_device
    await self._create_coordinator()
  File "/config/custom_components/smartthinq_sensors/__init__.py", line 460, in _create_coordinator
    await coordinator.async_refresh()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 226, in async_refresh
    await self._async_refresh(log_failures=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 250, in _async_refresh
    self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 206, in _async_update_data
    return await self.update_method()
  File "/config/custom_components/smartthinq_sensors/__init__.py", line 465, in _async_update
    await self._async_state_update()
  File "/config/custom_components/smartthinq_sensors/__init__.py", line 477, in _async_state_update
    state = await self._device.poll()
  File "/config/custom_components/smartthinq_sensors/wideq/devices/washerDryer.py", line 339, in poll
    res = await self._device_poll(WM_ROOT_DATA)
  File "/config/custom_components/smartthinq_sensors/wideq/device.py", line 698, in _device_poll
    data = await self._mon.refresh()
  File "/config/custom_components/smartthinq_sensors/wideq/device.py", line 153, in refresh
    if refresh_auth := await self._refresh_auth():
  File "/config/custom_components/smartthinq_sensors/wideq/device.py", line 109, in _refresh_auth
    async with Monitor._client_lock:
  File "/usr/local/lib/python3.10/asyncio/locks.py", line 14, in __aenter__
    await self.acquire()
  File "/usr/local/lib/python3.10/asyncio/locks.py", line 114, in acquire
    await fut
asyncio.exceptions.CancelledError
```

**Comment by kvisle** [comment]
I'm a new user of this integration, and it has happened to me as well. Will make an effort to provide debug info at next occurrance

**Comment by ssrsmart** [comment]
the was working fine until about a two months ago, it's starting to fail and when then fixed it by restart HA and it fails again after a while, I checked LG ThinQ app and there is no update, I hope this issue will be resolved soon.

**Comment by createthisnl** [comment]
I’ve had the same issue. I’m only using a washing machine with my integration. As suggested in #506 downgrade to 0.31.3 fixed the issue for me.
Not sure if the recent release 0.31.6 fixes this issue.

**Comment by Gh61** [comment]
The issue is still present in latest release.
After few days all devices seems turned off, even if they are running.

**Comment by donnie-darko** [comment]
same issue here

**Comment by Zunion94** [comment]
Same issue. It beaks itself after 2-3 days. Restart helps.

**Comment by createthisnl** [comment]
That's too bad. I've been using it flawlessly since I downgraded to 0.31.3. I can recommend this to everyone, but I only use the wachmachine with this integration.

**Comment by createthisnl** [comment]
Since I’ve updated Home Assistant to 2023.05 the 0.31.3 integration wouldn’t initialize due to a dependency issue. This was fixed in 0.31.4 and onwards. 

Due to this issue, I’ve upgraded the integration to the latest version (0.31.6) and it is working properly now for about a week.

**Comment by ollo69** [comment]
This issue should be fixed by PR #545 merged in last release (v0.31.7)

**Comment by ollo69** [comment]
Based also on comment from similar issues seems that this problem is solved, so I close the issue. If problem persist please open a new one.

**Comment by Gh61** [comment]
I can confirm, that on the latest version is all working well even after one week of running HA without restart.
Thank you, good work.
