### ISSUE TITLE
Connection not available. SmartThinQ platform not ready.

### ISSUE THREAD

**Issue by turbo4door** [ollo69/ha-smartthinq-sensors#53]
Suddenly getting this error in my logs over and over.
```
2020-06-25 15:59:54 WARNING (MainThread) [custom_components.smartthinq_sensors] Connection not available. SmartThinQ platform not ready.
2020-06-25 15:59:54 WARNING (MainThread) [homeassistant.config_entries] Config entry for smartthinq_sensors not ready yet. Retrying in 80 seconds.
```
Nothing has changed in HA, other than updating to 111.4
entities are showing as "restored" when looking at them from the integration and clicking on "entities" link.

**Comment by ollo69** [comment]
Connection not available seems a problem related to internet connection. Is continuous problem or now is working?

**Comment by turbo4door** [comment]
It has been continuously posting these errors today, had to remove the
integration to get them to stop, but having some other issues today as
well. I'll add back once I get a.handle on what's happening. Thanks for
quick response.

**Comment by ollo69** [comment]
Probably your token become invalid, or there are some other issue related to HA upgrade.
Wait for your feedback on next days.

**Comment by towerhand** [comment]
I’m having the same issue, started today. I’ll remove it and add it again.

**Comment by alexanv1** [comment]
The same thing just happened to me. I was about to remove and re-add the integration but opened the LG app first and it prompted me to accept the updated terms and conditions. After doing so in the app, the sensors immediately started working again in HA without removing and re-adding the integration.

**Comment by turbo4door** [comment]
Thanks for the heads up. Just opened the app and got the same thing.
Hopefully that takes care of it this time. I removed but was unable to
re-add, and I bet that's why.

**Comment by alexanv1** [comment]
Btw, in my case, the only reason I noticed this is that I started seeing the following in the logs:

> 2020-06-26 19:29:17 ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor.washer fails
Traceback (most recent call last):
  File "/config/custom_components/smartthinq_sensors/__init__.py", line 389, in device_update
    state = self._device.poll()
  File "/config/custom_components/smartthinq_sensors/wideq/washer.py", line 39, in poll
    res = self.device_poll("washerDryer")
  File "/config/custom_components/smartthinq_sensors/wideq/device.py", line 783, in device_poll
    self._client.refresh_devices()
  File "/config/custom_components/smartthinq_sensors/wideq/core_v2.py", line 622, in refresh_devices
    self._load_devices(True)
  File "/config/custom_components/smartthinq_sensors/wideq/core_v2.py", line 582, in _load_devices
    self._devices = self._session.get_devices()
  File "/config/custom_components/smartthinq_sensors/wideq/core_v2.py", line 431, in get_devices
    dashboard = self.get2("service/application/dashboard")
  File "/config/custom_components/smartthinq_sensors/wideq/core_v2.py", line 423, in get2
    language=self.auth.gateway.language,
  File "/config/custom_components/smartthinq_sensors/wideq/core_v2.py", line 147, in thinq2_get
    raise exc.APIError(code, "error")
custom_components.smartthinq_sensors.wideq.core_exceptions.APIError: ('0110', 'error')

@ollo69, it would be really helpful if the sensors could be marked as Unavailable when a certain number of updates in a row fail to make this easier to detect if it happens in the future.

**Comment by ollo69** [comment]
I remember that this already occured in the past, I should add a note in readme.

> @ollo69, it would be really helpful if the sensors could be marked as Unavailable when a certain number of updates in a row fail to make this easier to detect if it happens in the future.

Yes, make sense, I will add in next release.

I close this issue.
