### ISSUE TITLE
Unable to setup - Error retrieving OAuth Info from ThinQ / Error Retrieving login URL from ThinQ

### ISSUE THREAD

**Issue by BluThunder2k** [ollo69/ha-smartthinq-sensors#537]
Hi,

Trying to get our Washer and Dryer LG thinq working with this integration.   Our account is a LG account, email address based.

Entering the username and password it sits for 10 seconds and comes up with:

"Invalid SmartThinQ credentials. Use the LG App on your mobile device to verify if there are Term of Service to accept. Account based on social network are not supported and in most case do not work with this integration."

No TOS updates, and logged out and back in with the username and password on the app fine.

Running:

Home Assistant 2023.5.2
Supervisor 2023.04.1
Operating System 10.1
Frontend 20230503.3 - latest

I get the following error from my login attempt:

Logger: custom_components.smartthinq_sensors
Source: custom_components/smartthinq_sensors/wideq/core_async.py:285
Integration: smartthinq_sensors ([documentation](https://github.com/ollo69/ha-smartthinq-sensors), [issues](https://github.com/ollo69/ha-smartthinq-sensors/issues))
First occurred: 5:26:28 PM (5 occurrences)
Last logged: 5:28:55 PM

Error retrieving OAuth info from ThinQ
Error retrieving login URL from ThinQ
Traceback (most recent call last):
  File "/config/custom_components/smartthinq_sensors/__init__.py", line 127, in get_oauth_info_from_login
    return await ClientAsync.oauth_info_from_user_login(
  File "/config/custom_components/smartthinq_sensors/wideq/core_async.py", line 1488, in oauth_info_from_user_login
    gateway = await Gateway.discover(core)
  File "/config/custom_components/smartthinq_sensors/wideq/core_async.py", line 692, in discover
    gw_info = await core.gateway_info()
  File "/config/custom_components/smartthinq_sensors/wideq/core_async.py", line 398, in gateway_info
    result = await self.thinq2_get(V2_GATEWAY_URL)
  File "/config/custom_components/smartthinq_sensors/wideq/core_async.py", line 285, in thinq2_get
    async with self._get_session().get(
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client.py", line 467, in _request
    with timer:
  File "/usr/local/lib/python3.10/site-packages/aiohttp/helpers.py", line 721, in __exit__
    raise asyncio.TimeoutError from None
asyncio.exceptions.TimeoutError

Any suggestions?

Dave

**Comment by khayamgondal** [comment]
Seeing the same thing since yesterday. Looks like integration stopped working

**Comment by Landcross** [comment]
I'm not sure if it's related, but our AC unit stopped working through HA since yesterday. The logs are reporting
> Connection to ThinQ failed. Invalid Token

**Comment by Claudio1L** [comment]
2023-05-09 18:14:46.326 WARNING (MainThread) [custom_components.smartthinq_sensors] Connection not available. ThinQ platform not ready
Traceback (most recent call last):
File "/config/custom_components/smartthinq_sensors/__init__.py", line 242, in async_setup_entry
client = await lge_auth.create_client_from_token(refresh_token, oauth2_url)
File "/config/custom_components/smartthinq_sensors/__init__.py", line 143, in create_client_from_token
return await ClientAsync.from_token(
File "/config/custom_components/smartthinq_sensors/wideq/core_async.py", line 1436, in from_token
await client.refresh()
File "/config/custom_components/smartthinq_sensors/wideq/core_async.py", line 1354, in refresh
self._auth = await self.auth.refresh(True)
File "/config/custom_components/smartthinq_sensors/wideq/core_async.py", line 931, in refresh
access_token, token_validity = await self._gateway.core.refresh_auth(
File "/config/custom_components/smartthinq_sensors/wideq/core_async.py", line 649, in refresh_auth
out = await self._auth_request(
File "/config/custom_components/smartthinq_sensors/wideq/core_async.py", line 595, in _auth_request
oauth_url = await self.get_oauth_url()
File "/config/custom_components/smartthinq_sensors/wideq/core_async.py", line 380, in get_oauth_url
async with self._get_session().post(
File "/usr/local/lib/python3.10/site-packages/aiohttp/client.py", line 1141, in __aenter__
self._resp = await self._coro
File "/usr/local/lib/python3.10/site-packages/aiohttp/client.py", line 560, in _request
await resp.start(conn)
File "/usr/local/lib/python3.10/site-packages/aiohttp/client_reqrep.py", line 899, in start
message, payload = await protocol.read() # type: ignore[union-attr]
File "/usr/local/lib/python3.10/site-packages/aiohttp/streams.py", line 616, in read
await self._waiter
aiohttp.client_exceptions.ServerDisconnectedError: Server disconnected
2023-05-09 18:14:46.329 WARNING (MainThread) [homeassistant.config_entries] Config entry 'LGE Devices' for smartthinq_sensors integration not ready yet: ThinQ platform not ready; Retrying in background

**Comment by robsonfelix** [comment]
Logger: homeassistant.config_entries
Source: config_entries.py:429 
First occurred: 3:01:57 PM (1 occurrences) 
Last logged: 3:01:57 PM

Config entry 'LGE Devices' for smartthinq_sensors integration not ready yet: ThinQ platform not ready; Retrying in background

**Comment by TRusselo** [comment]
My washer integration stopped today when  i rebooted home assistant

**Comment by Lavoy3** [comment]
Happened  to me too. solved it by entering email and not username🤣

**Comment by TRusselo** [comment]
mine fixed itself.  I did nothing. it started working.
must have been server issue.

**Comment by Claudio1L** [comment]
Same here. The strange thing is that the LG mobile app was working

From: Tristyn Russelo ***@***.***>
Date: Tuesday, 9 May 2023 at 23:44
To: ollo69/ha-smartthinq-sensors ***@***.***>
Cc: Claudio1L ***@***.***>, Comment ***@***.***>
Subject: Re: [ollo69/ha-smartthinq-sensors] Unable to setup - Error retrieving OAuth Info from ThinQ / Error Retrieving login URL from ThinQ (Issue #537)

mine fixed itself. I did nothing. it started working.
must have been server issue.

**Comment by BluThunder2k** [comment]
And this has cleared for me as well.   Thanks everyone!!!
