### ISSUE TITLE
Error executing service: ServiceCall switch.turn_on... 

### ISSUE THREAD

**Issue by klu16** [ollo69/ha-smartthinq-sensors#552]
**Describe the bug**
I can turn on the LG washer-dryer, but cannot turn it off. 

**Expected behavior**
The device turns off. 

**Screenshots**
![Screenshot_2023-05-22-22-23-48-890_io homeassistant companion android](https://github.com/ollo69/ha-smartthinq-sensors/assets/123963106/bb1c08dc-00bf-4d9d-8a0f-474989c3bc56)
![Screenshot_2023-05-22-22-23-33-583_io homeassistant companion android](https://github.com/ollo69/ha-smartthinq-sensors/assets/123963106/ee2e8115-ddd4-4564-97ba-a7ff9b0c9f6f)

**Environment details:**
 - Environment (HASSIO, Raspbian, etc): QNAP Virtualization Station image
 - Home Assistant version installed: 2023.5.3
 - Component version installed: 0.31.8
 - Last know working version: n/a
 - LG device type and model with issue: LG washer-dryer F4DV710H1E 
 - LG devices connected (list):

**Output of HA logs**
`Logger: homeassistant.core
Source: custom_components/smartthinq_sensors/wideq/core_async.py:359
Integration: SmartThinQ LGE Sensors (documentation, issues)
First occurred: 20:17:14 (1 occurrences)
Last logged: 20:17:14

Error executing service: <ServiceCall switch.turn_on (c:01H12AV23ZM3BP8VRQVHFJKE8E): entity_id=['switch.pralka_lg_power']>
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/core.py", line 1867, in catch_exceptions
    await coro_or_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1889, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 226, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 798, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 980, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 838, in _handle_entity_call
    await result
  File "/config/custom_components/smartthinq_sensors/switch.py", line 271, in async_turn_on
    await self.entity_description.turn_on_fn(self._wrap_device)
  File "/config/custom_components/smartthinq_sensors/wideq/devices/washerDryer.py", line 252, in wake_up
    await self.set_with_retry(keys[0], keys[1], value=keys[2], num_retry=2)
  File "/config/custom_components/smartthinq_sensors/wideq/devices/washerDryer.py", line 292, in set_with_retry
    await self.set(
  File "/config/custom_components/smartthinq_sensors/wideq/devices/washerDryer.py", line 267, in set
    await super().set(
  File "/config/custom_components/smartthinq_sensors/wideq/device.py", line 517, in set
    await self._set_control(full_key, ctrl_path=ctrl_path)
  File "/config/custom_components/smartthinq_sensors/wideq/device.py", line 489, in _set_control
    await self._client.session.device_v2_controls(
  File "/config/custom_components/smartthinq_sensors/wideq/core_async.py", line 1192, in device_v2_controls
    res = await self.post2(cmd_path, payload)
  File "/config/custom_components/smartthinq_sensors/wideq/core_async.py", line 1029, in post2
    return await self._auth.gateway.core.lgedm2_post(
  File "/config/custom_components/smartthinq_sensors/wideq/core_async.py", line 346, in lgedm2_post
    return self._manage_lge_result(out, is_api_v2)
  File "/config/custom_components/smartthinq_sensors/wideq/core_async.py", line 359, in _manage_lge_result
    raise exc.APIError(message, code)
custom_components.smartthinq_sensors.wideq.core_exceptions.APIError: 0111 - {'data': None}
 `

`Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/smartthinq_sensors/wideq/core_async.py:359
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 20:17:54 (6 occurrences)
Last logged: 20:44:40

[140514235715920] 9006 - {'data': ''}
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 199, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1849, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1889, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 226, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 798, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 980, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 838, in _handle_entity_call
    await result
  File "/config/custom_components/smartthinq_sensors/switch.py", line 263, in async_turn_off
    await self.entity_description.turn_off_fn(self._wrap_device)
  File "/config/custom_components/smartthinq_sensors/wideq/devices/washerDryer.py", line 242, in power_off
    await self.set_with_retry(keys[0], keys[1], value=keys[2], num_retry=2)
  File "/config/custom_components/smartthinq_sensors/wideq/devices/washerDryer.py", line 292, in set_with_retry
    await self.set(
  File "/config/custom_components/smartthinq_sensors/wideq/devices/washerDryer.py", line 267, in set
    await super().set(
  File "/config/custom_components/smartthinq_sensors/wideq/device.py", line 517, in set
    await self._set_control(full_key, ctrl_path=ctrl_path)
  File "/config/custom_components/smartthinq_sensors/wideq/device.py", line 489, in _set_control
    await self._client.session.device_v2_controls(
  File "/config/custom_components/smartthinq_sensors/wideq/core_async.py", line 1192, in device_v2_controls
    res = await self.post2(cmd_path, payload)
  File "/config/custom_components/smartthinq_sensors/wideq/core_async.py", line 1029, in post2
    return await self._auth.gateway.core.lgedm2_post(
  File "/config/custom_components/smartthinq_sensors/wideq/core_async.py", line 346, in lgedm2_post
    return self._manage_lge_result(out, is_api_v2)
  File "/config/custom_components/smartthinq_sensors/wideq/core_async.py", line 359, in _manage_lge_result
    raise exc.APIError(message, code)
custom_components.smartthinq_sensors.wideq.core_exceptions.APIError: 9006 - {'data': ''}
`

```

```

**Additional context**

**Comment by GaupeLnx** [comment]
This is expected behavior. Same as in the ThinQ app where, when you press the power button while it is on, wil get a warning saying "You won't be able to turn the Washer back on remotely. Turn power off?", and then a cancel or confirm option.
