### ISSUE TITLE
exception thrown in log file

### ISSUE THREAD

**Issue by erkr** [ollo69/ha-smartthinq-sensors#579]
**Describe the bug**
I have sometimes this error  in my log file. When controlling my airco’s via HA.  After this error has occurred,  the state of  my airco’s in the LG cloud service (check that via the official LGE app) got out off sync with actual state of my devices.

**Expected behavior**
If applicable, a clear and concise description of what you expected to happen.

**Screenshots**

**Environment details:**
 - HASSIO
 - core 2023.7
 - Component version installed: v0.31.8
 - This error is present since I’m using this integration (May 2023)
 - Device list:
 - AP09RK
 - S3-M09JA2PA(2x)

**Output of HA logs**
Paste the relavant output of the HA log here.

```
Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/smartthinq_sensors/wideq/core_async.py:358
Integration: Home Assistant WebSocket API (documentation, issues) 
First occurred: August 11, 2023 at 18:30:31 (1 occurrences) 
Last logged: August 11, 2023 at 18:30:31

[547022817232] {'data': ''}
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 205, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1965, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2005, in _execute_service
    return await cast(
           ^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 235, in handle_service
    return await service.entity_service_call(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 848, in entity_service_call
    response_data = task.result()  # pop exception if have
                    ^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1192, in async_request_call
    return await coro
           ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 892, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/config/custom_components/smartthinq_sensors/climate.py", line 282, in async_set_hvac_mode
    await self._device.power(True)
  File "/config/custom_components/smartthinq_sensors/wideq/devices/ac.py", line 704, in power
    await self.set(keys[0], keys[1], key=keys[2], value=op_value)
  File "/config/custom_components/smartthinq_sensors/wideq/devices/ac.py", line 873, in set
    await super().set(
  File "/config/custom_components/smartthinq_sensors/wideq/device.py", line 528, in set
    await self._set_control(
  File "/config/custom_components/smartthinq_sensors/wideq/device.py", line 489, in _set_control
    await self._client.session.device_v2_controls(
  File "/config/custom_components/smartthinq_sensors/wideq/core_async.py", line 1192, in device_v2_controls
    res = await self.post2(cmd_path, payload)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/smartthinq_sensors/wideq/core_async.py", line 1029, in post2
    return await self._auth.gateway.core.lgedm2_post(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/smartthinq_sensors/wideq/core_async.py", line 346, in lgedm2_post
    return self._manage_lge_result(out, is_api_v2)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/smartthinq_sensors/wideq/core_async.py", line 358, in _manage_lge_result
    raise API2_ERRORS[code](message)
custom_components.smartthinq_sensors.wideq.core_exceptions.FailedRequestError: {'data': ''}
```

**Additional context**

**Comment by erkr** [comment]
Haven't seen them in the latest versions. I close the issue
