### ISSUE TITLE
Can't login

### ISSUE THREAD

**Issue by bzzzggz** [ollo69/ha-smartthinq-sensors#598]
Recently created a new LG SmartThinQ account in AU ENG. Got an error message: Invalid SmartThinQ credentials.

Can't find anywhere within the app to ask me to accept the term of service.

**Comment by ollo69** [comment]
Please add more info add screenshot about the authentication process and method used.

**Comment by andrewdrob10** [comment]
I am getting a similar issue,

```
Traceback (most recent call last):

File "/config/custom_components/smartthinq_sensors/__init__.py", line 251, in async_setup_entry

client = await lge_auth.create_client_from_token(refresh_token, oauth2_url)

^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

File "/config/custom_components/smartthinq_sensors/__init__.py", line 150, in create_client_from_token

return await ClientAsync.from_token(

^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

File "/config/custom_components/smartthinq_sensors/wideq/core_async.py", line 1445, in from_token

await client.refresh()

File "/config/custom_components/smartthinq_sensors/wideq/core_async.py", line 1363, in refresh

self._auth = await self.auth.refresh(True)

^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

File "/config/custom_components/smartthinq_sensors/wideq/core_async.py", line 947, in refresh

self.user_number = await self._gateway.core.get_user_number(access_token)

^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

File "/config/custom_components/smartthinq_sensors/wideq/core_async.py", line 590, in get_user_number

raise exc.AuthenticationError("Failed to retrieve User Number")

custom_components.smartthinq_sensors.wideq.core_exceptions.AuthenticationError: Failed to retrieve User Number

2023-09-15 11:05:08.432 WARNING (MainThread) [homeassistant.config_entries] Config entry 'LGE Devices' for smartthinq_sensors integration not ready yet: Invalid ThinQ credential error, integration setup aborted. Please use the LG App on your mobile device to verify credential.; Retrying in background

2023-09-15 11:05:27.039 ERROR (MainThread) [custom_components.smartthinq_sensors.wideq.core_async] get_user_number: invalid response: {'error': {'code': '9402', 'message': 'Asset 간의 통신 장애가 발생했습니다. :: SocketTimeoutException: 5,000 milliseconds timeout on connection http-outgoing-406282 [ACTIVE]', 'request': '/users/profile', 'service': 'system'}}

2023-09-15 11:05:44.709 ERROR (MainThread) [custom_components.smartthinq_sensors.wideq.core_async] get_user_number: invalid response: {'status': 2, 'lgoauth_error_code': 'LG.OAUTH.EC.2002', 'message': 'EMP processing error.'}

2023-09-15 11:06:13.568 ERROR (MainThread) [custom_components.smartthinq_sensors.wideq.core_async] get_user_number: invalid response: {'error': {'code': '9402', 'message': 'Asset 간의 통신 장애가 발생했습니다. :: SocketTimeoutException: 5,000 milliseconds timeout on connection http-outgoing-462747 [ACTIVE]', 'request': '/users/profile', 'service': 'system'}}

2023-09-15 11:07:02.651 ERROR (MainThread) [custom_components.smartthinq_sensors.wideq.core_async] get_user_number: invalid response: {'error': {'code': '9402', 'message': 'Asset 간의 통신 장애가 발생했습니다. :: SocketTimeoutException: 5,000 milliseconds timeout on connection http-outgoing-423296 [ACTIVE]', 'request': '/users/profile', 'service': 'system'}}

2023-09-15 11:08:15.817 ERROR (MainThread) [custom_components.smartthinq_sensors.wideq.core_async] get_user_number: invalid response: {'error': {'code': '9402', 'message': 'Asset 간의 통신 장애가 발생했습니다. :: SocketTimeoutException: 5,000 milliseconds timeout on connection http-outgoing-480755 [ACTIVE]', 'request': '/users/profile', 'service': 'system'}}

2023-09-15 11:08:15.821 WARNING (MainThread) [homeassistant.config_entries] Config entry 'LGE Devices' for smartthinq_sensors integration could not authenticate: Failed to retrieve User Number
```

**Comment by brywithawhy** [comment]
Also from AU and also having trouble logging in:

```
This error originated from a custom integration.

Logger: custom_components.smartthinq_sensors
Source: custom_components/smartthinq_sensors/wideq/core_async.py:876
Integration: SmartThinQ LGE Sensors (documentation, issues)
First occurred: 4:31:21 AM (2 occurrences)
Last logged: 4:39:06 AM

Error retrieving OAuth info from ThinQ
Traceback (most recent call last):
  File "/config/custom_components/smartthinq_sensors/wideq/core_async.py", line 867, in oauth_info_from_user_login
    token_info = await gateway.core.auth_user_login(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/smartthinq_sensors/wideq/core_async.py", line 557, in auth_user_login
    raise exc.TokenError()
custom_components.smartthinq_sensors.wideq.core_exceptions.TokenError: Token Error

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/smartthinq_sensors/__init__.py", line 134, in get_oauth_info_from_login
    return await ClientAsync.oauth_info_from_user_login(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/smartthinq_sensors/wideq/core_async.py", line 1498, in oauth_info_from_user_login
    result = await Auth.oauth_info_from_user_login(username, password, gateway)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/smartthinq_sensors/wideq/core_async.py", line 876, in oauth_info_from_user_login
    raise exc.AuthenticationError("User login failed") from ex
custom_components.smartthinq_sensors.wideq.core_exceptions.AuthenticationError: User login failed

```

**Comment by bzzzggz** [comment]
Working now. LG suddenly popped a term of usage for me to accept. I think LG's app is not designed properly, which makes it hard even to find a place to accept the terms of usage.
