### ISSUE TITLE
Can't load integration after upgrading Rasberry Pi OS (to Bookworm/Debian 12)

### ISSUE THREAD

**Issue by psfales** [ollo69/ha-smartthinq-sensors#623]
**Describe the bug**
I'm having the same issue as described in #608.   The integration was working for me before I upgraded my Raspberry Pi from Bullseye to Bookworm.  (This was needed because HA 20223.10.0 and later will not run on Bullseye).  After the upgrade, I'm not able to login.   I verified that I can login to the web site and to the app, and tried removing and re-adding the integration.  When logging in through the app, it told me that it's been a long time since I changed my password, so I did that.    Again verified that I can login through the web page and app, but removing and re-adding the integration does not work.  

I'm using the email login/password authentication

**Expected behavior**
The integration should load and find my washer and dryer.

**Screenshots**

**Environment details:**
 - Environment (HASSIO, Raspbian, etc):  HA core running on Raspbian Bookworm
 - Home Assistant version installed: 2023.10.4 
 - Component version installed: v0.34.0
 - Last know working version:  (I think it was the same version  when I was on Bullseye, but not sure)
 - LG device type and model with issue:
 - LG devices connected (list):

**Output of HA logs**

```
2023-10-21 19:31:05.020 WARNING (MainThread) [custom_components.smartthinq_sensors] Connection not available. ThinQ platform not ready
Traceback (most recent call last):
  File "/srv/homeassistant3.11/lib/python3.11/site-packages/aiohttp/client.py", line 558, in _request
    resp = await req.send(conn)
           ^^^^^^^^^^^^^^^^^^^^
  File "/srv/homeassistant3.11/lib/python3.11/site-packages/aiohttp/client_reqrep.py", line 670, in send
    await writer.write_headers(status_line, self.headers)
  File "/srv/homeassistant3.11/lib/python3.11/site-packages/aiohttp/http_writer.py", line 130, in write_headers
    self._write(buf)
  File "/srv/homeassistant3.11/lib/python3.11/site-packages/aiohttp/http_writer.py", line 75, in _write
    raise ConnectionResetError("Cannot write to closing transport")
ConnectionResetError: Cannot write to closing transport

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/homeassistant/.homeassistant/custom_components/smartthinq_sensors/__init__.py", line 293, in async_setup_entry
    lge_devices, unsupported_devices, discovered_devices = await lge_devices_setup(
                                                           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/homeassistant/.homeassistant/custom_components/smartthinq_sensors/__init__.py", line 575, in lge_devices_setup
    if not await dev.init_device():
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/homeassistant/.homeassistant/custom_components/smartthinq_sensors/__init__.py", line 436, in init_device
    if not await self._device.init_device_info():
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/homeassistant/.homeassistant/custom_components/smartthinq_sensors/wideq/device.py", line 432, in init_device_info
    self._model_data = await self._client.model_url_info(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/homeassistant/.homeassistant/custom_components/smartthinq_sensors/wideq/core_async.py", line 1581, in model_url_info
    if not (model_url_info := await self._load_json_info(url)):
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/homeassistant/.homeassistant/custom_components/smartthinq_sensors/wideq/core_async.py", line 1510, in _load_json_info
    content = await self._auth.gateway.core.http_get_bytes(info_url)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/homeassistant/.homeassistant/custom_components/smartthinq_sensors/wideq/core_async.py", line 276, in http_get_bytes
    async with self._get_session().get(
  File "/srv/homeassistant3.11/lib/python3.11/site-packages/aiohttp/client.py", line 1141, in __aenter__
    self._resp = await self._coro
                 ^^^^^^^^^^^^^^^^
  File "/srv/homeassistant3.11/lib/python3.11/site-packages/aiohttp/client.py", line 572, in _request
    raise ClientOSError(*exc.args) from exc
aiohttp.client_exceptions.ClientOSError: Cannot write to closing transport

```

**Additional context**

**Comment by psfales** [comment]
To be more clear, the integration actually loads to the point where it is visible in the list of integrations, but it fails setup and doesn't recognize my devices.   When it retries periodically, or when I manually click "reload," it goes briefly to "Initializing" then to "Failed setup, will retry"

**Comment by psfales** [comment]
Strange, after being disconnected for several days (following the upgrade, it took me a while to get around to looking at it) and then actively fighting with it for several hours today (trying all the experiments in the description), it suddenly connected up and started working.  I wonder if it took some time for the password change to propagate on the LG side.

The only puzzle is that a couple of sensors that I used to have on my dashboard are now showing up as unavailable (specifically, switch.washer_power_off, and switch.dryer_power_off are no longer listed)

**Comment by psfales** [comment]
Seems to working ok now.  Maybe it was because I reset the password, or maybe it was a transient problem on LG's end.   In any case, it's hard to debug when the problem isn't happening!

**Comment by ollo69** [comment]
Good to know that now is working. 
There are a lot of variables here: you upgrade the OS to Bookworm, you upgrade HA and you change LG password.
The error in log seems something related to local network (Cannot write to closing transport) but I suppose that your network was working fine. 
Considering all these variables and that the error disappear, it is impossible to investigate on the cause.
