### ISSUE TITLE
Can’t login

### ISSUE THREAD

**Issue by Andreweburg** [ollo69/ha-smartthinq-sensors#658]
**Can’t login using email/pass**

“Error connecting to SmartThinQ. Try again, and make sure you can access the ThinQ app on your phone.”

Logger: custom_components.smartthinq_sensors.config_flow
Source: custom_components/smartthinq_sensors/config_flow.py:222
Integration: SmartThinQ LGE Sensors ([documentation](https://github.com/ollo69/ha-smartthinq-sensors), [issues](https://github.com/ollo69/ha-smartthinq-sensors/issues)) 
First occurred: 08:38:03 (5 occurrences) 
Last logged: 09:11:20

Error connecting to ThinQ
Traceback (most recent call last):
  File "/config/custom_components/smartthinq_sensors/config_flow.py", line 222, in _check_connection
    client = await lge_auth.create_client_from_token(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/smartthinq_sensors/__init__.py", line 151, in create_client_from_token
    return await ClientAsync.from_token(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/smartthinq_sensors/wideq/core_async.py", line 1446, in from_token
    await client.refresh()
  File "/config/custom_components/smartthinq_sensors/wideq/core_async.py", line 1366, in refresh
    await self._load_devices()
  File "/config/custom_components/smartthinq_sensors/wideq/core_async.py", line 1283, in _load_devices
    new_devices = await self._session.get_devices()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/smartthinq_sensors/wideq/core_async.py", line 1065, in get_devices
    self._common_lang_pack_url = dashboard.get("langPackCommonUri")
                                 ^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'get'

**Everything is ok in app. 
terms of service are accepted. 

Lg account is just created (new one). 

i tried to reinstall app/ integration, create new account.  Nothing ((((**

**if I use Share Home Assistant HTTP connection (may cause SSL errors) mode
I receive this kind of error:**

“Invalid SmartThinQ credentials. Use the LG App on your mobile device to verify if there are Term of Service to accept. Account based on social network are not supported and in most case do not work with this integration.”

Logger: custom_components.smartthinq_sensors
Source: custom_components/smartthinq_sensors/__init__.py:135
Integration: SmartThinQ LGE Sensors ([documentation](https://github.com/ollo69/ha-smartthinq-sensors), [issues](https://github.com/ollo69/ha-smartthinq-sensors/issues)) 
First occurred: 09:05:00 (3 occurrences) 
Last logged: 09:13:25

Error retrieving OAuth info from ThinQ
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aiohttp/connector.py", line 992, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 1112, in create_connection
    transport, protocol = await self._create_connection_transport(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 1145, in _create_connection_transport
    await waiter
  File "/usr/local/lib/python3.11/asyncio/sslproto.py", line 575, in _on_handshake_complete
    raise handshake_exc
  File "/usr/local/lib/python3.11/asyncio/sslproto.py", line 557, in _do_handshake
    self._sslobj.do_handshake()
  File "/usr/local/lib/python3.11/ssl.py", line 979, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1006)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/smartthinq_sensors/wideq/core_async.py", line 868, in oauth_info_from_user_login
    token_info = await gateway.core.auth_user_login(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/smartthinq_sensors/wideq/core_async.py", line 474, in auth_user_login
    async with self._get_session().post(
  File "/usr/local/lib/python3.11/site-packages/aiohttp/client.py", line 1187, in __aenter__
    self._resp = await self._coro
                 ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/client.py", line 574, in _request
    conn = await self._connector.connect(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/connector.py", line 544, in connect
    proto = await self._create_connection(req, traces, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/connector.py", line 911, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/connector.py", line 1235, in _create_direct_connection
    raise last_exc
  File "/usr/local/lib/python3.11/site-packages/aiohttp/connector.py", line 1204, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/connector.py", line 996, in _wrap_create_connection
    raise ClientConnectorSSLError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorSSLError: Cannot connect to host ru.emp.lgsmartplatform.com:443 ssl:default [[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1006)]

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/smartthinq_sensors/__init__.py", line 135, in get_oauth_info_from_login
    return await ClientAsync.oauth_info_from_user_login(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/smartthinq_sensors/wideq/core_async.py", line 1499, in oauth_info_from_user_login
    result = await Auth.oauth_info_from_user_login(username, password, gateway)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/smartthinq_sensors/wideq/core_async.py", line 877, in oauth_info_from_user_login
    raise exc.AuthenticationError("User login failed") from ex
custom_components.smartthinq_sensors.wideq.core_exceptions.AuthenticationError: User login failed

**plz help ☺️🥲**

**Comment by Stif007** [comment]
I also can’t log in, same errors

**Comment by wantsoftat** [comment]
I also can’t log in, same errors

**Comment by WhFrost** [comment]
I also can’t log in, same errors

**Comment by slydiman** [comment]
It seems duplicate issue https://github.com/ollo69/ha-smartthinq-sensors/issues/651
BTW, after https://github.com/ollo69/ha-smartthinq-sensors/pull/659 I can login, but the device list is empty.

**Comment by edwardtich1** [comment]
Invalid ThinQ credential error, integration setup aborted. Please use the LG App on your mobile device to ensure your credentials are correct or there are new Term of Service to accept. If your credential changed, you must reconfigure integration. Account based on social network are not supported and in most case do not work with this integration.

**Comment by Andreweburg** [comment]
> Invalid ThinQ credential error, integration setup aborted. Please use the LG App on your mobile device to ensure your credentials are correct or there are new Term of Service to accept. If your credential changed, you must reconfigure integration. Account based on social network are not supported and in most case do not work with this integration.

I’ve just created new account to be 100% sure. 
everything is ok in the app.

**Comment by WhFrost** [comment]
Error connecting to SmartThinQ. Try again, and make sure you can access the ThinQ app on your phone.

**Comment by Andreweburg** [comment]
> Error connecting to SmartThinQ. Try again, and make sure you can access the ThinQ app on your phone.

I’ve just logged in via homebridge everything works fine. But via this integration it is impossible to do. 
I’m trying to log in via this integration 2 times a day. Week passed - no success ((
My iOS app works fine.

**Comment by ollo69** [comment]
Please refer to #651.
I found some changes analyzing the traffic from LG app, but need some time to implement changes.

**Comment by edwardtich1** [comment]
Error connecting to SmartThinQ. Try again, and make sure you can access the ThinQ app on your phone.

**Comment by Andreweburg** [comment]
> Error connecting to SmartThinQ. Try again, and make sure you can access the ThinQ app on your phone.

![IMG_1947](https://github.com/ollo69/ha-smartthinq-sensors/assets/98278997/eb55fb77-5796-4dc0-aa45-37271efc5571)
Exactly the same ((

**Comment by ollo69** [comment]
Please try using last release and let me know if it fix this issue. Because this issue is closed please continue discussion on #651.
