### ISSUE TITLE
Duct zone control failed

### ISSUE THREAD

**Issue by srrsparky** [ollo69/ha-smartthinq-sensors#670]
**Describe the bug**
Zone control has stopped working recently (the last few days).

[a031afda-0523-6563-6b9d-f0cb779e11db.json](https://github.com/ollo69/ha-smartthinq-sensors/files/13868230/a031afda-0523-6563-6b9d-f0cb779e11db.json)

**Environment details:**
 - Environment (HASSIO, Raspbian, etc): 
 - Home Assistant version installed: 2024.1.2 (core) 2023.12.0 (supervisor)
 - Component version installed: v0.36.2
 - Last know working version: it works intermittently
 - LG device type and model with issue: Ducted air conditioner
 - LG devices connected (list):

**Output of HA logs**
```
2024-01-09 10:41:34.299 DEBUG (MainThread) [custom_components.smartthinq_sensors.wideq.core_async] Loading model info for Air Conditioner. Model: DUCT_626301_AU, Url: https://kic.lgthinq.com:46030/api/webContents/modelJSON?modelName=modelJSON_401&countryCode=KR&contentsId=a031afda-0523-6563-6b9d-f0cb779e11db&authKey=thinq
2024-01-09 10:41:35.140 DEBUG (MainThread) [custom_components.smartthinq_sensors] Updating ThinQ device Air Conditioner
2024-01-09 10:41:35.140 DEBUG (MainThread) [custom_components.smartthinq_sensors.wideq.device] Updating ThinQ device Air Conditioner
2024-01-09 10:41:35.140 DEBUG (MainThread) [custom_components.smartthinq_sensors.wideq.device] Polling...
2024-01-09 10:41:35.141 DEBUG (MainThread) [custom_components.smartthinq_sensors.wideq.core_async] lgedm2_post before: https://kic.lgthinq.com:46030/api/rti/rtiMon
2024-01-09 10:41:35.821 DEBUG (MainThread) [custom_components.smartthinq_sensors.wideq.core_async] lgedm2_post after: {'lgedmRoot': {'returnCd': '0000', 'returnMsg': 'OK', 'stateCode': 'S', 'workId': 'n-a031afda-0523-6563-6b9d-f0cb779e11db', 'deviceState': 'E', 'timestamp': 0}}
2024-01-09 10:41:35.821 DEBUG (MainThread) [custom_components.smartthinq_sensors.wideq.core_async] lgedm2_post before: https://kic.lgthinq.com:46030/api/rti/rtiResult
2024-01-09 10:41:36.460 DEBUG (MainThread) [custom_components.smartthinq_sensors.wideq.core_async] lgedm2_post after: {'lgedmRoot': {'returnCd': '0000', 'returnMsg': 'OK', 'workList': {'deviceId': 'a031afda-0523-6563-6b9d-f0cb779e11db', 'deviceState': 'E', 'format': 'B64', 'returnCode': '0000', 'returnData': 'eyJPcGVyYXRpb24iOiIwIiwiT3BNb2RlIjoiMiIsIldpbmRTdHJlbmd0aCI6IjIiLCJUZW1wVW5pdCI6IjAiLCJUZW1wQ3VyIjoiMzkiLCJUZW1wQ2ZnIjoiMjEiLCJHcm91cFR5cGUiOiI1IiwiQWlyQ2xlYW4iOiJOUyIsIkF1dG9EcnkiOiJOUyIsIlBvd2VyU2F2ZSI6Ik5TIiwiU2xlZXBUaW1lIjoiMCIsIk9uVGltZSI6Ik5TIiwiT2ZmVGltZSI6Ik5TIiwiUmFjQWRkRnVuYyI6Ik5TIiwiRXh0cmFPcCI6IjAiLCJEaWFnQ29kZSI6IjAwIiwiVGVtcExpbWl0TWF4IjoiMzAiLCJUZW1wTGltaXRNaW4iOiIxNiIsIlRpbWVCc09uIjoiMCIsIlRpbWVCc09mZiI6IjAiLCJEdWN0Wm9uZVR5cGUiOiI0IiwiWm9uZUNvbnRyb2wiOiIxIiwiRFJFRCI6IjAifQ==', 'stateCode': 'S', 'workId': 'n-a031afda-0523-6563-6b9d-f0cb779e11db'}}}
2024-01-09 10:41:36.461 DEBUG (MainThread) [custom_components.smartthinq_sensors.wideq.core_async] lgedm2_post before: https://kic.lgthinq.com:46030/api/rti/rtiControl
2024-01-09 10:41:37.438 DEBUG (MainThread) [custom_components.smartthinq_sensors.wideq.core_async] lgedm2_post after: {'lgedmRoot': {'returnCd': '0011', 'returnMsg': '등록되지 않은 모델입니다.', 'deviceId': 'a031afda-0523-6563-6b9d-f0cb779e11db', 'stateCode': 'S', 'workId': 'n-36b36381-75ef-41d7-baa7-de347e615b', 'deviceState': 'E', 'timestamp': 0}}
2024-01-09 10:41:37.438 DEBUG (MainThread) [custom_components.smartthinq_sensors.wideq.device] Error calling additional poll V1 methods: 0011 - 등록되지 않은 모델입니다.
2024-01-09 10:41:37.439 DEBUG (MainThread) [custom_components.smartthinq_sensors.wideq.core_async] lgedm2_post before: https://kic.lgthinq.com:46030/api/rti/rtiControl
2024-01-09 10:41:38.469 DEBUG (MainThread) [custom_components.smartthinq_sensors.wideq.core_async] lgedm2_post after: {'lgedmRoot': {'returnCd': '0011', 'returnMsg': '등록되지 않은 모델입니다.', 'deviceId': 'a031afda-0523-6563-6b9d-f0cb779e11db', 'stateCode': 'S', 'workId': 'n-2255095e-973e-49ca-a1a7-88e5e0e414', 'deviceState': 'E', 'timestamp': 0}}
2024-01-09 10:41:38.469 ERROR (MainThread) [custom_components.smartthinq_sensors.wideq.devices.ac] Duct zone control failed
Traceback (most recent call last):
  File "/config/custom_components/smartthinq_sensors/wideq/devices/ac.py", line 957, in poll
    await self.update_duct_zones()
  File "/config/custom_components/smartthinq_sensors/wideq/devices/ac.py", line 445, in update_duct_zones
    states = await self._get_duct_zones()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/smartthinq_sensors/wideq/devices/ac.py", line 502, in _get_duct_zones
    zones = await self._get_config(DUCT_ZONE_V1)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/smartthinq_sensors/wideq/device.py", line 603, in _get_config
    data = await self._client.session.get_device_config(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/smartthinq_sensors/wideq/core_async.py", line 1326, in get_device_config
    res = await self.post(
          ^^^^^^^^^^^^^^^^
  File "/config/custom_components/smartthinq_sensors/wideq/core_async.py", line 1055, in post
    return await self._auth.gateway.core.lgedm2_post(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/smartthinq_sensors/wideq/core_async.py", line 385, in lgedm2_post
    return self._manage_lge_result(out, is_api_v2)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/smartthinq_sensors/wideq/core_async.py", line 412, in _manage_lge_result
    raise exc.APIError(message, code)
custom_components.smartthinq_sensors.wideq.core_exceptions.APIError: 0011 - 등록되지 않은 모델입니다.
```

**Comment by ollo69** [comment]
Does it works with previous release? Can you try to roll-back?

**Comment by srrsparky** [comment]
I did a search on the Korean error message, and looks like it is mostly linked to the LG app. I signed out of the app, and restarted the air conditioner (off and on at the breaker). Restated home assistant and it is working again. 

Thanks for the integration 😀
