### ISSUE TITLE
Invalid SmartThingQ credentials

### ISSUE THREAD

**Issue by menmnl** [ollo69/ha-smartthinq-sensors#686]
I succesfuly installed V0.37.0 through HACS in order to control my airco units from HA.
When adding the integration in the Devices & services/integrations tab and submitting the required configuration information, I get a ‘Invalid SmartThinQ credentials’ error.

I have used a private email address for my LG registration as stated, and accepted all license and privacy agreements in the LG app and on the website.
Also, the LG ThinQ apps works fine, controlling my 3 airco units.
I did the LG app registration and configuration from the Netherlands, thus using country code Netherlands-NL and language Dutch-nl and verified those in the LG app.
I tried the given SmartThinq login URL to see if redirection works, but am not able to generate a working redirect URL because of an internal server error. So, dead end on the LG side (my normal account logins through https://www.lg.com/nl are OK).

I found a lot of open ends in existing HA threads, so trying here.
Hope you can be of help!
As I am still a HA rooky please adjust your answer to my level.

HA Core 2024.1.6
HA OS 11.4
Raspberry Pi 4 model B

**Comment by ollo69** [comment]
It is very hard to find a valid reason for not working account.
Please start adding here the log error that you receive when you try to login with your credential.

**Comment by menmnl** [comment]
Thanks for your early reply.

I read the logs before sending. Got an SSL error.
It seems that nl.emp.lgsmartplatform.com was filtered out by OpenDNS.
Whitelisted the URL and airco units are now recovered. Let the fun begin!


FYI, perhaps to implement a proper error response:

This error originated from a custom integration.

Logger: custom_components.smartthinq_sensors
Source: custom_components/smartthinq_sensors/__init__.py:135
Integration: SmartThinQ LGE Sensors (documentation, issues)
First occurred: 14:53:45 (2 occurrences)
Last logged: 18:52:08

Error retrieving OAuth info from ThinQ
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aiohttp/connector.py", line 992, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 1112, in create_connection
    transport, protocol = await self._create_connection_transport(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 1145, in _create_connection_transport
    await waiter
  File "/usr/local/lib/python3.11/asyncio/sslproto.py", line 575, in _on_handshake_complete
    raise handshake_exc
  File "/usr/local/lib/python3.11/asyncio/sslproto.py", line 557, in _do_handshake
    self._sslobj.do_handshake()
  File "/usr/local/lib/python3.11/ssl.py", line 979, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/smartthinq_sensors/wideq/core_async.py", line 908, in oauth_info_from_user_login
    token_info = await gateway.core.auth_user_login(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/smartthinq_sensors/wideq/core_async.py", line 514, in auth_user_login
    async with self._get_session().post(
  File "/usr/local/lib/python3.11/site-packages/aiohttp/client.py", line 1194, in __aenter__
    self._resp = await self._coro
                 ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/client.py", line 578, in _request
    conn = await self._connector.connect(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/connector.py", line 544, in connect
    proto = await self._create_connection(req, traces, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/connector.py", line 911, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/connector.py", line 1235, in _create_direct_connection
    raise last_exc
  File "/usr/local/lib/python3.11/site-packages/aiohttp/connector.py", line 1204, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/connector.py", line 994, in _wrap_create_connection
    raise ClientConnectorCertificateError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorCertificateError: Cannot connect to host nl.emp.lgsmartplatform.com:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)')]

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/smartthinq_sensors/__init__.py", line 135, in get_oauth_info_from_login
    return await ClientAsync.oauth_info_from_user_login(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/smartthinq_sensors/wideq/core_async.py", line 1621, in oauth_info_from_user_login
    result = await Auth.oauth_info_from_user_login(username, password, gateway)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/smartthinq_sensors/wideq/core_async.py", line 917, in oauth_info_from_user_login
    raise exc.AuthenticationError("User login failed") from ex
custom_components.smartthinq_sensors.wideq.core_exceptions.AuthenticationError: User login failed
