### ISSUE TITLE
Failed to set up

### ISSUE THREAD

**Issue by OddmarDam** [ollo69/ha-smartthinq-sensors#694]
**Describe the bug**
Plugin says faiel to setup

**Expected behavior**

**Screenshots**

**Environment details:**
 - Environment HASSIO on a NUC
  Core   2024.1.6 
  Supervisor   2024.01.1 
  Operating System   11.5
  Frontend   20240104.0

**Output of HA logs**
Logger: homeassistant.config_entries
Source: config_entries.py:406
First occurred: 6 February 2024 at 09:58:39 (2 occurrences)
Last logged: 15:46:12

Error setting up entry LGE Devices for smartthinq_sensors
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 406, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/smartthinq_sensors/__init__.py", line 215, in async_setup_entry
    await cleanup_orphan_lge_devices(hass, config_entry.entry_id, client)
  File "/config/custom_components/smartthinq_sensors/__init__.py", line 596, in cleanup_orphan_lge_devices
    device_registry = await hass.helpers.device_registry.async_get_registry()
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1075, in __getattr__
    value = getattr(self._module, attr)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/deprecation.py", line 258, in check_if_deprecated_constant
    raise AttributeError(f"Module {module_name!r} has no attribute {name!r}")
AttributeError: Module 'homeassistant.helpers.device_registry' has no attribute 'async_get_registry'

**Comment by ollo69** [comment]
Can you give detail about integration version and how you install? Looking the code seems that you are using an old version
