### ISSUE TITLE
Can`t login after reboot HA, can't connect to any device

### ISSUE THREAD

**Issue by santo76** [ollo69/ha-smartthinq-sensors#719]
**Describe the bug**
After restart HA, it can't connect again with LG devices

**Expected behavior**
Lg extension must connect with lg cloud, to manage devices
<img width="1623" alt="Captura de pantalla 2024-03-14 a las 9 30 26" src="https://github.com/ollo69/ha-smartthinq-sensors/assets/4824730/c5bcbbcd-13c8-4720-8773-697999e2cec4">

**Screenshots**
<img width="1623" alt="Captura de pantalla 2024-03-14 a las 9 30 42" src="https://github.com/ollo69/ha-smartthinq-sensors/assets/4824730/159d6f87-0d25-43fb-a125-ff8701693b00">

**Environment details:**
 - Environment HASSIO in Raspberry
 - Home Assistant version installed: 2024.3.0
 - Component version installed: v0.38.7
 - Last know working version: v0.38.6
 - LG device type and model with issue: all models
 - LG devices connected (list):
 - RAC_056905_WW-RAC (AC)
 - RAC_056905_WW-RAC (AC)
 - RAC_056905_WW-RAC (AC)
 - 2REB1GLVB1___-BF (REFRIGERATOR)
 - REF11EIISP_2-FD (REFRIGERATOR)
 - F_W7_D___W.B_2QEUK-FL (WASHER)
 - D0211-DW (DISHWASHER)

**Output of HA logs**
Este error se originó a partir de una integración personalizada.

Registrador: custom_components.smartthinq_sensors
Fuente: custom_components/smartthinq_sensors/__init__.py:294
integración: SmartThinQ LGE Sensors (documentación, problemas)
Ocurrió por primera vez: 08:58:08 (1 ocurrencias)
Último inicio de sesión: 08:58:08

Connection not available. ThinQ platform not ready
Traceback (most recent call last):
  File "/config/custom_components/smartthinq_sensors/__init__.py", line 294, in async_setup_entry
    lge_devices, unsupported_devices, discovered_devices = await lge_devices_setup(
                                                           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/smartthinq_sensors/__init__.py", line 618, in lge_devices_setup
    if not await init_device(lge_dev, device_info, root_dev):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/smartthinq_sensors/__init__.py", line 574, in init_device
    if not await dev.init_device():
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/smartthinq_sensors/__init__.py", line 447, in init_device
    if not await self._device.init_device_info():
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/smartthinq_sensors/wideq/device.py", line 467, in init_device_info
    self._model_data = await self._client.model_url_info(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/smartthinq_sensors/wideq/core_async.py", line 1705, in model_url_info
    if not (model_url_info := await self._load_json_info(url)):
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/smartthinq_sensors/wideq/core_async.py", line 1634, in _load_json_info
    content = await self._auth.gateway.core.http_get_bytes(info_url)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/smartthinq_sensors/wideq/core_async.py", line 312, in http_get_bytes
    async with self._get_session().get(
  File "/usr/local/lib/python3.12/site-packages/aiohttp/client.py", line 1194, in __aenter__
    self._resp = await self._coro
                 ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/client.py", line 504, in _request
    with timer:
  File "/usr/local/lib/python3.12/site-packages/aiohttp/helpers.py", line 735, in __exit__
    raise asyncio.TimeoutError from None
TimeoutError

```

```

**Additional context**
I try to update with last version and the problem persists

**Comment by Fremencz** [comment]
I have exactly the same problem.

**Comment by santo76** [comment]
Hello
it's working now, i haven't done anything and it works againg.

i have not restarted HA and it's working, 
close issue
