### ISSUE TITLE
Switching AC on and setting a temperature at the same time doesn't work

### ISSUE THREAD

**Issue by kwridan** [ollo69/ha-smartthinq-sensors#771]
**Describe the bug**

I have an LG duct AirCon configured in homeassitant via this integration and exposed to HomeKit. When the AC is off, attempting to switch it on via HomeKit successfully switches it on, however doesn't respect the temperature selected (it defaults to 24℃), manually changing the temperature subsequently works. 

**Expected behavior**
The temperature selected should be respected.

**Screenshots**
n/a

**Environment details:**
 - Environment (HASSIO, Raspbian, etc): 
 - Home Assistant version installed: 2024.6.0
 - Component version installed: v0.39.2
 - Last know working version: n/a
 - LG device type and model with issue: DUCT_626301_WW-DUCT
 - LG devices connected (list):

**Output of HA logs**

```
2024-07-07 18:36:59.526 ERROR (MainThread) [homeassistant.core] Error executing service: <ServiceCall climate.set_temperature (c:...): entity_id=['climate.my_ac'], hvac_mode=cool, temperature=22.5>
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/core.py", line 2761, in _run_service_call_catch_exceptions
    await coro_or_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 2784, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 977, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1049, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 922, in async_service_temperature_set
    await entity.async_set_temperature(**kwargs)
  File "/config/custom_components/smartthinq_sensors/climate.py", line 388, in async_set_temperature
    await self._device.set_target_temp(new_temp)
  File "/config/custom_components/smartthinq_sensors/wideq/devices/ac.py", line 741, in set_target_temp
    await self.set(keys[0], keys[1], key=keys[2], value=conv_temp)
  File "/config/custom_components/smartthinq_sensors/wideq/devices/ac.py", line 892, in set
    await super().set(
  File "/config/custom_components/smartthinq_sensors/wideq/device.py", line 590, in set
    await self._set_control(
  File "/config/custom_components/smartthinq_sensors/wideq/device.py", line 551, in _set_control
    await self._client.session.device_v2_controls(
  File "/config/custom_components/smartthinq_sensors/wideq/core_async.py", line 1322, in device_v2_controls
    res = await self.post2(cmd_path, payload)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/smartthinq_sensors/wideq/core_async.py", line 1079, in post2
    return await self._auth.gateway.core.lgedm2_post(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/smartthinq_sensors/wideq/core_async.py", line 393, in lgedm2_post
    return self._manage_lge_result(out, is_api_v2)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/smartthinq_sensors/wideq/core_async.py", line 406, in _manage_lge_result
    raise exc.APIError(message, code)
custom_components.smartthinq_sensors.wideq.core_exceptions.APIError: 0103 - {'data': ''}
```

**Additional context**

Testing this a bit further, it might not be specific to HomeKit, manually invoking the service in home assistant to set the temperature and hvac mode when the AC is switched off results in the same behaviour where the temperature defaults to 24℃ just doesn't produce the error above.

```
service: climate.set_temperature
target:
  device_id: #...<device-id>
data:
  temperature: 22.5
  hvac_mode: cool
```

Could it be that the ThinQ API doesn't support setting the hvac mode and temperature at the same time?

Thanks! 🙏

**Comment by qemical** [comment]
It happens the same to me. I always put a delay of a second and then I set temp.

**Comment by baszalmstra** [comment]
I am running into the same issue but for me it also happens if I just try to change the HVAC mode from off to anything else. 

I see this in the logs:

```
2024-09-14 11:25:48.679 ERROR (MainThread) [homeassistant.core] Error executing service: <ServiceCall climate.set_hvac_mode (c:01J7QXMMS2N246E037EZTWQP8A): entity_id=['climate.ac_attic'], hvac_mode=cool>
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/core.py", line 2781, in _run_service_call_catch_exceptions
    await coro_or_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 2804, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 996, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1068, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/config/custom_components/smartthinq_sensors/climate.py", line 333, in async_set_hvac_mode
    await self._device.set_op_mode(operation_mode)
  File "/config/custom_components/smartthinq_sensors/wideq/devices/ac.py", line 688, in set_op_mode
    await self.set(keys[0], keys[1], key=keys[2], value=mode_value)
  File "/config/custom_components/smartthinq_sensors/wideq/devices/ac.py", line 892, in set
    await super().set(
  File "/config/custom_components/smartthinq_sensors/wideq/device.py", line 590, in set
    await self._set_control(
  File "/config/custom_components/smartthinq_sensors/wideq/device.py", line 551, in _set_control
    await self._client.session.device_v2_controls(
  File "/config/custom_components/smartthinq_sensors/wideq/core_async.py", line 1322, in device_v2_controls
    res = await self.post2(cmd_path, payload)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/smartthinq_sensors/wideq/core_async.py", line 1079, in post2
    return await self._auth.gateway.core.lgedm2_post(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/smartthinq_sensors/wideq/core_async.py", line 393, in lgedm2_post
    return self._manage_lge_result(out, is_api_v2)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/smartthinq_sensors/wideq/core_async.py", line 406, in _manage_lge_result
    raise exc.APIError(message, code)
custom_components.smartthinq_sensors.wideq.core_exceptions.APIError: 0103 - {'data': ''}
```

**Comment by yiskang** [comment]
Same here 

```
Logger: homeassistant.core
Source: core.py:2781
First occurred: September 25, 2024 at 10:05:31 PM (4 occurrences)
Last logged: 10:00:31 PM

Error executing service: <ServiceCall climate.set_temperature (c:...): entity_id=['climate.air_conditioner'], hvac_mode=cool, temperature=27.0>
Error executing service: <ServiceCall climate.set_temperature (c:...): entity_id=['climate.air_conditioner'], temperature=27.0>
Error executing service: <ServiceCall climate.set_temperature (c:...): entity_id=['climate.air_conditioner'], hvac_mode=cool, temperature=27.0>
Error executing service: <ServiceCall climate.set_temperature (c:...): entity_id=['climate.air_conditioner'], hvac_mode=cool, temperature=27.0>
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/core.py", line 2781, in _run_service_call_catch_exceptions
    await coro_or_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 2804, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 996, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1068, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 951, in async_service_temperature_set
    await entity.async_set_temperature(**kwargs)
  File "/config/custom_components/smartthinq_sensors/climate.py", line 388, in async_set_temperature
    await self._device.set_target_temp(new_temp)
  File "/config/custom_components/smartthinq_sensors/wideq/devices/ac.py", line 741, in set_target_temp
    await self.set(keys[0], keys[1], key=keys[2], value=conv_temp)
  File "/config/custom_components/smartthinq_sensors/wideq/devices/ac.py", line 892, in set
    await super().set(
  File "/config/custom_components/smartthinq_sensors/wideq/device.py", line 590, in set
    await self._set_control(
  File "/config/custom_components/smartthinq_sensors/wideq/device.py", line 551, in _set_control
    await self._client.session.device_v2_controls(
  File "/config/custom_components/smartthinq_sensors/wideq/core_async.py", line 1322, in device_v2_controls
    res = await self.post2(cmd_path, payload)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/smartthinq_sensors/wideq/core_async.py", line 1079, in post2
    return await self._auth.gateway.core.lgedm2_post(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/smartthinq_sensors/wideq/core_async.py", line 393, in lgedm2_post
    return self._manage_lge_result(out, is_api_v2)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/smartthinq_sensors/wideq/core_async.py", line 406, in _manage_lge_result
    raise exc.APIError(message, code)
custom_components.smartthinq_sensors.wideq.core_exceptions.APIError: 0103 - {'data': ''}
```

**Comment by ollo69** [comment]
Does setting the single values work properly?

**Comment by kwridan** [comment]
Thanks @ollo69 

Yes, once the unit is already on, setting a specific temperature subsequently works.

**Comment by ollo69** [comment]
Ok, so I will try to just invert the sequence, may be this is just the cause of the issue

**Comment by qemical** [comment]
Thanks @ollo69 ! Now setting temperature with HVAC mode works good, but still running with the issue on the climate card:

![image](https://github.com/user-attachments/assets/ca21bd69-acb4-4e88-ae5f-f9b476ad58c0)

If I press COOL MODE with a temperature set on the screen , AC is turning on with the old TEMP device had before. If I change the temperature when device is already on, everything works good.

Send you the DIAG logs. I switched AC with a temp of 19. But the AC started with 20. After a few seconds, real temp displayed by the AC is updated in the climate card.

Many many thanks!

`2024-10-15 12:05:03.160 DEBUG (MainThread) [custom_components.smartthinq_sensors.wideq.device] Setting new state for device 2d03e190-2a73-1f17-8789-4cbce993f20b:  basicCtrl - Set - airState.tempState.target - 19.0
2024-10-15 12:05:03.160 DEBUG (MainThread) [custom_components.smartthinq_sensors.wideq.core_async] lgedm2_post before: https://eic-service.lgthinq.com:46030/v1/service/devices/2d03e190-2a73-1f17-8789-4cbce993f20b/control-sync
2024-10-15 12:05:03.341 DEBUG (MainThread) [custom_components.smartthinq_sensors.wideq.core_async] lgedm2_post after: {'resultCode': '0000', 'result': {'data': ''}}
2024-10-15 12:05:03.342 DEBUG (MainThread) [custom_components.smartthinq_sensors] Manually updated smartthinq_sensors-AC Living Room data
2024-10-15 12:05:03.401 DEBUG (MainThread) [custom_components.smartthinq_sensors.wideq.device] Setting new state for device 2d03e190-2a73-1f17-8789-4cbce993f20b:  basicCtrl - Set - airState.operation - 257
2024-10-15 12:05:03.401 DEBUG (MainThread) [custom_components.smartthinq_sensors.wideq.core_async] lgedm2_post before: https://eic-service.lgthinq.com:46030/v1/service/devices/2d03e190-2a73-1f17-8789-4cbce993f20b/control-sync
2024-10-15 12:05:04.104 DEBUG (MainThread) [custom_components.smartthinq_sensors.wideq.core_async] lgedm2_post after: {'resultCode': '0000', 'result': {'data': ''}}
2024-10-15 12:05:04.105 DEBUG (MainThread) [custom_components.smartthinq_sensors.wideq.device] Setting new state for device 2d03e190-2a73-1f17-8789-4cbce993f20b:  basicCtrl - Set - airState.opMode - 0
2024-10-15 12:05:04.105 DEBUG (MainThread) [custom_components.smartthinq_sensors.wideq.core_async] lgedm2_post before: https://eic-service.lgthinq.com:46030/v1/service/devices/2d03e190-2a73-1f17-8789-4cbce993f20b/control-sync
2024-10-15 12:05:04.794 DEBUG (MainThread) [custom_components.smartthinq_sensors.wideq.core_async] lgedm2_post after: {'resultCode': '0000', 'result': {'data': ''}}
2024-10-15 12:05:04.794 DEBUG (MainThread) [custom_components.smartthinq_sensors] Manually updated smartthinq_sensors-AC Living Room data
2024-10-15 12:05:21.362 DEBUG (MainThread) [custom_components.smartthinq_sensors] Updating ThinQ device AC Room
2024-10-15 12:05:21.362 DEBUG (MainThread) [custom_components.smartthinq_sensors.wideq.device] Setting new state for device 43169adf-41bc-1a06-b5e9-147f67c2a563:  allEventEnable - Set - airState.mon.timeout - 70
2024-10-15 12:05:21.362 DEBUG (MainThread) [custom_components.smartthinq_sensors.wideq.core_async] lgedm2_post before: https://eic-service.lgthinq.com:46030/v1/service/devices/43169adf-41bc-1a06-b5e9-147f67c2a563/control
2024-10-15 12:05:21.710 DEBUG (MainThread) [custom_components.smartthinq_sensors.wideq.core_async] lgedm2_post after: {'resultCode': '0000', 'result': ''}
2024-10-15 12:05:21.710 DEBUG (MainThread) [custom_components.smartthinq_sensors.wideq.device] Updating ThinQ device AC Room
2024-10-15 12:05:21.710 DEBUG (MainThread) [custom_components.smartthinq_sensors.wideq.device] Polling...
2024-10-15 12:05:21.710 DEBUG (MainThread) [custom_components.smartthinq_sensors.wideq.core_async] thinq2_get before: https://eic-service.lgthinq.com:46030/v1/service/devices/43169adf-41bc-1a06-b5e9-147f67c2a563
2024-10-15 12:05:21.832 DEBUG (MainThread) [custom_components.smartthinq_sensors.wideq.core_async] thinq2_get after: {'resultCode': '0000', 'result': {'appType': 'NUTS', 'modelAppType': 'NUTS', 'modelCountryCode': 'WW', 'countryCode': 'CY', 'modelName': 'RAC_056905_WW', 'deviceType': 401, 'deviceCode': 'AI01', 'alias': 'AC Room', 'deviceId': '43169adf-41bc-1a06-b5e9-147f67c2a563', 'fwVer': '', 'imageFileName': 'ac_home_wall_airconditioner_img.png', 'ssid': 'CytaKick', 'softapId': '', 'softapPass': '', 'macAddress': '', 'networkType': '02', 'timezoneCode': 'Asia/Nicosia', 'timezoneCodeAlias': 'Asia/Nicosia', 'utcOffset': 2, 'utcOffsetDisplay': '+02:00', 'dstOffset': 3, 'dstOffsetDisplay': '+03:00', 'curOffset': 3, 'curOffsetDisplay': '+03:00', 'sdsGuide': '{"deviceCode":"AI01"}', 'newRegYn': 'N', 'userNo': 'CY2403303960509', 'tftYn': 'N', 'deviceState': 'E', 'snapshot': {'airState.windStrength': 3.0, 'airState.wMode.lowHeating': 0.0, 'airState.diagCode': 0.0, 'airState.lightingState.displayControl': 0.0, 'airState.wDir.hStep': 1.0, 'mid': 237528172.0, 'airState.energy.onCurrent': 50.0, 'airState.wMode.airClean': 0.0, 'airState.quality.sensorMon': 0.0, 'airState.tempState.target': 20.0, 'airState.miscFuncState.autoDryRemainTime': 0.0, 'airState.operation': 0.0, 'airState.wMode.jet': 0.0, 'airState.wDir.vStep': 1.0, 'timestamp': 1728980194108.0, 'airState.powerSave.basic': 0.0, 'fwUpgradeInfo': {'upgSched': {'upgUtc': '0', 'cmd': 'none'}}, 'static': {'deviceType': '401', 'countryCode': 'CY'}, 'airState.tempState.current': 29.5, 'airState.miscFuncState.extraOp': 0.0, 'airState.reservation.sleepTime': 0.0, 'airState.miscFuncState.autoDry': 0.0, 'airState.reservation.targetTimeToStart': 0.0, 'meta': {'allDeviceInfoUpdate': False, 'messageId': 'LMwwlZBiSQmQ3QwSjJAYcA'}, 'online': True, 'airState.opMode': 0.0, 'airState.reservation.targetTimeToStop': 0.0, 'airState.filterMngStates.maxTime': 0.0, 'airState.filterMngStates.useTime': 0.0}, 'online': True, 'platformType': 'thinq2', 'area': 124054, 'regDt': 20240414104109.0, 'blackboxYn': 'Y', 'modelProtocol': 'STANDARD', 'receipeVersion': 0, 'activeSaving': 'OFF', 'smartCareV2': 'OFF', 'order': 0, 'nlpAlias': 'none', 'drServiceYn': 'N', 'fwInfoList': [{'checksum': '00000409', 'order': 1.0, 'partNumber': 'SAA38690409'}], 'modemConfig': {'support_dst': 'y', 'online_check': 'y'}, 'brandType': 'common', 'regDtUtc': '20240414074109', 'regIndex': 0, 'groupableYn': 'Y', 'controllableYn': 'Y', 'combinedProductYn': 'N', 'masterYn': 'Y', 'initDevice': False, 'firebaseLogKey': 'P:SD', 'manufacture': {'inventoryOrg': 'EAT', 'macAddress': '14:7F:67:C2:A5:63', 'manufactureModel': 'S3-M09JA3FA', 'manufacturedAt': '2024-02-12T07:31:15+00:00', 'registeredAt': '2024-02-12T08:05:46.841876+00:00', 'salesModel': 'S3-M09JA3FA', 'serialNo': '402TKRT26438'}, 'upgradableYn': 'N', 'autoFwDownloadYn': 'N', 'csUpgradableYn': 'N', 'foodPoisonIndex': '0', 'matterYn': 'N', 'tclcount': 0}}
2024-10-15 12:05:21.832 DEBUG (MainThread) [custom_components.smartthinq_sensors] ThinQ status updated
2024-10-15 12:05:21.832 DEBUG (MainThread) [custom_components.smartthinq_sensors] Finished fetching smartthinq_sensors-AC Room data in 0.470 seconds (success: True)
2024-10-15 12:05:34.023 DEBUG (MainThread) [custom_components.smartthinq_sensors] Updating ThinQ device AC Living Room
2024-10-15 12:05:34.023 DEBUG (MainThread) [custom_components.smartthinq_sensors.wideq.device] Setting new state for device 2d03e190-2a73-1f17-8789-4cbce993f20b:  allEventEnable - Set - airState.mon.timeout - 70
2024-10-15 12:05:34.023 DEBUG (MainThread) [custom_components.smartthinq_sensors.wideq.core_async] lgedm2_post before: https://eic-service.lgthinq.com:46030/v1/service/devices/2d03e190-2a73-1f17-8789-4cbce993f20b/control
2024-10-15 12:05:34.150 DEBUG (MainThread) [custom_components.smartthinq_sensors.wideq.core_async] lgedm2_post after: {'resultCode': '0000', 'result': ''}
2024-10-15 12:05:34.150 DEBUG (MainThread) [custom_components.smartthinq_sensors.wideq.device] Updating ThinQ device AC Living Room
2024-10-15 12:05:34.150 DEBUG (MainThread) [custom_components.smartthinq_sensors.wideq.device] Polling...
2024-10-15 12:05:34.150 DEBUG (MainThread) [custom_components.smartthinq_sensors.wideq.core_async] thinq2_get before: https://eic-service.lgthinq.com:46030/v1/service/devices/2d03e190-2a73-1f17-8789-4cbce993f20b
2024-10-15 12:05:34.272 DEBUG (MainThread) [custom_components.smartthinq_sensors.wideq.core_async] thinq2_get after: {'resultCode': '0000', 'result': {'appType': 'NUTS', 'modelAppType': 'NUTS', 'modelCountryCode': 'WW', 'countryCode': 'CY', 'modelName': 'RAC_056905_WW', 'deviceType': 401, 'deviceCode': 'AI01', 'alias': 'AC Living Room', 'deviceId': '2d03e190-2a73-1f17-8789-4cbce993f20b', 'fwVer': '', 'imageFileName': 'ac_home_wall_airconditioner_img.png', 'ssid': 'CytaKick', 'softapId': '', 'softapPass': '', 'macAddress': '', 'networkType': '02', 'timezoneCode': 'Asia/Nicosia', 'timezoneCodeAlias': 'Asia/Nicosia', 'utcOffset': 2, 'utcOffsetDisplay': '+02:00', 'dstOffset': 3, 'dstOffsetDisplay': '+03:00', 'curOffset': 3, 'curOffsetDisplay': '+03:00', 'sdsGuide': '{"deviceCode":"AI01"}', 'newRegYn': 'N', 'userNo': 'CY2403303960509', 'tftYn': 'N', 'deviceState': 'E', 'snapshot': {'airState.windStrength': 4.0, 'airState.wMode.lowHeating': 0.0, 'airState.diagCode': 0.0, 'airState.lightingState.displayControl': 0.0, 'airState.wDir.hStep': 0.0, 'mid': 240460997.0, 'airState.energy.onCurrent': 66.0, 'airState.wMode.airClean': 0.0, 'airState.quality.sensorMon': 0.0, 'airState.tempState.target': 20.0, 'airState.miscFuncState.autoDryRemainTime': 0.0, 'airState.operation': 1.0, 'airState.wMode.jet': 0.0, 'airState.wDir.vStep': 0.0, 'timestamp': 1728983125989.0, 'airState.powerSave.basic': 0.0, 'fwUpgradeInfo': {'upgSched': {'upgUtc': '0', 'cmd': 'none'}}, 'static': {'deviceType': '401', 'countryCode': 'CY'}, 'airState.tempState.current': 28.5, 'airState.miscFuncState.extraOp': 0.0, 'airState.reservation.sleepTime': 0.0, 'airState.miscFuncState.autoDry': 0.0, 'airState.reservation.targetTimeToStart': 0.0, 'meta': {'allDeviceInfoUpdate': False, 'messageId': 'IuRRlpffQyqUq3prIqt8sQ'}, 'online': True, 'airState.opMode': 0.0, 'airState.reservation.targetTimeToStop': 0.0, 'airState.filterMngStates.maxTime': 0.0, 'airState.filterMngStates.useTime': 0.0}, 'online': True, 'platformType': 'thinq2', 'area': 124054, 'regDt': 20240414104403.0, 'blackboxYn': 'Y', 'modelProtocol': 'STANDARD', 'receipeVersion': 0, 'activeSaving': 'OFF', 'smartCareV2': 'OFF', 'order': 0, 'nlpAlias': 'none', 'drServiceYn': 'N', 'fwInfoList': [{'checksum': '00000409', 'order': 1.0, 'partNumber': 'SAA38690409'}], 'modemConfig': {'support_dst': 'y', 'online_check': 'y'}, 'brandType': 'common', 'regDtUtc': '20240414074403', 'regIndex': 0, 'groupableYn': 'Y', 'controllableYn': 'Y', 'combinedProductYn': 'N', 'masterYn': 'Y', 'initDevice': False, 'firebaseLogKey': 'P:SD', 'manufacture': {'inventoryOrg': 'EAT', 'macAddress': '4C:BC:E9:93:F2:0B', 'manufactureModel': 'S3-M24K23FA', 'manufacturedAt': '2022-03-25T05:51:10+00:00', 'registeredAt': '2022-03-25T18:05:20.585736+00:00', 'salesModel': 'S3-M24K23FA', 'serialNo': '203TKRTD1094'}, 'upgradableYn': 'N', 'autoFwDownloadYn': 'N', 'csUpgradableYn': 'N', 'foodPoisonIndex': '0', 'matterYn': 'N', 'tclcount': 0}}
2024-10-15 12:05:34.272 DEBUG (MainThread) [custom_components.smartthinq_sensors] ThinQ status updated
2024-10-15 12:05:34.272 DEBUG (MainThread) [custom_components.smartthinq_sensors] Finished fetching smartthinq_sensors-AC Living Room data in 0.249 seconds (success: True)
2024-10-15 12:05:37.200 DEBUG (MainThread) [custom_components.smartthinq_sensors.wideq.device] Setting new state for device 2d03e190-2a73-1f17-8789-4cbce993f20b:  basicCtrl - Set - airState.operation - 0
2024-10-15 12:05:37.200 DEBUG (MainThread) [custom_components.smartthinq_sensors.wideq.core_async] lgedm2_post before: https://eic-service.lgthinq.com:46030/v1/service/devices/2d03e190-2a73-1f17-8789-4cbce993f20b/control-sync
2024-10-15 12:05:37.941 DEBUG (MainThread) [custom_components.smartthinq_sensors.wideq.core_async] lgedm2_post after: {'resultCode': '0000', 'result': {'data': ''}}
2024-10-15 12:05:37.941 DEBUG (MainThread) [custom_components.smartthinq_sensors] Manually updated smartthinq_sensors-AC Living Room data
2024-10-15 12:05:37.944 DEBUG (MainThread) [custom_components.smartthinq_sensors.wideq.device] Setting new state for device 43169adf-41bc-1a06-b5e9-147f67c2a563:  basicCtrl - Set - airState.operation - 0
2024-10-15 12:05:37.944 DEBUG (MainThread) [custom_components.smartthinq_sensors.wideq.core_async] lgedm2_post before: https://eic-service.lgthinq.com:46030/v1/service/devices/43169adf-41bc-1a06-b5e9-147f67c2a563/control-sync
2024-10-15 12:05:37.947 DEBUG (MainThread) [custom_components.smartthinq_sensors.wideq.device] Setting new state for device 2d03e190-2a73-1f17-8789-4cbce993f20b:  basicCtrl - Set - airState.operation - 0
2024-10-15 12:05:37.947 DEBUG (MainThread) [custom_components.smartthinq_sensors.wideq.core_async] lgedm2_post before: https://eic-service.lgthinq.com:46030/v1/service/devices/2d03e190-2a73-1f17-8789-4cbce993f20b/control-sync
2024-10-15 12:05:38.673 DEBUG (MainThread) [custom_components.smartthinq_sensors.wideq.core_async] lgedm2_post after: {'resultCode': '0000', 'result': {'data': ''}}
2024-10-15 12:05:38.673 DEBUG (MainThread) [custom_components.smartthinq_sensors] Manually updated smartthinq_sensors-AC Room data
2024-10-15 12:05:38.831 DEBUG (MainThread) [custom_components.smartthinq_sensors.wideq.core_async] lgedm2_post after: {'resultCode': '0000', 'result': {'data': ''}}
2024-10-15 12:05:38.831 DEBUG (MainThread) [custom_components.smartthinq_sensors] Manually updated smartthinq_sensors-AC Living Room data`
