### ISSUE TITLE
Airco: Reservation sleep time is not available

### ISSUE THREAD

**Issue by erkr** [ollo69/ha-smartthinq-sensors#846]
**Describe the bug**
Thanks for the great efforts spend on this integration for LG devices!
I ran into a bug. When I set the sleeptimer like this:
``` 
action: smartthinq_sensors.set_sleep_time
data:
  sleep_time: 60
target:
  entity_id: climate.slaapkamer_airco
``` 
That works when the airco is in `cool` mode. But not in `heat` mode. In that mode I get this error: `Reservation sleep time is not available`.

**Expected behavior**
Should also work in `heat` mode. With the official app the mode doesn't matter, so I guess it's just not implemented for all modes by this integration.
**Screenshots**

**Environment details:**
 - Environment: HASSIO,
 - Home Assistant version installed: 2024.12.5
 - Component version installed: 0.40.3
 - Last know working version: na
 - LG device type and model with issue: LG ⸱ RAC_056905_WW-RAC (AC)
 - LG devices connected (list):
3 devices
**Output of HA logs**
Paste the relavant output of the HA log here.

```
Logger: homeassistant.helpers.script.websocket_api_script
Source: helpers/script.py:526
First occurred: 10:06:41 (2 occurrences)
Last logged: 10:07:04

websocket_api script: Error executing script. Unexpected error for call_service at pos 1: Reservation sleep time is not available
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 526, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 764, in _async_call_service_step
    response_data = await self._async_run_long_action(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<9 lines>...
    )
    ^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 727, in _async_run_long_action
    return await long_task
           ^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2802, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2845, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1007, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
        hass, entity, func, data, call.context
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1079, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/config/custom_components/smartthinq_sensors/climate.py", line 473, in async_set_sleep_time
    await self._device.set_reservation_sleep_time(sleep_time)
  File "/config/custom_components/smartthinq_sensors/wideq/devices/ac.py", line 879, in set_reservation_sleep_time
    raise ValueError("Reservation sleep time is not available")
ValueError: Reservation sleep time is not available
```

**Additional context**

**Comment by mick96** [comment]
I’m experiencing the same issue. I’ve attached the debug logging output file for reference. However, I’m not sure if it’s helpful, as I don’t know how to interpret its contents.
[error_log-sleepTimerAction.zip](https://github.com/user-attachments/files/18402241/error_log-sleepTimerAction.zip)

**Comment by erkr** [comment]
Bump

**Comment by erkr** [comment]
Please have a look into this issue. I would like to use my timers for all modes, not only cooling

**Comment by erkr** [comment]
Pretty, Pretty, Pretty, Pretty, Pretty please 🙏

**Comment by erkr** [comment]
🥹

**Comment by erkr** [comment]
Ping
