### ISSUE TITLE
wideq.core_exceptions.InvalidCredentialError

### ISSUE THREAD

**Issue by garyt72** [ollo69/ha-smartthinq-sensors#86]
**Describe the bug**
This started today after updating to HA 0.115.1 had been working for many months prior to this evening.
Entities are unavailable, and getting these errors after providing redirect URL after a successful login:

```
2020-09-18 22:42:30 ERROR (SyncWorker_58) [custom_components.smartthinq_sensors] Error connecting to ThinQ
Traceback (most recent call last):
  File "/srv/hass/conf/custom_components/smartthinq_sensors/__init__.py", line 128, in createClientFromToken
    oauth_url, token, oauth_user_num, self._region, self._language
  File "/srv/hass/conf/custom_components/smartthinq_sensors/wideq/core_v2.py", line 736, in from_token
    client.refresh()
  File "/srv/hass/conf/custom_components/smartthinq_sensors/wideq/core_v2.py", line 718, in refresh
    self._load_devices()
  File "/srv/hass/conf/custom_components/smartthinq_sensors/wideq/core_v2.py", line 592, in _load_devices
    self._devices = self._session.get_devices()
  File "/srv/hass/conf/custom_components/smartthinq_sensors/wideq/core_v2.py", line 441, in get_devices
    dashboard = self.get2("service/application/dashboard")
  File "/srv/hass/conf/custom_components/smartthinq_sensors/wideq/core_v2.py", line 433, in get2
    language=self.auth.gateway.language,
  File "/srv/hass/conf/custom_components/smartthinq_sensors/wideq/core_v2.py", line 150, in thinq2_get
    raise API2_ERRORS[code]()
custom_components.smartthinq_sensors.wideq.core_exceptions.InvalidCredentialError
2020-09-18 22:42:30 ERROR (MainThread) [custom_components.smartthinq_sensors.config_flow] LGE ThinQ: Invalid Login info!

```

**Environment details:**
 - Environment (HASSIO, Raspbian, etc):  Ubuntu 18.04.5 LTS
 - Home Assistant version installed: 0.115.1
 - Component version installed: 1.5.2
 - Last know working version: 1.5.2
 - LG device type and model with issue:  Refrigerator
 - LG devices connected (list): Refrigerator

**Output of HA logs**
Included above

**Comment by garyt72** [comment]
After more poking around, I found that I needed to accept new terms in the mobile app.  After doing that, I had to download a new version of the app, then accept more terms.  

After doing all of the above, I was able to complete the authentication process successfully.

**Comment by rwarner** [comment]
Thank you for posting this and saving me hours of time.

@ollo69 would it be worth adding a note somewhere in the Integration workflow to "Double check accepting TOS in the LG mobile app" if authentication is unsuccessful?
